### ISSUE TITLE
ErrorBoundary caught status 200 loader Response

### ISSUE THREAD

**Issue by ttys026** [remix-run/remix#10016]
### Reproduction

Please see https://stackblitz.com/edit/remix-run-remix-6kxa37?file=app%2Froutes%2F_index.tsx for reproduce

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.12.1 
    @remix-run/node: * => 2.12.1 
    @remix-run/react: * => 2.12.1 
    @remix-run/serve: * => 2.12.1 
    vite: ^5.1.0 => 5.4.7
```

### Used Package Manager

npm

### Expected Behavior

Given the description here, if loader throw a response instance with status 200, should't be caught by ErrorBoundary
![image](https://github.com/user-attachments/assets/cb070d95-caee-4ba1-bab7-81a0698f58f4)

### Actual Behavior

ErrorBoundary caught status 200 loader response

**Comment by ttys026** [comment]
I am not sure if this is the expected behavior. I noticed that Remix sets the "x-remix-catch" header, which causes it to go into the ErrorBoundary. Redirect responses are bypassed, but not 200 requests.
https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/server.ts#L358.

In this case, I can't prevent this unless I `return` a response instead of `throw` a response, but this introduces an unwanted TypeScript inference in my case.

**Comment by brophdawg11** [comment]
This is expected behavior - an "error response" is a `Response` thrown from a loader/action - status code doesn't matter.  The vast majority of the time, folks throw 4xx/5xx responses but we'd be happy to accept a PR changing the code comment to remove the 4xx/5xx reference to avoid confusion via intellisense.

The `throw` versus `return` decision is about what do you want to render - your `Component` or your `ErrorBoundary`?
