### ISSUE TITLE
Could not clone the remix tutorial template

### ISSUE THREAD

**Issue by alamenai** [remix-run/remix#10289]
### Reproduction

I'm new to Remix 😄 !

I started learning the tutorial and when I wanted to clone the template each attempt I faced this issue : 

![image](https://github.com/user-attachments/assets/4e8e4341-76b7-4fa6-9076-42251c9a0b58)

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13620H
    Memory: 7.70 GB / 15.35 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
    pnpm: 9.3.0 - ~/.nvm/versions/node/v22.1.0/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.58
```

### Used Package Manager

npm

### Expected Behavior

Setup the project with the default tutorial template by Remix.

### Actual Behavior

 ▲  Oh no! There was a problem fetching the file from GitHub. The request responded with a 404 status. Please try again later.

![image](https://github.com/user-attachments/assets/a3b7fb9a-3d6e-4931-a428-f3766b75c20f)

**Comment by brookslybrand** [comment]
Hey @alamenai, I can't replicate this, I wonder if GitHub was having a bad day at the time. Sorry you were having a bad experience either way

At this point, I do recommend you try out the [React Router v7 tutorial](https://reactrouter.com/tutorials/address-book), since that's the next version of Remix [context](https://remix.run/blog/incremental-path-to-react-19)

**Comment by alamenai** [comment]
Thank you @brookslybrand , yes when I tried it next day, it works.
