### ISSUE TITLE
[Bug]: MetaFunction data differs on server vs client

### ISSUE THREAD

**Issue by Ehesp** [remix-run/remix#1054]
### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16.1.0

### Steps to Reproduce

Throw a 404 within a loader and log out the MetaFunction arguments:

```ts
// routes/foo.tsx
export const loader: LoaderFunction = async () => {
  throw json({ foo: 'bar' }, 404);
};

export const meta: MetaFunction = (args) => {
  console.log(args);
  return {
    title: 'Remix Starter',
    description: 'Welcome to remix!',
  };
};
```

### Expected Behavior

I expected the `data` in the `MetaFunction` to always be `{ foo: 'bar' }` on both client and server. 

### Actual Behavior

When loading the `/foo` page via a server request, the `data` argument of `MetaFunction` is `undefined`:

```js
{
  data: undefined,
  parentsData: { root: null },
  params: {},
  location: {
    pathname: '/foo',
    search: '',
    hash: '',
    state: null,
    key: 'default'
  }
}
```

However, if you client navigate to the `/foo` page, the data comes through as expected:

![image](https://user-images.githubusercontent.com/842078/146197801-5b608a02-cc70-4545-b17a-ecddd795943b.png)

Since I'm providing the data myself, I was experiencing an error accessing my object on the server (cannot read property of undefined), however on client navigation the page loaded as expected with the correct meta information.

I created a [reproduction](https://stackblitz.com/edit/node-xxkqxr?file=app/root.tsx) of this happening.

**Comment by silvenon** [comment]
Also, semi-related, but why does the `meta` function run in the client at all? Am I missing some obvious use case where this would be useful?

**Comment by giubatt** [comment]
I just ran into this bug while doing the Jokes App tutorial

After enabling javascript I tried throwing some errors on loaders to test the error boundaries and noticed this bug. When the route is rendered on the server and an error is thrown on the loader, the meta receives `data` as undefined, but after client-side navigation gets a thrown error on the loader, the meta function receives the thrown error in the `data`.

Is this expected behavior?

#2536 Seems to be on the right track to solve this

**Comment by dmarkow** [comment]
Having the same issue. We use loader data to set page titles quite a bit. If a server rendered page throws a response, `data` is undefined. If the page was navigated to on the client side, `data` contains a `CatchValue` object. We were already using optional chaining on the `data` object in case it was undefined, but because of the client side rendering data being present, we had to change to use optional chaining on the entire path to avoid errors, e.g. `{ title: data?.user?.name }`. This at least avoids client side crashes, but if any of our actual data uses the keys `data`, `status`, or `statusText`, it could possibly show the catch value data instead of our app's data.

The [documentation](https://remix.run/docs/en/v1/api/conventions#page-context-in-meta-function) seems to imply that as long as `data` is present, you can expect it to be your loader data.

**Comment by dmarkow** [comment]
Actually, the [entire example in the documentation](https://remix.run/docs/en/v1/api/conventions#page-context-in-meta-function) is broken. The sample there only works as described with SSR. If it was client rendered, data *is* present:

```typescript
// Loader throws a response using:
throw new Response("Not Found", {
  status: 404,
});


export const meta: MetaFunction = ({ data, params }) => {
  // data is undefined here only during SSR. CSR actually populates data with an object:
  // '{"status":404,"statusText":"Not Found","data":"Not Found"}'
  if (!data) {
    return {
      title: "Missing Shake",
      description: `There is no shake with the ID of ${params.shakeId}. 😢`,
    };
  }

  // So this breaks and will cause an error when trying to read `shake.name` since `shake` will be undefined
  // TypeError: Cannot read properties of undefined (reading 'name')
  const { shake } = data as LoaderData;
  return {
    title: `${shake.name} milkshake`,
    description: shake.summary,
  };
};

**Comment by kiliman** [comment]
I think the issue is that Remix should not send catch data to the meta function. `data` should always represent loader data.

**Comment by danecando** [comment]
It also sends regular errors thrown from a render as `data` to the meta function. Really confusing behavior feel like I'm having to do some excessive type guarding to handle all the edge cases for what `data` can be

**Comment by danecando** [comment]
I just upgraded my app to v2 meta tags on the latest remix release and removed all the type guards. It looks like this one can probably be closed.

related: https://github.com/remix-run/remix/pull/2536

**Comment by ryanflorence** [comment]
```tsx
  fixture = await createFixture({
    files: {
      "app/routes/_index.tsx": js`
        import { json } from "@remix-run/node";
        import { useLoaderData, useRouteError } from "@remix-run/react";

        export function loader() {
          throw json({ foo: 'bar' }, 404)
        }

        export function meta(args) {
          console.log(args);
          return [{ title: 'Hello World' }];
        }

        export function ErrorBoundary() {
          let error = useRouteError();
          return <pre>Boundary: {JSON.stringify(error, null, 2)}</pre>;
        }

        export default function Index() {
          let data = useLoaderData();
          return <pre>Component: {JSON.stringify(data, null, 2)}</pre>;
        }
      `,
    },
  });
```

This test:

1. Passes `undefined` to `args.data` in `meta` for SSR and client rendering
2. Renders the ErrorBoundary

Looks like we've fixed this somewhere along the way. Thanks for the report!

![Image](https://github.com/remix-run/remix/assets/100200/0b2c11d2-065d-4bbd-b6eb-fb0601d28ef4)

**Comment by Ehesp** [comment]
Cheers :)
