### ISSUE TITLE
[Feature]: Client only routes

### ISSUE THREAD

**Issue by arvigeus** [remix-run/remix#1107]
### What is the new or updated feature that you are suggesting?

Title says it all.

### Why should this feature be included?

I tried to rewrite a small project in Remix, only to find it was impossible because a package I use cannot be server rendered. Often these things cannot be known in advance, would be terribly frustrating for someone else who already invested days building something.

**Comment by universse** [comment]
I came across this a while ago. It could be useful. https://github.com/sergiodxa/remix-utils/blob/main/src/react/client-only.tsx

**Comment by arvigeus** [comment]
This seems like a better solution. I think it should be part of the official release. Maintainers can close this issue in that case.

**Comment by sergiodxa** [comment]
@arvigeus if you have a package that can't be used server-side (e.g. because it uses browser APIs outside an useEffect or in the whole module) you could re-export them from a `.client.ts|js` file.

```ts
export * from "my-browser-only-compatible-package";
```

Then in your routes, import from that file, and if it's a component, you can render it inside the ClientOnly component from Remix Utils

```ts
import Component from "~/components/something.client"

export default function Screen() {
  return <ClientOnly><Component /></ClientOnly>;
}
```

That should work.

**Comment by arvigeus** [comment]
Thank you so much, @sergiodxa ! Unfortunately it did not work again (same error).

This produced a slightly different error though:

```jsx
import { lazy, Suspense } from "react";
import { ClientOnly } from "remix-utils";

const Editor = lazy(() => import("react-simple-code-editor"));
...
<ClientOnly fallback={null}>
    <Suspense fallback={null}>
        <Editor ... />
    </Suspense>
</ClientOnly>
```

**Comment by sergiodxa** [comment]
> Thank you so much, @sergiodxa ! Unfortunately it did not work again (same error).
> 
> This produced a slightly different error though:
> 
> ```js
> import { lazy, Suspense } from "react";
> import { ClientOnly } from "remix-utils";
> 
> const Editor = lazy(() => import("react-simple-code-editor"));
> ...
> <ClientOnly fallback={null}>
>     <Suspense fallback={null}>
>         <Editor ... />
>     </Suspense>
> </ClientOnly>
> ```

You can't do async imports in Remix AFAIK

```ts
// app/components/code-editor.client.ts
export * from "react-simple-code-editor":
```

```ts
// app/routes/something.tsx
import Editor from "~/components/code-editor.client";

export default function Screen() {
  return (
    <ClientOnly>
      <Editor />
    </ClientOnly>
  );
}
```

Doing that, Remix will only include the react-simple-code-editor in the client bundle and not try to render it server-side.

**Comment by sergiodxa** [comment]
> Thank you so much, @sergiodxa ! Unfortunately it did not work again (same error).
> 
> This produced a slightly different error though:
> 
> ```js
> import { lazy, Suspense } from "react";
> import { ClientOnly } from "remix-utils";
> 
> const Editor = lazy(() => import("react-simple-code-editor"));
> ...
> <ClientOnly fallback={null}>
>     <Suspense fallback={null}>
>         <Editor ... />
>     </Suspense>
> </ClientOnly>
> ```

I think this should work https://stackblitz.com/edit/node-xygzss?file=app/routes/index.tsx but I get an `Uncaught ReferenceError: global is not defined` from the that `react-simple-code-editor` library, it looks like a bug in the library, they should use window not global, maybe they are expecting Babel or webpack to replace global with window and make that work automatically and since Remix is not using them it will not work.

**Comment by arvigeus** [comment]
I think I am going offtopic here, so I will close the issue.

I solved it by forking the library, Thank you for the hints, @sergiodxa!

**Comment by universse** [comment]
@sergiodxa I can't seem to find `.client` filename convention in the doc. Is it a supported feature?

**Comment by jorissparla** [comment]
> @arvigeus if you have a package that can't be used server-side (e.g. because it uses browser APIs outside an useEffect or in the whole module) you could re-export them from a `.client.ts|js` file.
> 
> ```ts
> export * from "my-browser-only-compatible-package";
> ```
> 
> Then in your routes, import from that file, and if it's a component, you can render it inside the ClientOnly component from Remix Utils
> 
> ```ts
> import Component from "~/components/something.client"
> 
> export default function Screen() {
>   return <ClientOnly><Component /></ClientOnly>;
> }
> ```
> 
> That should work.

not using react-simple-editor, but CKEditor, and this totally worked for me, thank you!!

**Comment by nsantos16** [comment]
Same error with `react-apexcharts`, I tried your suggested approach @sergiodxa but I received this error after the fallback
<img width="1439" alt="Screen Shot 2021-12-29 at 00 44 09" src="https://user-images.githubusercontent.com/9642510/147625446-a135003f-dbdd-44fe-a93e-646e957695cd.png">

**Comment by sergiodxa** [comment]
> Same error with `react-apexcharts`, I tried your suggested approach @sergiodxa but I received this error after the fallback
> <img alt="Screen Shot 2021-12-29 at 00 44 09" width="1439" src="https://user-images.githubusercontent.com/9642510/147625446-a135003f-dbdd-44fe-a93e-646e957695cd.png">

The error mentions a promise, so I think you are doing a dynamic import? I recommend against them and instead use a .client.ts file to avoid it server side

**Comment by Alarid** [comment]
I know this issue has been closed, but I have the exact same problem and I can't find any solution. @arvigeus did you end up solving it by forking react-simple-code-editor? Care to briefly explain how please?

I still find it weird that this error is occurring, because with @sergiodxa's solution the package should never be used on the server and the component using it shouldn't render either.  I'm trying to build a playground component for a Remix project and man, what a struggle it is!

**Comment by Alarid** [comment]
Update for those interested: with the latest Remix version (1.2.3) everything works fine, even server-side 🎉
