### ISSUE TITLE
[Feature]: Firebase Firestore support pls.

### ISSUE THREAD

**Issue by simon-zhangmuye** [remix-run/remix#1214]
### What is the new or updated feature that you are suggesting?

Please support Google serverless framework like Firebase, Firestore, firebase auth, cloud storage, google analytics, google cloud function, google machine learning and so on.

### Why should this feature be included?

Firebase is the most powerful framework which is supported by Google.
It has lots of built-in features, such as extensions, auth, smtp and etc.
It is much better than AWS lambda and amplify.
It has the largest market share in product level serverless framework and will dominate the market.

**Comment by archwebio** [comment]
Hello, I would love to create an example [here](https://github.com/remix-run/remix/tree/main/examples) on  for Firebase if there's no one working on it.

**Comment by archwebio** [comment]
Hello, I would love to create an example [here](https://github.com/remix-run/remix/tree/main/examples) on for Firebase if there's no one working on it.

**Comment by Ehesp** [comment]
@simon-zhangmuye what so you mean by Firebase support? You can use Firebase easily with Remix using the Node Admin SDK.

**Comment by ccssmnn** [comment]
I'm using firebase & firestore in a remix application which is currently under development.

Just combine `firebase-admin` (nodejs) and the `firebase` (client-js) libraries in your loaders / actions. I handle the auth state with a session cookie, which can be generated with the Admin SDK ([docs](https://firebase.google.com/docs/auth/admin/manage-cookies)). You need to verify email + password with the Browser SDK on the server, which is [what they recommend](https://github.com/firebase/firebase-admin-node/issues/1141#issuecomment-765627139). The data access to Firestore is handled by firebase-admin. No need to set up security rules, since you can make the checks in your code and no client will access Firestore directly.

@archwebio have you started yet? Considering adding a firebase example, too.

**Comment by ccssmnn** [comment]
I've added a PR #1811 to add an example for Auth & Firestore with Remix.

Deployment to Cloud Functions does not seem possible, see #211

But you can run a remix express server in a Docker container and deploy it to Cloud Run.

**Comment by TheRealFlyingCoder** [comment]
Hey just chiming in on this.

Remix supports all forms of deployment to GCP (including firebase), in fact Firebase/firestore was the first platform ryan and mj deployed to.

@simon-zhangmuye if you experienced trouble with Firestore reach out in the Discord, but for now you should close this issue as it's just adding clutter.

My issue #211 isn't stopping anyone from deploying to functions, it's just an annoying thing you have to work around by passing through the context, and likely can't be resolved.

That being said, firebase functions aren't really a suitable deployment platform for Remix apps... Cold starts, and speed are pretty terrible for SSR... Cloud run is the better alternative.

**Comment by penx** [comment]
> firebase functions aren't really a suitable deployment platform for Remix apps... Cloud run is the better alternative

just to note that firebase functions v2, currently in beta, use Cloud Run:

https://firebase.google.com/docs/functions/beta
