### ISSUE TITLE
[Feature]: Why need double render?

### ISSUE THREAD

**Issue by oliviertassinari** [remix-run/remix#1325]
### What is the new or updated feature that you are suggesting?

I suspect there are two improvement opportunities with: https://remix.run/docs/en/v1/guides/styling#css-in-js-libraries.

> Some of them require a "double render" in order to extract the styles from the component tree during the server render.

Do you have more details on why?

In https://github.com/mui-org/material-ui/pull/30366 @mnajdova has updated the *MUI + emotion + remix* example to remove the double render. It seems to work great. I believe the same pattern could be applied to *styled-components*.

---

> It's unlikely this will affect performance in a significant way

A side note. My personal experience at Onepixel relative to other templating languages, and indexing about 10M pages with Next.js on Google is that React is not this fast on the server-side. Our TTFB was above 100ms. We had better performance with Rails. 1/3 was about express/redis/SQL queries, 2/3 of the time spent to get the first byte was on rendering the React tree (apollo was half of this time, we had to render React twice with apollo to extract the queries, CSS-in-JS was also adding to the slowness).

### Why should this feature be included?

To improve the guidelines.

**Comment by sergiodxa** [comment]
> ### What is the new or updated feature that you are suggesting?
> I suspect there are two improvement opportunities with: https://remix.run/docs/en/v1/guides/styling#css-in-js-libraries.
> 
> > Some of them require a "double render" in order to extract the styles from the component tree during the server render.
> 
> Do you have more details on why?
> 
> In [mui-org/material-ui#30366](https://github.com/mui-org/material-ui/pull/30366) @mnajdova has updated the _MUI + emotion + remix_ example to remove the double render. It seems to work great. I believe the same pattern could be applied to _styled-components_.

The way some CSS in JS libraries know what styles to apply when doing SSR is that your do a first render where you collect the rendered styles by the CSS in JS and then with that data you do another render where the CSS in JS library render the correct styles at the top.

Not all libraries does this.

---

> > It's unlikely this will affect performance in a significant way
> 
> A side note. My personal experience at Onepixel relative to other templating languages, and indexing about 10M pages with Next.js on Google is that React is not this fast on the server-side. Our TTFB was above 100ms. We had better performance with Rails. 1/3 was about express/redis/SQL queries, 2/3 of the time spent to get the first byte was on rendering the React tree (apollo was half of this time, we had to render React twice with apollo to extract the queries, CSS-in-JS was also adding to the slowness).
> 
> ### Why should this feature be included?
> To improve the guidelines.

If you measure the time it takes React to do SSR it will probably be less than 10ms, React is super fast to do SSR, but when you do SSR you typically also get your data server-side and that's most usually the slow part.

In my experience with Rails, their template language is slower than React doing SSR, except you are using a cache which Rails does and React doesn't do, but you could add cache, for example with Remix using [Cache-Control headers or a server-side cache](https://sergiodxa.com/articles/http-vs-server-side-cache-in-remix).

> 2/3 of the time spent to get the first byte was on rendering the React tree (apollo was half of this time, we had to render React twice with apollo to extract the queries, CSS-in-JS was also adding to the slowness)

By this, it looks like your slow problem was not React itself but Apollo and CSS in JS, if you render React once it should not be an issue anymore then.

In Remix that's most likely not an issue, because instead of using Apollo to do the data fetching you fetch in the loader server-side, once, all loaders of the same request also run in parallel to avoid issues, even if you use GraphQL you can do run the query on the loader and avoid Apollo and similar libraries, and if you don't use CSS in JS and use plain CSS (it can be with CSS frameworks of course) you will avoid the double render required for that too.

**Comment by kentcdodds** [comment]
I updated the docs and added a styled-components example in the dev branch (mistakenly didn't get it into the main branch) that gets rid of the double render.

**Comment by mnajdova** [comment]
> I updated the docs and added a styled-components example in the dev branch (mistakenly didn't get it into the main branch) that gets rid of the double render.

It is pretty much what I ended up with, the only difference was that I used a `meta` tag for the insertion point. Once this is merged in main, I will update our example to use the same string, so that it does not differ from the official documentation.

**Comment by chaance** [comment]
Closing as I believe Kent addressed this in our styled components example, but let me know if there is anything else we can do to improve the CSS-in JS story.
