### ISSUE TITLE
Propagate action set-cookie as cookie to loader

### ISSUE THREAD

**Issue by jacob-ebey** [remix-run/remix#1335]
Without propagating set-cookie as cookie to the loader, if you don't redirect your action with JS disabled when setting a cookie and accessing it in a loader, the site will be "one request behind".

Patch for `@remix-run/server-runtime@1.1.1`:

```diff
diff --git a/node_modules/@remix-run/server-runtime/server.js b/node_modules/@remix-run/server-runtime/server.js
index d723f76..3064ab7 100644
--- a/node_modules/@remix-run/server-runtime/server.js
+++ b/node_modules/@remix-run/server-runtime/server.js
@@ -21,6 +21,7 @@ var mode = require('./mode.js');
 var routes = require('./routes.js');
 var responses = require('./responses.js');
 var serverHandoff = require('./serverHandoff.js');
+var cookie = require("cookie");
 
 /**
  * The main request handler for a Remix server. This handler runs in the context
@@ -228,6 +229,8 @@ async function renderDocumentRequest({
         statusText: actionResponse.statusText
       };
 
+
+
       if (responses.isCatchResponse(actionResponse)) {
         appState.catchBoundaryRouteId = getDeepestRouteIdWithBoundary(matches, "CatchBoundary");
         appState.trackCatchBoundaries = false;
@@ -267,6 +270,18 @@ async function renderDocumentRequest({
     matchesToLoad.slice(0, -1), "ErrorBoundary");
   }
 
+  if (actionResponse) {
+    let newCookieValues = cookie.parse(request.headers.get("Cookie"));
+    for (let [name, value] of Array.from(actionResponse.headers)) {
+      if (name === "set-cookie") {
+        let cookies = cookie.parse(value.split(";")[0] || "");
+        Object.assign(newCookieValues, cookies);
+      }
+    }
+    let newCookie = Object.entries(newCookieValues).map(([name, value]) => `${name}=${encodeURIComponent(value)}`).join("; ");
+    request.headers.set("Cookie", newCookie);
+  }
+
   let routeLoaderResults = await Promise.allSettled(matchesToLoad.map(match => match.route.module.loader ? data.callRouteLoader({
     loadContext,
     match,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ryanflorence** [comment]
Hmm ...

Just take loaders/actions/remix out of the equation. You can't set a cookie for a response and read it from the request because the request comes before the response. Cookies need a round trip with the browser.

```js
http.createServer((req, res) => {
  // this is the cookie of the request
  let cookie = req.headers.cookie;

  // this is the cookie of the action response
  let newCookie = "..."
  res.writeHead("cookie", newCookie);

  // in remix loaders are called here, semantically it doesn't
  // make sense to read the cookie you just set
  res.end();
})
```

What's interesting is that with JavaScript enabled, the action request makes a round trip with the server, so the cookie set in an action *is available* to your loaders.

Without JavaScript, the cookie *is not set* in your loaders because it's all the same request.

The biggest issue here is that *we don't know if the cookie actually makes it to the browser* with this code. It might not if they have cookies disabled, so setting the cookie for loaders is an "optimistic cookie", but a potential lie.

I'm undecided on this:

- I can see the pragmatic reasons to fake the cookie in the loaders and get consistent behavior.
- That cookie, in 1 out of million cases, could be a lie. Remix's goal is to emulate the native web behaviors and then progressively enhance the experience with JavaScript. This is the reverse, this is making plain POST request act like a progressively enhanced POST with Remix. We haven't done that before. I'm not sure we want to.

**Comment by SleeplessByte** [comment]
I've ran into the same problem. Indeed cookies will always need to round-trip, so hacking the cookie storage isn't what I am looking for. What I was looking for was a way to have the results of an action override / be fetchable in a loader. Reading the above, am I right to understand that's currently not possible?

What I'm trying to do right now is submit a `<Form>` that changes a cookie-based setting. That setting is not updated in the redirect after the form is submitted, but is in the subsequent page load.

**Comment by SleeplessByte** [comment]
Whilst this is now closed, I don't believe there is a resolution.

If there is, I'd love to learn!

**Comment by herecydev** [comment]
Can we please re-open this? At a minimum the docs need to be updated with this caveat
