### ISSUE TITLE
[Feature]: Support running on Akamai EdgeWorkers

### ISSUE THREAD

**Issue by AustinGil** [remix-run/remix#1539]
### What is the new or updated feature that you are suggesting?

Adding support to run Remix on [Akamai EdgeWorkers](https://developer.akamai.com/akamai-edgeworkers-overview)

### Why should this feature be included?

Akamai is the largest CDN provider in the world with over 250,000 edge compute servers around the world. Adding support would mean even lower latency to people regardless of location. This support already exists for Cloudflare Workers. Supporting Akamai would also include more existing customers.

I'd be happy to help with a PR as well.

**Comment by andrewgadziksonos** [comment]
I took a look at this and I'm not sure it's possible to do (could be wrong).

<img width="851" alt="image" src="https://user-images.githubusercontent.com/31038519/153466747-8f5a3bb8-36e0-47ef-b04b-3ddbf12862d9.png">

`onClientRequest` is out of the question because we want to utilize the CDN cache, and this is fired before the cache is checked.  Plus `request.respondWith(...)` does not support `Set-Cookie` headers.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/31038519/153467094-ff911dcd-d354-445a-9285-7331ab54c57a.png">

`responseProvider` feels like the most appropriate choice here, but it does not support `POST` http methods.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/31038519/153467046-1cb2b4a1-f054-412f-802e-32f749509eb6.png">

It doesn't look like you can return a response in `onOriginRequest` either.

**Comment by AustinGil** [comment]
OK. I think you're right today, but as I understand it, some things are still in development. So if we want to circle back on this, should we leave this ticket open or close it and come back at a later time?

**Comment by andrewgadziksonos** [comment]
Ok I thought about this more last night, what about this approach?

- GET requests are handled via the `responseProvider` event.  This works out great if you want to cache results and utilize the CDN's cache.  One open question is how are static asset requests handled?  Do we need some sort of routing in `onClientRequest`?

- POST requests are handled via `onClientRequest` to process the request and use `request.respondWith(...)` and via `onClientResponse` to handle setting potential cookies.  POST requests typically dont rely on caching (is that accurate? 🤔)

**Comment by Marwansabbouh** [comment]
Hi Andrew
"One open question is how are static asset requests handled? Do we need some sort of routing in onClientRequest?"
I am not familiar with Remix, other than the quick introduction my colleague Austin gave me. 
With that said, since there is no origin behind Remix, you need to store the static content somewhere on the edge. 
The  Akamai solution for that is the Edge Key Value (EKV) store for data or Net Storage(NS) for things like images.
In this context, you can configure your Akamai property to retrieve directly from NS, without the need of any edgeworkers processing. 
An alternative Akamai solution for that is the Edge Key Value store for data. With this solution, you need to be mindful of the limit on the number of EKV calls allowed in a single RP invocation. Typically, Edgeworkers allows a maximum of 50.  EKV may impose additional [limitation](https://techdocs.akamai.com/edgekv/docs/limits).  The good news is once the fetch takes place, the static content can be cached.

**Comment by chaance** [comment]
We likely won't be adding new adapters directly to the Remix repo any time soon, but we welcome PRs for new examples!
