### ISSUE TITLE
[Bug]: Parent headers are not loaded if child does not set the headers

### ISSUE THREAD

**Issue by dg1234uk** [remix-run/remix#1552]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [X] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

17.3.0

### Steps to Reproduce

Set the following on a parent route:

```ts
export function headers() {
  return {
    test: "value"
  };
}
```

Then without any headers set on a child route. Go to the child route and note that the `test: "value"` header is not set.

### Expected Behavior

I have taken this from the docs: [Remix.run Docs - headers](https://remix.run/docs/en/v1/api/conventions#headers)

> Because Remix has nested routes, there's a battle of the headers to be won when nested routes match. In this case, the deepest route wins.

I'm not sure if my interoperation is correct but I believe it is intended that if there are no headers set on the child route/loader/action then it will use the parents (if set).

### Actual Behavior

For the `test: "value"` header to be set on all child routes unless they define their own headers, then it is up to those child routes to merge the parent headers if they require.

**Comment by dg1234uk** [comment]
#1553 is my attempt to resolve this

**Comment by dg1234uk** [comment]
Also the remix-cla-bot did not prompt me to sign the CLA as per the [Contributing to Remix](https://remix.run/docs/en/v1/pages/contributing#contributor-license-agreement) docs mention.

**Comment by jacob-ebey** [comment]
This is actually expected behavior. Headers within nested routes are not as simple as "just surface the parent's if I don't have my own".

Think of this case where your routes folder has this structure:

```
routes
  | - dashboard.tsx
  | - dashboard
    | - item.tsx
```

Visiting /dashboard/item will render the nested routes. If dashboard.tsx returns headers that say "cache me for 1 hour", but the item needs to *not* be cached at all, you have just shot yourself in the foot if parent headers surface automatically and have accidentally cached your item.tsx for 1 hour as well.

It's the job of the "leaf" route to aggregate and surface headers. This is why the parent headers are passed into the child routes headers function for aggregation.

**Comment by kiliman** [comment]
I think the main issue is that OP wanted to add a header for every request and was wondering why exporting headers in root didn't handle that.

He ended up adding the headers in entry.server and now it's working.

So yes, headers that are dependent on routes should be handled at the leaf route, but headers that are global should be added in entry.server.

**Comment by kiliman** [comment]
@dg1234uk Perhaps you can create a PR on the headers documentation to mention the entry.server solution.

**Comment by dg1234uk** [comment]
Thanks all, I will take a look at creating a PR on the docs.

**Comment by kentcdodds** [comment]
I've created a PR to add some docs about global headers. I think the existing docs address the original question pretty well. https://github.com/remix-run/remix/pull/1681

**Comment by na2hiro** [comment]
So there's no concept of "battle of headers", which is described here?

> Because Remix has nested routes, there's a battle of the headers to be won when nested routes match. In this case, the deepest route wins. Consider these files in the routes directory:
>
> (...abbreviated...)
>
> We don't want surprise headers in your responses, so it's your job to merge them if you'd like. Remix passes in the parentHeaders to your headers function. So users.tsx headers get passed to $userId.tsx, and then $userId.tsx headers are passed to profile.tsx headers.

https://remix.run/docs/en/v1/api/conventions#headers

If headers will never go to child routes, we should also remove that part in the doc.

I still think it's rather a bug, because `headers` of ancestor routes are actually called. (I confirmed by throwing error in ancestor's `headers`). @kentcdodds what do you think?

**Comment by na2hiro** [comment]
I did some archeology. It seems the change has intentionally made. The behavior has changed Feb 2021 by @mjackson d37c00508b671758c714b4c7672280d8e8de08ea

> ### Breaking Changes
> 
> - Leaf route determines headers on document requests instead of aggregating
>   headers from all routes
