### ISSUE TITLE
[Feature]: Explain when to pick Remix App Server instead of saying it is important?

### ISSUE THREAD

**Issue by ZeroPie** [remix-run/remix#1697]
### What is the new or updated feature that you are suggesting?

https://remix.run/docs/en/v1/tutorials/blog#creating-the-project
Says: It is important that you pick Remix App Server. Fine for me this gives the impression it will be an integrated Deployment like Vercel's.

Then we are pointed to the Readme (Suggestion: Maybe this could be in the page itself since it's small and concise)
https://remix.run/docs/en/v1/guides/deployment

So i notice theres no deployment on remix and i choose to deploy my repo on Vercel, but this doesn't work with the remix config.
![Screenshot 2022-01-28 at 12 05 37](https://user-images.githubusercontent.com/8741666/151598795-a1b0accc-9919-458e-b4d8-425fb418f513.png)

So we just end up just switching back from remix-app server to vercel, when we could have picked up Vercel right away.

### Why should this feature be included?

Save time for first users, get them to deploy their app straight away like next.js and Vercel do.

**Comment by ShafSpecs** [comment]
Remix server is to be chosen when you are not sure of your deployment service. In the tutorial, it was stated **important to choose Remix server** because the tutorial was just a short one allowing you to explore Remix. If you wanted a fully-fledged tutorial (which is always advised as the first remix tutorial you should do), the Jokes App is the way to go where you actually build an app and deploy it.

**Comment by ZeroPie** [comment]
@ShafSpecs okey) sounds reasonable to me.
