### ISSUE TITLE
[Feature] Add fb:app_id and fb:page_id to Meta component 

### ISSUE THREAD

**Issue by gixxerblade** [remix-run/remix#1717]
### What is the new or updated feature that you are suggesting?

Request add Facebook's open graph markup `fb:page_id` and `fb:app_id` to the Meta component.

### Why should this feature be included?

 When a link is shared to Facebook, the crawler indexes the fb:page_id and fb:app_id if they are present. According to a [Guide to Sharing for Webmasters](https://developers.facebook.com/docs/sharing/webmasters#markup) on Facebook's site, they recommend the use of `fb:app_id`

fb:app_id | In order to use Facebook Insights you must add the app ID to your page. Insights lets you view analytics for traffic to your site from Facebook. Find the app ID in your App Dashboard.
-- | --

**Comment by kiliman** [comment]
It doesn't look like there's consistency in how `<meta>` tags are used. The HTML standard is to use `<meta name="" content=""/>`. But apparently there's an RDFa standard that allows `<meta property="" content=""/>`.

The `og:*` meta properties, use the `property` attribute, same with `fb:*`. I thought that a good heuristic would be to look for `:` in the property name and if present use `property`, otherwise use `name`. Unfortunately that doesn't work, as `twitter:*` meta tags use `name`. 😮‍💨

Currently the Remix `<Meta>` component is hard-coded to check for `og:` prefix. Every time a new meta property came out, they would need to update this.

It may be better to allow you to specify this in the `meta` export.

```ts
export function meta() {
  return {
    title: 'My title',
    description: 'My description',
    'og:image': 'path/to/image',    // keep for backward compatibility
    'fb:app_id': { property: 'fb:app_id', content: '1234' },  // use object for non-name version
    '@fb:page_id': 'page-id',       // or use a prefix like @ to denote this is 'property'
  }
}
```

**Comment by Ethaan** [comment]
So i guess for now this is what we need to do right?

```
<head>
  <meta charSet="utf8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta property="fb:app_id" content="xxxx" />
  <Meta />
  <Links />
</head>
```

**Comment by kiliman** [comment]
Yes, for now you would need to manually render those <meta> elements yourself.

**Comment by 14850842** [comment]
This however does not allow you to specify dynamic values such as your deep link:

```
 <meta property="al:ios:url" content="example://applinks/:id" />
 ```

**Comment by machour** [comment]
@14850842 a PR which should allow that to work was recently merged:
   https://github.com/remix-run/remix/pull/4610

The feature will be available in next release.

**Comment by susanwinters214** [comment]
Do we need to have BOTH the fb:app_id AND the fb:page_id? Or will that confuse the bots?
