### ISSUE TITLE
[Feature]: How to login via google?

### ISSUE THREAD

**Issue by zwl1619** [remix-run/remix#1809]
### What is the new or updated feature that you are suggesting?

Is there a tutorial for login via google account?

### Why should this feature be included?

Is there a tutorial for login via google account?

**Comment by yomeshgupta** [comment]
@zwl1619 May be this might help you

https://devtools.tech/blog/add-social-authentication-functionality-to-a-remix-run-project---rid---jVwo6agJvN2oX4IegYgz

**Comment by sergiodxa** [comment]
Because that tutorial uses Passport.js it will only work if you use the Express adapter, if you use Remix App Server where you can't control the server code or use any other adapter like Vercel, Netlify, or even Cloudflare then you can't use Passport.js.

---

@zwl1619 you can use [Remix Auth](https://github.com/sergiodxa/remix-auth) to add authentication for your app independent of the adapter you use.

And there's a [GoogleStrategy](https://github.com/pbteja1998/remix-auth-google) that you can use, you could also get the strategy from [remix-auth-socials](https://github.com/TheRealFlyingCoder/remix-auth-socials) which bundle many social strategies including Google.

And if, for some reason, you don't want to use any of those packages you can use the [OAuth2Strategy](https://github.com/sergiodxa/remix-auth-oauth2) and configure it to work with Google, those packages above do that.
