### ISSUE TITLE
[Feature]: Allow dev server to listen on localhost

### ISSUE THREAD

**Issue by RazerM** [remix-run/remix#1831]
### What is the new or updated feature that you are suggesting?

I want to be able to have the dev server listen on localhost. I think https://github.com/remix-run/remix/pull/1328 should be reconsidered (e.g. by making it configurable).

### Why should this feature be included?

I don't want my development app to be available on the whole network. It seems a bit of an unusual default compared to other web frameworks I'm familiar with — Django and Flask's dev servers both listen on 127.0.0.1, and I assume it's similar for most others. Typically I'd only change this for demo purposes, but in any case I doubt any default suits everyone so an environment variable or CLI option would be ideal.

**Comment by kiliman** [comment]
They don't include the reason for this change, so I'm assuming it's to handle something internal. Probably due to testing?

Anyway, if you need more control over things, then I would switch to the Express adapter instead of using Remix App Server. This will allow you to configure the server however you want. *NOTE: RAS uses Express under the hood.*

**Comment by nmaves** [comment]
I agree the change in [#132](https://github.com/remix-run/remix/pull/1328) should be reconsidered.  It causes secure cookies to fail for local development.

**Comment by nmaves** [comment]
Maybe we could have the best of both worlds and display something like this....

  Local:            http://localhost:3000
  On Your Network:  http://192.168.1.87:3000

**Comment by kettanaito** [comment]
The change to always use local IP is disruptive. Most of the dev tools and integrations will rely on `localhost`, which is fixed, while local IP is variable. For example, I cannot work with an OAuth in my app because its callback is set to `localhost:300/auth`, so I end up using `localhost` anyway. 

👍 to making this configurable. How to establish the dev server is the developer's decision.

**Comment by mcansh** [comment]
I'm not opposed either way, but just letting you know that the server is still accessible via localhost, we just log the local ip address

**Comment by mcansh** [comment]
opened #2301, thanks for patience every one :pray:

**Comment by MichaelDeBoey** [comment]
Since #2301 is merged, I think this one can be closed now?

**Comment by mcansh** [comment]
> Since #2301 is merged, I think this one can be closed now?

yup thanks!

**Comment by RazerM** [comment]
@mcansh that PR does not address the issue, which is about which IP address remix _listens on_. I'm aware that I can access remix via localhost when it is listening on the IP address of my machine. I think the description is clear (?)

I want to be able to listen only on localhost. In case you're not familiar with how that works, that means that if I tell remix to listen on 127.0.0.1 I should not be able to go to another machine on the same network and access the remix dev server.
