### ISSUE TITLE
[Bug]: Error on the getting-started-tutorial for post route

### ISSUE THREAD

**Issue by erickmaminiaina** [remix-run/remix#1870]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

@latest

### What version of Node are you using? Minimum supported version is 14.

16.13.2

### Steps to Reproduce

I just began to use remix for my internship. So, I began to get started with remix following the Quickstart tutorial.
I followed all the steps as described on the tutorial.
Arrived at the "Your First Route" part, I found a problem with the script : while adding my first route, as requested on the tutorial step, I wrote the following line : 
`<Link to="/posts">Posts</Link>`

### Expected Behavior

This line, if I understand it, permits to link the `post view` to the `root`. This should permit to inject the list of posts on the view.

### Actual Behavior

The view doesn't show the list of posts, and the terminal doesn't seem to display errors. 

[FIXED] I fixed the problem by removing the '/' on the route, so instead of
`<Link to="/posts">Posts</Link>`, I corrected it to be `<Link to="posts">Posts</Link>`

I opened this issue in order to fix the error on the [Quickstart page](https://remix.run/docs/en/v1/tutorials/blog)

**Comment by ftonato** [comment]
Hello @erickmaminiaina, thank you for opening this issue.

----

⚠️ tl;dr for maintainers: **false positive bug**.

----

I read what you wrote above and in the **expected behavior** part you mention:

> This line, if I understand it, permits to link the post view to the root. This should permit to inject the list of posts on the view.

What you understood, as you wrote, is that adding the code `<Link to="/posts">Posts</Link>` would allow us **to inject the list of posts on the view (as you wrote)**, but that's not what the documentation says, let's see the image below:

<img width="600" alt="Screenshot 2022-02-27 at 16 49 23" src="https://user-images.githubusercontent.com/5417662/155891503-1538cd94-b37e-493c-af61-5c4708c3b89a.png">

The first line mentions just that:

> We're going to make a new route to render at the "/posts" URL.

Which means that we are going to create a link in our current view, which will redirect us to another `/posts` route where (further down in the tutorial, see the screenshot above) will redirect us to a **404 error page**.

> Back in the browser go ahead and click the link. You should see a 404 page since we've not created this route yet. Let's create the route now:

Until finally, we follow the rest of the tutorial and the page that so far gives us an error, will eventually return the _posts_.

Perhaps you got it wrong at some point, but the documentation is correct. I followed it to validate and everything worked correctly, so don't worry, just try again and everything will be fine 🚀 🙃
