### ISSUE TITLE
Add a changelog page to the dashboard/docs

### ISSUE THREAD

**Issue by Vivalldi** [remix-run/remix#19]
### Proposal
Add a changelog page within the documentation to allow users to view updates within the dashboard. 

### Workaround
Currently, release information is being added to the #releases channel in discord.

**Suggested Tags**: `enhancement` | `remix.run`

**Comment by IanVS** [comment]
Is there a changelog somewhere?  I don't see a `CHANGELOG.md` file, the `Releases` tab of github is kind of worthless since it is full of releases like `v0.0.0-experimental-149e932f`, and searching for `changelog` on the docs site does not return any results.  Is there somewhere else that I'm missing?  How can we keep track of the changes being made in this project?  Thanks!

**Comment by machour** [comment]
Releases are now tracked via Github Releases.
