### ISSUE TITLE
Firebase functions & Express - Empty request body

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#211]
### Issue
Action Request body is empty after making the journey through Firebase `https.onRequest()` -> Express -> `createRequestHandler()`

### Notes
Express request object has the body before `createRequestHandler` as you can successfully pass it in the Context object

### Replication
I've created a little solution that replicates the problem as simply as possible.

The button posts a hidden field value to the action, if the value exists in the body it redirects to "hasToken" otherwise "noToken"

There are 3 tests which simply change the server configuration:

1. Remix run -> Should work successfully
2. Express -> Should work successfully
3. Firebase Emulator -> Should fail

It needs the Firebase Emulator suite to do the failing test unfortunately, but it's not too big a hassle to install.

[ExpressTest.zip](https://github.com/remix-run/remix/files/6722575/ExpressTest.zip)

**Comment by ccssmnn** [comment]
I was running into this when I tried to prepare a Remix + Firebase example. In the Cloud Function [docs](https://firebase.google.com/docs/functions/http-events#read_values_from_the_request), they say, that request bodies are parsed before the request is processed by the Cloud Function handler. That's why it works with Remix run and standalone Express, but not in the emulator.

As answered [here](https://stackoverflow.com/questions/70992856/disable-undo-firebase-cloud-functions-default-request-parsing), there is no way to disable this behavior.

**Comment by gustavopch** [comment]
For anyone having this issue, you can make it work with this patch:
```diff
diff --git a/node_modules/@remix-run/express/dist/server.js b/node_modules/@remix-run/express/dist/server.js
index 4ea186f..2c63e13 100644
--- a/node_modules/@remix-run/express/dist/server.js
+++ b/node_modules/@remix-run/express/dist/server.js
@@ -74,7 +74,7 @@ function createRemixRequest(req, res) {
     signal: controller.signal
   };
   if (req.method !== "GET" && req.method !== "HEAD") {
-    init.body = req;
+    init.body = req.rawBody ?? req;
   }
   return new node.Request(url.href, init);
 }
```
