### ISSUE TITLE
Route Chunk loaded although redirect is thrown

### ISSUE THREAD

**Issue by roydigerhund** [remix-run/remix#2235]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

1. Create a route with a loader that throws a redirect. To demonstrate the behavior, I'll directly throw the redirect but the use case would be for example a protected route only for authenticated users.

```js
export const loader = () => {
  throw redirect("/");
};
```

2. Link to this route with `Link`

```js
<Link to={"/protected"}>Go to Protected Site</Link>
```

3. Click on the link and check the network requests, the chunk of the route containing the code for rendering the default export got loaded.

If you directly access the protected site or link to it with an `<a>` tag, this chunk will not be loaded.

### Expected Behavior

Code to execute render function shouldn't be fetched if the loader throws a redirect or an error.

### Actual Behavior

Chunk of protected routes are fetched and might contain sensitive data.

**Comment by machour** [comment]
Described problem is still reproducible in 1.11.0

**Comment by brophdawg11** [comment]
This is expected since Remix runs your loader and fetches the route chunk in parallel for optimal performance.  If Remix waited to confirm the loader didn't redirect before loading the route chunk it would introduce a waterfall slowing down every route transition.

You should not have sensitive _data_ in your protected route chunks.  Those are probably readily accessible anywhere in the world from your CDN.  All of your data should come from loaders and those should only ever run and return sensitive data after you've authenticated+authorized the user.

The [middleware](https://github.com/remix-run/react-router/discussions/9564) proposal is relevant to any discussion on protected routes and depending on implementation design I could see a world in which that doesn't load chunks if the middleware redirects.
