### ISSUE TITLE
Add common props to route components

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#227]
There are a handful of values that we could pass to route components to simplify application code and application testing.

Right now we pass nothing:

```ts
export type RouteComponent = ComponentType<{}>;
```

I'm thinking we start small:

```ts
export type RouteComponent = ComponentType<{
  loaderData: AppData;
  actionData: AppData;
}>;
```

- This simplifies the majority of route components by not requiring an import of `useLoaderData` or `useActionData`
- This simplifies unit testing route components by allowing tests to simply pass in values for data instead of stubbing out Remix context (though this isn't a big motivating factor for me, it's really easy to have a route component do nothing more than `return <RouteView data={useRouteData()} />` and get the same effect)

The hooks will continue to do exactly what they do so that it's easy to create abstractions around them (like other hooks, or to get data deeper in the tree w/o having to drill the prop down).

---

Heck, we could very well pass all of this stuff in if we wanted to:

```ts
export type RouteComponent = ComponentType<{
  loaderData: AppData;
  actionData: AppData;
  location: Location<any>;
  params: RouteParams;
  pendingLocation?: Location<any>;
  pendingParams?: RouteParams;
  submission?: GenericSubmission;
}>;
```

**Comment by luchsamapparat** [comment]
This was my first thought when I started reading about Remix: Why use hooks if you can pass loader data as props...? Great that you were already thinking about that.

**Comment by jacob-ebey** [comment]
I'm actually against this change for a few reasons:

1. Testing becomes harder with typescript. You'll either be forced to mock out all props to satisfy the interface or cast to "any". What do I mock per component without diving into the implementation? With hooks, just look at the imports and `jest.mock` the hooks. No context mocking needed.
2. It introduces "magic" in each route. Where do these props come from? How can I replace these props in the future with another implementation? It sacrifices extensibility for class component support and I think that's wrong.
3. It makes typing components harder. Instead of a generic function, I now have to export an arrow function with a type that might look like this:
    ```ts
    const Component: RouteComponent<LoaderData, ActionData> = () => { return null; };
    export default Component;
    ```
    This leads to additional issues in what do you do if you don't have a loader and only an action? How do you type this that doesn't look ugly?:
    ```ts
    const Component: RouteComponent<never, ActionData> = () => { return null; };
    export default Component;
    ```

I'll just leave you with this:
```ts
const Component: RouteComponent<LoaderData, ActionData> = ({ actionData, loaderData }) => {
  return <h1>Hello, World!</h1>;
};
export default Component;
```
vs
```ts
export default function Component() {
  const actionData = useActionData<LoaderData>();
  const loaderData = useLoaderData<LoaderData>();

  return <h1>Hello, World!</h1>
}
```

**Comment by luchsamapparat** [comment]
@chaance does closing this issue mean that you decided against implementing this?
