### ISSUE TITLE
How to set multiple `Set-Cookie` headers in a single response?

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#231]
I tried copying `concatSetCookieHeaders` from remix but that... eh, doesn't work... Doing that I end up with a single set-cookie header.

Here's the relevant code: 

```ts
const sessionIdCookie = await getUserSessionCookieFromMagicLink(request)
if (sessionIdCookie) {
  const destroyCookie = await loginInfoSession.destroy()
  return redirect('/me', {
    headers: {
      'Set-Cookie': concatSetCookieHeaders(destroyCookie, sessionIdCookie),
    },
  })
}
```

What I need is two `Set-Cookie` headers, and this gives me a single `Set-Cookie` header that doesn't end up updating either one.

If I use either of these cookie values by itself then they each work as expected. But I need to set them both in the same response.

**Comment by shripadk** [comment]
This doesn't seem to be working when you have a parent loader and nested loader both trying to `Set-Cookie`. Since according to Remix docs, the nested loader headers override the parent loader headers, it can only be merged in the `headers` function that is exported. However, there is no way to merge both `Set-Cookie` headers in there either as the result expected by the function is a Javascript object or instance of `Headers` Fetch API.

How do I handle this situation? Or am I missing something?

**Comment by shripadk** [comment]
@kiliman Wasn't sure if this is a bug or a discussion so I posted both. A discussion in Discord as well as a report here. But I am now inclined to think this is definitely a bug.

Tested it out in the root loader (the Response headers contains only 1 `Set-Cookie` that is concatenating all values instead of setting a `Set-Cookie` for each cookie):

<img width="440" alt="image" src="https://user-images.githubusercontent.com/189344/185213886-9f6403af-b350-45d3-b097-95ae080f0cd6.png">

Network tab:

<img width="937" alt="image" src="https://user-images.githubusercontent.com/189344/185214185-cf1ce502-86fa-4c7a-8c7a-c39618b2fcfb.png">

**Comment by shripadk** [comment]
@kiliman  Interestingly it only works with `redirect`. This only tells me that this is definitely a bug as the user of the framework would expect same consistent behavior with respect to headers in both situations (when using `json` and when using `redirect`) as well as within the exported `header` function. I feel this issue should be re-opened as it only tackles one use case. You can see the behavior of `redirect` (which is the right behavior) and contrast it with behavior of `json` above:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/189344/185218013-4d6d04b4-b7d2-4b8a-91dc-a2679603440b.png">

Network tab:

<img width="942" alt="image" src="https://user-images.githubusercontent.com/189344/185218069-4fd0ad55-f4e7-4c4f-b802-166f798f614f.png">

**Comment by martinmckenna** [comment]
this still seems to be an issue in the `action`. I currently have this action in a route:

```ts
import type { ActionArgs } from "@remix-run/node";
import { createCookie, json } from "@remix-run/node";

import { AUTH_COOKIE, AUTH_EXP_COOKIE } from "app/cookies"

export const setCookie = (key: string, value: any) => {
  const createdCookie = createCookie(key, {
    path: "/",
    sameSite: "lax",
  });
  return createdCookie.serialize(value);
};

export async function action({ request }: ActionArgs) {
  return json(
    {},
    {
      headers: {
        "Set-Cookie": await setCookie(AUTH_COOKIE, ""),
        // @ts-expect-error
        "Set-Cookie": await setCookie(AUTH_EXP_COOKIE, ""),
      },
    }
  );
}
```

and here are my response headers:

![Screen Shot 2023-09-04 at 4 09 56 PM](https://github.com/remix-run/remix/assets/7387001/67cf9825-0239-4352-967f-9dea349904c0)

**Comment by wenzf** [comment]
This way it seems to work

```js
   return json(
            { success: true },
            {
                headers: [
                    ["Set-Cookie", await destroyFirstSession(firstSession)],
                    ["Set-Cookie", await commitSecondSession(secondSession)]

                ]
            }
        )
```

**Comment by alfredsgenkins** [comment]
I tried both `cookie.append` and setting array of cookie entries and it appears nothing works in production. Weirdly on local it's all good. But in production it breaks. Is there any caveat I need to avoid when declaring cookies? Or maybe the problem is actually in ION-SST Remix plugin.

Cookies:

```typescript
const idTokenCookie = createCookie("id_token", {
  path: "/",
  httpOnly: true,
  secrets: [process.env.COOKIE_SECRET],
  secure: process.env.NODE_ENV === "production",
});

const refreshTokenCookie = createCookie("refresh_token", {
  path: "/",
  httpOnly: true,
  secrets: [process.env.COOKIE_SECRET],
  secure: process.env.NODE_ENV === "production",
});
```

And nor this:

```typescript
class {
  async getLogoutHeaders() {
    return [
      ["Set-Cookie", await idTokenCookie.serialize("", { maxAge: 0 })],
      ["Set-Cookie", await refreshTokenCookie.serialize("", { maxAge: 0 })],
    ];
  }
}
```

And nor this:

```typescript
class {
  async getLogoutHeaders() {
    const headers = new Headers();

    headers.append(
      "Set-Cookie",
      await idTokenCookie.serialize("", { maxAge: 0 })
    );

    headers.append(
      "Set-Cookie",
      await refreshTokenCookie.serialize("", { maxAge: 0 })
    );

    return headers;
  }
}
```

**Comment by alfredsgenkins** [comment]
A temporary solution from my side was to merge cookies:

```typescript
class {
  async getLogoutHeaders() {
    const headers = new Headers();

    headers.append(
      "Set-Cookie",
      await idTokenCookie.serialize("", { maxAge: 0 })
    );

    headers.append(
      "Set-Cookie",
      await refreshTokenCookie.serialize("", { maxAge: 0 })
    );

    return new Headers([["Set-Cookie", headers.get("Set-Cookie") || ""]]);
  }
}
```

Yet, I do not think the solution is great.

**Comment by wenzf** [comment]
> A temporary solution from my side was to merge cookies:
> Yet, I do not think the solution is great.

I haven't found a stable solution for this issue which works in production mode yet. I don't fully understand why, my best guess is that is because of race conditions.

My case: I tried to delete a cookie1 and create a new cookie2 in the same header. My workaround was to delete cookie1 on one route, redirect to another route where cookie2 is added and redirect again to the final target route. That worked for me, but your workaround seems more elegant than mine.

**Comment by alfredsgenkins** [comment]
@wenzf have you tried combining them, as I did? I also noticed that despite being combined, on local it still sends cookies separately, and in production it does indeed split them apart. Seems like it could indeed be the difference in server implementation, I am using `remix vite:dev` in development and SST ion in production.

**Comment by wenzf** [comment]
@alfredsgenkins I haven't tried your solution combining the cookies yet, but I'll give it a try for sure in future!

I'm using `arc` with classic compiler. Seeing the same issue with different deployment pipelines doesn't indicate that different server implementations is the cause of this.

SST looks very interesting btw., I need to have a closer look at that. Would be great having an alternative to `arc`.

**Comment by enure** [comment]
@alfredsgenkins this might be related: https://github.com/sst/ion/pull/702

**Comment by wenzf** [comment]
@alfredsgenkins check out this https://github.com/epicweb-dev/epic-stack/blob/main/app/utils/misc.tsx#L90
