### ISSUE TITLE
LiveReload rendering nothing on server but a component on client

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#2485]
### What version of Remix are you using?

1.3.3

### Steps to Reproduce

We discovered this in the indie stack, I fixed it by adding `cross-env NODE_ENV=development` to the `remix dev` command, but you can quickly reproduce this by initializing the indie stack with the commit before my fix:

```
npx create-remix@latest --template=https://github.com/remix-run/indie-stack/tree/d725c62dfde7241397e5b74863e432d3e9a8dff2 live-reload-bug
# install deps
cd ./live-reload-bug
npm run dev
```

Open the app and you'll see the error:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/1500684/159996656-e842394d-e917-4afc-bb00-3483618f7d51.png">

### Expected Behavior

We expect that during development the LiveReload will render the script necessary to hook up live reload on both the server and the client.

### Actual Behavior

It renders nothing on the server and the script on the client. So it "works" but you get the warning.

The way the `LiveReload` works is it is set to an empty function that returns null when the `NODE_ENV` is not `development`. In `development` it's set the the full component that renders the script tag for live reload.

You can add a `console.log(process.env.NODE_ENV)` to the `root.tsx` and you'll notice it logs `development` in both the server and the client. However, if you add `console.log(process.env.NODE_ENV)` to `./node_modules/@remix-run/react/components.js` you'll see it's `undefined`.

So while it appears we do set the `NODE_ENV` to development before the app code is loaded, we don't do that before our own code is loaded.

I realize that we don't want node-isms (like `process.env.NODE_ENV`) in our packages, but the fact is that we already have it and if we want to remove it then that's going to be a breaking change so we need to figure out how to make this work. I think we just need to take whatever code is setting the environment variables and move it to happen earlier in the process before other files are imported. Maybe?

**Comment by ostwilkens** [comment]
I'm just starting out and I'm stuck on this. 
What can I do about this in my own stack? https://github.com/ostwilkens/remix-minimal-stack
Setting `NODE_ENV=development` doesn't seem to work for me.

**Comment by kentcdodds** [comment]
We're going to need a reproduction on this. Your issue is probably different from what mine was at the time I opened this issue. We've changed LiveReload quite a bit since this issue was made. Could you please make reproduction steps (and preferably a failing integration test) for us? https://github.com/remix-run/remix/blob/main/docs/pages/contributing.md#think-you-found-a-bug

Thanks!

**Comment by abdulkader** [comment]
Hello @kentcdodds @ryanflorence 
With a clean install of the Remix Basic App, I can reproduce the error. Also, no other changes/libraries were added, and when running development mode, I get an attached error, and when running production build as well, getting an error. Not sure if it will impact any production build if we don't know the root cause.

Steps:
1. Run `npx create-remix@latest myremix-app` and choose below options from the promps
```
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change
deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```

2. When you run dev or start after build, you will get these 2 errors.


1. On Development Mode

![Screenshot 2023-01-22 at 2 10 58 PM](https://user-images.githubusercontent.com/4932290/213910525-fc610f76-7801-4446-8c92-c78fdbd3eed6.png)

2. On Production Mode

![Screenshot 2023-01-22 at 2 11 24 PM](https://user-images.githubusercontent.com/4932290/213910535-c54051fe-829f-4b98-958a-a4f0ea55aaef.png)

**Comment by machour** [comment]
@abdulkader @Mihai-github  Please open new issue and provide a repository reproducing the problem 🙏🏼
