### ISSUE TITLE
Remix cli seems to be broken

### ISSUE THREAD

**Issue by arpitdalal** [remix-run/remix#2685]
### What version of Remix are you using?

latest

### Steps to Reproduce

run `npx create-remix@latest remix-app` and select the following
```bash
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? No
```
and it will not even create a simple app and gives me these files/folders:
![image](https://user-images.githubusercontent.com/61059807/162246128-815458d5-2fc4-48a2-aafb-535f49d75170.png)

Here's the whole folder zipped : https://drive.google.com/file/d/1cojG8UUK-qrP0mOCnb3I_cLBDWcBAAFN/view?usp=sharing
I am using npx v7.21.1

### Expected Behavior

The options selected in the cli should give me a remix-server app

### Actual Behavior

The cli doesn't even give an app

**Comment by MichaelDeBoey** [comment]
Are you installing it next to a fork of the `remix` repo?

**Comment by arpitdalal** [comment]
yeah

**Comment by kiliman** [comment]
@arpitdalal 
> Creating the app somewhere else fixed the problem, but I don't understand why does it matter 🤷‍♂️

Remix uses heuristics to determine where to pull the template from: from GitHub, file system, etc.

If the CLI finds a local folder with the name of the template, it will use that. Otherwise it looks on GitHub.

I believe the issue is that if the template is named "remix" (which is what the Remix App Server uses), it accidentally finds a local folder named "remix" and simply copies that into your new project instead of fetching from GitHub.

They should probably rename the default templates to something more unique.

**Comment by arpitdalal** [comment]
ohh... okay makes sense, thanks @kiliman for the explanation!
