### ISSUE TITLE
Submit form return error

### ISSUE THREAD

**Issue by ZetraDev** [remix-run/remix#2726]
### What version of Remix are you using?

1.3.3

### Steps to Reproduce

create a form component and submit it

### Expected Behavior

no error

### Actual Behavior

it return 405 error with "405 Method Not Allowed"

**Comment by machour** [comment]
This error is displayed when you post to a route that doesn't define an action. 
Did you define an `action` on your route?

**Comment by ZetraDev** [comment]
I defined the action in my route

**Comment by ZetraDev** [comment]
here's my code:
```tsx
// root.tsx
export default function App() {
	const data = useLoaderData();
	return (
		<Document>
			{
				data.user ? <Outlet /> : <Form />
			}
		</Document>
	);
}
export const action: ActionFunction = async ({
	request,
}) => {
	return json({})
};
```

**Comment by alekpentchev** [comment]
> here's my code:
> 
> ```tsx
> // root.tsx
> export default function App() {
> 	const data = useLoaderData();
> 	return (
> 		<Document>
> 			{
> 				data.user ? <Outlet /> : <Form />
> 			}
> 		</Document>
> 	);
> }
> export const action: ActionFunction = async ({
> 	request,
> }) => {
> 	return json({})
> };
> ```

What about the `<Form />` component? Could you please share its code? 
Here you used `useLoaderData()` but you don't have the `loader()` function. Instead you're defining `action()` that doesn't do anything.
Typically you'd have the `action()` function on the same level as the component with a form, probably in `<Form />`. But without seeing its code it's hard to tell whether there's an issue in your code or in Remix.

**Comment by ZetraDev** [comment]
Sorry for making you confusing with my code, here is full code:
```tsx
// root.tsx
export const loader: Loader: LoaderFunction = async({request}) => {
	return {user: await getUser(request)}
}
export default function App() {
	const data = useLoaderData();
	return (
		<Document>
			{
				data.user ? <Outlet /> : <Form />
			}
		</Document>
	);
}
export const action: ActionFunction = async ({
	request,
}) => {
	return json({})
};


// /component/LoginForm.tsx
export function Form() {
	return (
		<form method="post">
			<input name="test" />
			<button type="submit">test</button>
		</form>
	)
}
```

**Comment by ZetraDev** [comment]
So i just read the docs again and i see that it was using Form element from remix instead of normal <form> element, i tried it and the form submitted successfully, so i think the problem solved, sorry for wasting your time

**Comment by alekpentchev** [comment]
No problem, good to hear that you've managed to solve your problem :)

**Comment by jimniels** [comment]
For anyone who comes here from Google:

I was using `<form action="/" method="post">` and kept getting a 405, even though I had an action on my route.

I realized it was because I was on an _index route_ which requires [the `?index` parameter](https://remix.run/docs/en/v1/guides/routing#what-is-the-index-query-param).

In a case like this, there are two ways to resolve this issue:

1. Add `?index` to the form's action URL, e.g.

```
<form action="/?index" method="post">…</form>
```

2. Upgrade the `<form>` element to Remix's `<Form>` element (which will add the query param for you automatically)

```
import { Form } from "@remix-run/react";

<Form reloadDocument method="post">…</Form>
```

In my case, I wanted the browser to [handle the submit functionality](https://remix.run/docs/en/v1/guides/data-writes#graduate-to-form-and-add-pending-ui) so I added the `reloadDocument` which basically results in the same thing as writing the `<form action="/?index" method="post">`
