### ISSUE TITLE
Browser Environment Variables showing in network tab

### ISSUE THREAD

**Issue by Maks19** [remix-run/remix#3271]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

1. Add Browser Environment Variables according to the https://remix.run/docs/en/v1/guides/envvars#browser-environment-variables
2. Redirect to any route
3. Check your secrets in network tab

![image](https://user-images.githubusercontent.com/41080668/169558847-aa94c376-f1f9-4415-9ddb-4aef58564381.png)

Following the documentation the best way to add env variables is to add them on your server **but** how to processed _secret_ url that should be in root component (e.g. Google Api script)?

### Expected Behavior

Environment Variables are hidden

### Actual Behavior

Environment Variables are shown

**Comment by kiliman** [comment]
If you're following the guide, the loader should only be returning public variables that can be viewed on the client. Do not return secret keys, but simply use them on the server via `process.env.MY_SECRET_KEY`.

Also, make sure you only use these keys in the loader or action. Otherwise, you should move that code to a `*.server` file to ensure it is only included in the server bundle.

**Comment by machour** [comment]
Isn't the Google Maps Api key supposed to be public? (It needs to make it to the browser to be appended to the maps script).

Closing this issue as I don't think there's a problem here, feel free to ask for this issue to be opened again if there's an oversight on my part 🙏
