### ISSUE TITLE
Cookies with `secrets` should be encrypted.

### ISSUE THREAD

**Issue by fern64** [remix-run/remix#336]
Currently cookies with `secrets` are only signed, which can lead to security vulnerabilities as it's easy to see what's inside the cookie. Providing `secrets` implies that the cookie is encrypted, so I would like to ask for either a docs update to clarify this or a change to cookies such that they are encrypted when providing `secrets`.

**Comment by jasonk** [comment]
Encrypted cookies means either that none of the data in the cookie can be used in the browser, or that the information necessary to decrypt the cookie must also be available in the browser for the browser to decrypt it, which means your secrets aren't actually secret.

The most common use for cookies is to hold something like a session ID, or a user ID.  If the values stored in the cookie are intended to be secret then you might want to encrypt the cookies, but if it's just something like a Session ID then you don't really gain anything by encrypting it, because there is nothing useful that someone can do with the cookie.

The warning in Django isn't really relevant, it's warning you about two things: 1. that someone who obtains your secret key can use it to create valid cookies that include any content they want (which should be obvious, that's why they are called "secrets") and 2. that if you ware using the "PickleSerializer" that the cookie data can include an executable payload (that anyone would choose to use a serializer that could include executable code is the real WTF in that warning).

It's also worth nothing that the Django warning clearly says that their cookies are also signed but not encrypted.

It might be worthwhile to add an option to encrypt cookies, but I'd argue that if you are storing information in cookies that is sensitive enough to need encryption, then it makes just as much sense for you to encrypt it before putting it into the cookie, because for everybody else there is no security risk from having the cookies signed but not encrypted and nothing to gain by encrypting them.

**Comment by machour** [comment]
Converting this to a Proposal discussion, as per our [Development Process](https://remix.run/docs/en/v1/pages/contributing#development-process).
