### ISSUE TITLE
HMR

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#34]
We thought we wanted it in the beginning, but we're not sure now. With the full-stack nature of Remix it's quite nice to have the full page reload so you don't break your app in production.

For example, if you do this:

```js
let [state, setState] = useState(0)
```

Fire up your app, start working and then change it to this:

```js
let [state, setState] = useState(localStorage.foo)
```

With HMR, your app continues to work just fine. If you don't hit "refresh" and try to server render that code, you'll never know you broke your app.

Our current live reload approach ensures that every change runs through a full server render pass so you don't end up with those kinds of surprises.

Additionally, when you're changing loader code, HMR won't update the UI, live reload does.

Finally, usually HMR is more about hiding the slowness of front-end build tools than about maintaining client state on code changes. ESBuild is fast, so it doesn't matter.

All that said, we've got some experimental stuff working from a while back, but it's really not high priority right now because there are some tradeoffs to consider, it's not just an obvious thing to add. Also the live reload experience right now is so good that some people think we already have HMR 🤫

This issue is here, and left open, because we haven't decided to do HMR, but we haven't decided not to either.

**Comment by ycjcl868** [comment]
same issue, lack of [react-refresh](https://github.com/facebook/react/issues/16604#issuecomment-528663101) support.

**Comment by alexturpin** [comment]
Just wanted to chime in for team HMR a bit! I understand Remix's goals with SSR first, and I also agree that with Edge computing, it's likely where everything is headed. However, I assume there are many others like me who are building apps with significant client-side state and interaction in order to create really rich UX. One example of such an app would be an online collaborative editor, something like Figma or Miro.

It would be awesome to have some fast refresh capabilities to make building that kind of apps on Remix an even nicer experience. On my current project, I even use the [Vite HMR API](https://vitejs.dev/guide/api-hmr.html) to enhance the development experience according to our business requirements.

**Comment by itsMapleLeaf** [comment]
I've worked on a handful of "app-like apps" using Remix lately, and this is still near the top of my wish list.

Although ESBuild runs are fast, in my opinion, maintaining state between changes is a really underrated capability. It helps in cases like editing a popover state while it's open, editing a menu item while it's open, toggles, and so on. The failure case as described in the OP is a valid one for sure. But I don't know if guarding against that is worth sidestepping a potentially huge boost in DX.

**Comment by leon** [comment]
My story is I want to use remix as the framework for a react-three-fiber app.

I really like remix, but compared to using vite and their react plugin I get real time updates both to css and 3d code which is a must have once you have tried it.

Could we tell remix which folders to do fast refresh on?

that way we could get fast refresh on ui components and in my case the react-three-fiber app, but still have full reloads when changing loaders or route adjacent modules.
