### ISSUE TITLE
`@remix-run/server-runtime` drops Cloudflare Workers Service Bindings special field: `request.cf`

### ISSUE THREAD

**Issue by tulup-conner** [remix-run/remix#3640]
### What version of Remix are you using?

1.6.3

### Steps to Reproduce

1. Create a new project with `npx create-remix` on `Cloudflare Workers`, or in my case, fork https://github.com/jacob-ebey/remix-cloudflare-worker-template
2. Create another Cloudflare Worker that does something (let's call it `another-worker`)
3. Add a [Service Binding]() to the Remix app so we can call `another-worker` without going over the Internet (let's call it `ANOTHER_WORKER`)
4. Attempt to call `another-worker` using the binding from a Remix loader or action

```js
const loader = function ({ context, request }) {
  const anotherWorker = await context.env.ANOTHER_WORKER.fetch("https://.../");
  const anotherResponse = await anotherWorker.json();
}
```

### Expected Behavior

The bound worker should execute, and produce whatever result it is designed to. I should be able to read that result from 

```js
await anotherWorker.json()
```

### Actual Behavior

The worker fails, producing the following response in the Cloudflare Workers dashboard:

```json
"exceptions": [
  {
    "name": "Error",
    "message": "The script will never generate a response.",
  }
],
```

Cloudflare Workers appears to rely on a custom property in `Request`s/`Response`s called `cf`, which contains a volume of metadata. Without it, requests to Service Bindings produce this unhelpful error message. Add the `cf`, and it works.

How, exactly? Well, on older versions of `@remix-run/server-runtime`, the entire `Request` object is cloned when passed to actions/loaders, so I was able to just do this:

```js
const loader = function ({ context, request }) {
  const anotherWorker = await context.env.ANOTHER_WORKER.fetch(new Request("https://.../", { cf: request.cf });
  const anotherResponse = await anotherWorker.json();
}
```
I believe [this commit](https://github.com/remix-run/remix/commit/8bdd2f8cc085118967061a425f32c7dcc3ad7a00) changed that behavior.

I was able to create a patch with `patch-package` where I simply added the following line to additionally pass the Cloudflare metadata:

```
diff --git a/node_modules/@remix-run/server-runtime/dist/server.js b/node_modules/@remix-run/server-runtime/dist/server.js
index ba1443c..57bc5ab 100644
--- a/node_modules/@remix-run/server-runtime/dist/server.js
+++ b/node_modules/@remix-run/server-runtime/dist/server.js
@@ -256,7 +256,8 @@ async function handleDocumentRequest({
     headers: request.headers,
     method: request.method,
     redirect: request.redirect,
-    signal: request.signal
+    signal: request.signal,
+    cf: request.cf,
   });
   let routeLoaderResults = await Promise.allSettled(matchesToLoad.map(match => match.route.module.loader ? data.callRouteLoader({
     loadContext,
```

With that said, I don't really know what the appropriate solution is to this problem. I'm posting this as an issue with Remix, as it is on *some* level, but I am going to re-open a discussion on the Cloudflare end about why this happens, because it seems like a smell indicating another problem, rather than an issue in and of itself.

**Comment by tulup-conner** [comment]
Mentioned this on Cloudflare discord under `Service Bindings`: https://discord.com/channels/595317990191398933/922881438796378112/992613477392863323

**Comment by drewdecarme** [comment]
I am indeed having the same issue when trying access my service bindings. I was also used to accessing it on the Request under that special `cf` key, but I no longer can.

I originally went the route of using CF Pages, but I need some variables defined in the global context for some configuration files and I haven't found a way of doing that. In addition, I think service bindings are an awesome way to speed things up since my API is on CF Workers.

CF Workers suggests you destructure the `env` key from the request: https://developers.cloudflare.com/workers/platform/bindings/about-service-bindings/#gateway-worker-and-service-bindings-usage state here. This is also integral because CF Workers doesn't let you make request from workers on the same account so an app using Remix on CF Workers and an API on CF Workers wont work.

**Comment by drewdecarme** [comment]
After doing some serious digging... I ran across this wonderful bit of documentations with workers.

https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#bindings

Since the Remix worker is written and built using the service worker syntax such as below, much like the environment variables, it sticks all bindings on the global context. TBH, the global context magic of CF workers just blows my mind coming from a purely functional programming background. However, that's the way that it works.
```js
import { createEventHandler } from "@remix-run/cloudflare-workers";
import * as build from "@remix-run/dev/server-build";

addEventListener(
  "fetch",
  createEventHandler({ build,mode: process.env.NODE_ENV })
);
```

So if you go to run a loader, your service binding is going to be on the global context. So let's say that my api worker is called api-gateway, i can bind it like this in my `wrangler.toml`
```toml
services = [
  { binding = "API_GATEWAY", service = "api-gateway", environment = "production" }
]
```
Then I can use it in... I feel dirty saying this... in global context in my Remix Loader Function
```
export const loader: LoaderFunction = async ({ request }) => {
  const res = await API.fetch("...whatver");
  const data = await res.json();
  console.log(data);
  return json(data);
};
```

However, with that said, I haven't actually figured out a successful way to call my `API_GATEWAY` but at least we can access the service binding in some fashion.

**Comment by kamranayub** [comment]
Based on my usage of Remix + workers and bindings right now, I think this is fixed. At least, from loaders I can access `context.env.MY_SERVICE.fetch` and invoke them. And I noticed the code/path mentioned above is no longer applicable, I think it's handled within the cloudflare pages remix package now properly.
