### ISSUE TITLE
WDS not available in example with cloudflare workers

### ISSUE THREAD

**Issue by polRk** [remix-run/remix#3755]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

run `npx create-remix` choose cloudflare workers, open browser

### Expected Behavior

All are fine

### Actual Behavior

```
Remix dev asset server web socket closed. Reconnecting...
(index):22 WebSocket connection to 'ws://127.0.0.1:54195/socket' failed: 
remixLiveReloadConnect @ (index):22
(anonymous) @ (index):42
(index):49 Remix dev asset server web socket error:
react_devtools_backend.js:4026 Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
overrideMethod @ react_devtools_backend.js:4026
ws.onerror @ (index):50
error (async)
remixLiveReloadConnect @ (index):48
(anonymous) @ (index):42
setTimeout (async)
ws.onclose @ (index):40
(index):39 Remix dev asset server web socket closed. Reconnecting...
(index):22 WebSocket connection to 'ws://127.0.0.1:54195/socket' failed: 
```

**Comment by polRk** [comment]
Emm, i'm lost this error...

**Comment by amitabhdhiwal** [comment]
I got this when I ran `npm run dev:wrangler` instead of `npm run dev`.  :sweat_smile: 

`npm run dev` runs the asset server as well as local workers.

**Comment by mjackson** [comment]
I can't reproduce this. We have updated the Remix Cloudflare Workers template since this issue was opened. We used to rely on Wrangler for hot reloading, but we don't anymore with our new dev server. This appears to be a wrangler issue. Please [take a look at the new template](https://github.com/remix-run/remix/tree/main/templates/cloudflare-workers) and update.
