### ISSUE TITLE
Transition type needs to be imported from '@remix-run/react/dist/transition'

### ISSUE THREAD

**Issue by andresBobsled** [remix-run/remix#3866]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

Add `Transition` type to a .ts file. Only way to add the import is from '@remix-run/react/dist/transition'

### Expected Behavior

Ideally we don't import dist and we can import from '@remix-run/react'

### Actual Behavior

To import transition, the current line is:
`import type { Transition } from '@remix-run/react/dist/transition';`

**Comment by narutosstudent** [comment]
I think Transition has to be exported here: https://github.com/remix-run/remix/blob/d09663e608cc5373a25f1c23ec32844ff67ad9a6/packages/remix-react/index.tsx#L64

Then we can import it like we do with the Fetcher type.

Work around atm for stable import would be to get the return type of type useTransition `ReturnType<typeof useTransition>` in order to be able to use this type, or import from dist.

@kentcdodds @ryanflorence 

Is there a reason not to export all types from the transition file, right now the Fetcher type is the only exported type.

**Comment by kentcdodds** [comment]
Can you help me understand the use case for this?

**Comment by narutosstudent** [comment]
@kentcdodds We have a util function at Bobsled that says isSubmitting, where we pass the transition function.

I'm curious also, is there a reason not to export all types? What would be against it?

**Comment by kentcdodds** [comment]
Just want to limit how much we expose. I think it's sensible to export this. Though @ryanflorence or @mjackson will need to approve it. Until then you can use `patch-package`.

**Comment by kwiat1990** [comment]
I have a similar use case as @narutosstudent.

**Comment by markdalgleish** [comment]
I think it makes sense to export this too, but in the meantime you can get the type like this:

```ts
import { useNavigation } from "@remix-run/react";

type Navigation = ReturnType<typeof useNavigation>;
```

**Comment by markdalgleish** [comment]
The `Navigation` type will be exported in v2: https://github.com/remix-run/remix/pull/7136
