### ISSUE TITLE
useSubmit doesn't submit the button value

### ISSUE THREAD

**Issue by lili21** [remix-run/remix#3913]
### What version of Remix are you using?

1.6.7

### Steps to Reproduce

I create a stackblitz demo - https://stackblitz.com/edit/node-rwvnef?file=app%2Froutes%2Findex.tsx

You can click the `submit` button to reproduce the issue

### Expected Behavior

the terminal should output  `---formData--- { name: '', action: 'join' }`

### Actual Behavior

the terminal output  `---formData--- { name: '' }`

it's not the same behavior as click the `join` button

**Comment by n3oney** [comment]
I'm pretty sure this is intended behavior.

HTML buttons only submit the value inside of them if the form is submitted by clicking the button.
If you want a separate button to submit the value of a button, put the ref on the button, instead of the form.
If you want some additional data inside of the form, you can use the `hidden` input type.

MDN:
**value**
	Defines the value associated with the button's name when it's submitted with the form data. This value is passed to the server in params when the form is submitted using this button.

**Comment by lili21** [comment]
Ah, Thanks for the clarification.
