### ISSUE TITLE
[Bug] submit action causes multiple renders

### ISSUE THREAD

**Issue by rafalfigura** [remix-run/remix#3993]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

I have created a [GitHub repository](https://github.com/rafalfigura/remix-run-double-render) that can reproduce this problem. 

Steps: 
1. Create route with action in app/routes/index.tsx
```
export const action: ActionFunction = async () => {
  return json({ d: 'ok' });
};
export default function Index() {
    const actionData = useActionData();
    console.log(`index`, actionData);

    return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
        {JSON.stringify(actionData)}
      <Form method="post">
        <button type={`submit`}>submit</button>
        <input type={`text`} name={`data`} defaultValue={`asdasd`}></input>
      </Form>
    </div>
  );
}
```
3. Add console.log to root.tsx
```
export default function App() {
  console.log('root');
  return (
    <html lang="en">
       ...
    </html>
  );
}
```
2. Navigate to index route and click submit

### Expected Behavior

Page reload only once.

### Actual Behavior

Right now, the page reloads three times. When I switch Form method to `get` the page reloads twice.

<img width="758" alt="NMwv9HVPDr" src="https://user-images.githubusercontent.com/34662065/184505763-1fef830c-514a-4aa3-ac69-09df07ee52da.png">

**Comment by jacob-ebey** [comment]
This is expected behavior. `console.log(useTransition().state)` and you'll understand the reasons for the re-renders. When you submit a form with method POST, we undergo the following state transitions:

- Start in "idle"
- Submit form -> "submitting"
- Data revalidation -> "loading"
- When all is done -> "idle"

When submitting a GET form:

- Start in "idle"
- Submit form -> "loading"
- When all is done -> "idle"
