### ISSUE TITLE
Redirects caused outside of Remix are not handled correctly

### ISSUE THREAD

**Issue by dylanblokhuis** [remix-run/remix#4183]
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

- Create an example Remix project using Express
- Add a 301/302 redirect outside of Remix e.g. inside ``server.js`` to redirect ``/foo-redirect`` to ``/foo``
- Create two routes: ``foo.tsx`` and ``foo-redirect.tsx`` and add a loader to both
- Now create a route e.g. ``index.tsx`` and create a ``<Link to="/foo-redirect">..</Link>`` component
- Click on the ``<Link>`` component

Example repo: https://github.com/dylanblokhuis/remix-redirect-bug.git

### Expected Behavior

That the redirect is being followed and the user ends up on ``/foo``

### Actual Behavior

Redirect is not being followed and the user ends up on ``/foo-redirect``

**Comment by kiliman** [comment]
The issue is that if Remix does a client side fetch to your loader (which happens when you click on the `<Link>`), Remix handles redirects differently. You have to check for a data request (URL has search param `_data`). If so, you need to redirect using status 203 and header: `x-remix-redirect`, instead of the standard 301/302 status.

I have an example here: https://github.com/kiliman/express-auth-example/blob/4aed9f0bfeb85d7cc73d4e8232cbaf9cd1a1d1c3/server/index.js#L78

```js
  const url = new URL(`${req.protocol}://${req.get('host')}${req.originalUrl}`)
  const isDataRequest = url.searchParams.has('_data')
  if (isDataRequest) url.searchParams.delete('_data')

  const returnUrl = encodeURI(`${url.pathname}${url.search}`)
  const redirectUrl = `/login?returnUrl=${returnUrl}`

  return isDataRequest
    ? // special handling for redirect from data requests
      res.status(204).set('x-remix-redirect', redirectUrl).send()
    : res.redirect(redirectUrl)
```

**Comment by dylanblokhuis** [comment]
In my case we use a reverse proxy that handles all redirects (so its outside of Remix's environment completely), so having to make the reverse proxy handle redirects differently just for Remix is in my opinion not really great. Remix's ``fetchData(..)`` already handles redirects properly, it's just the transition part not working correctly. Hence my PR which fixes the problem, but I do not know for sure if it's the proper way to tackle the problem.
