### ISSUE TITLE
`remix dev --debug` isn't accessible from outside Docker

### ISSUE THREAD

**Issue by frontsideair** [remix-run/remix#4216]
### What version of Remix are you using?

1.6.5

### Steps to Reproduce

- Start a dev server with `remix dev --debug` inside a docker container
- Try to access it (from VSCode or Chrome Inspector) with the printed address

### Expected Behavior

The inspector should be attached

### Actual Behavior

The inspector doesn't attach

I think it's because the host is `127.0.0.1` by default (and not configurable) which doesn't work well with Docker, [see this SO answer](https://stackoverflow.com/a/59182290). It should either be `0.0.0.0` by default, or be configurable the way Nodejs debugger CLI is, like this: `node --inspect=0.0.0.0:9229 main.js`

**Comment by meglio** [comment]
I can confirm this is a problem.

The issue exists because `--debug` starts an inspector without specifying any parameters, and thus does not give us any way to specify a different host to bind to:

<img src="https://user-images.githubusercontent.com/282177/191400796-4860e6e4-eb18-4214-a2c1-43b3ca7e6a97.png" height=150/>

<p>&nbsp</p>

The [deafult host is `127.0.0.1`, which makes it impossible to connect to the inspector from outside of Docker:

https://nodejs.org/en/docs/guides/debugging-getting-started/#command-line-options

<img src="https://user-images.githubusercontent.com/282177/191400977-7f41c51c-f9a5-42f3-b6e1-80c0c05db4b1.png" height=250/>

A temporary workaround could be to use e.g. Socat to route debugger traffic accordingly.

The actual solution would be to make `--debug` in remix a **boolean OR string** argument, so that it can accept address and/or port to bind to: `--debug=host:port`. It is currently a boolean argument, so no custom host/port can be specified, and it is not passed through to `inspector.open();`.

**Comment by pcattori** [comment]
The new v2 dev server now let's you specify a custom server command, which means you can use `node` directly: `remix dev -c 'node --debug ./server.js'`

Note: You can use [binode](https://github.com/kentcdodds/binode) if you want to pass `node` flags to `remix-serve`.
