### ISSUE TITLE
Relative paths in markdown links don't reference current directory

### ISSUE THREAD

**Issue by cayblood** [remix-run/remix#4326]
### What version of Remix are you using?

1.7.2

### Steps to Reproduce

1. Create a markdown file in a subfolder under `routes`.
2. Using markdown syntax, create a relative link to a file in the same subfolder. For example, in `file1.md`, create the following link:
```
[Second file](file2)
```
3. Notice that the link is broken and does not include `/subfolder/file2`.

### Expected Behavior

I would expect the current folder that the markdown file is being served from to be prepended to any relative links.

### Actual Behavior

Other ancestors folders are included in relative links, but not the current folder.

**Comment by kiliman** [comment]
Hmm. I'm not seeing that behavior.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/47168/194111850-07e00798-3919-4a7a-ab77-f1bda58e81f2.png">

### Hover over link
<img width="208" alt="image" src="https://user-images.githubusercontent.com/47168/194111986-202ce9ae-e302-4f2e-bf1d-93cb0380346a.png">

### The actual URL in the `<a href>`
<img width="460" alt="image" src="https://user-images.githubusercontent.com/47168/194112260-15087798-75b6-4f35-858a-2245289ba251.png">

This is correct. Remix is not going to modify your markup. Because both files are in the parent folder, relative URLs will always be relative to the current folder it's in.

**Comment by cayblood** [comment]
Maybe my question is: why doesn't clicking on the relative path take me to the file?

**Comment by kiliman** [comment]
I'm not sure. When I click on the link, I see file2. Do you have a simple repo available?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/47168/194127949-043afdfa-83bf-470c-bf6c-62e6d30da351.png">

**Comment by cayblood** [comment]
@machour I've tried to reproduce this with a simpler example but can't do it. Would it be possible to invite you to a private repo where it is happening so that you can reproduce it with that? The repo isn't especially sensitive or complex, it just hasn't been released yet.
