### ISSUE TITLE
Option to customize request logging

### ISSUE THREAD

**Issue by maximilize** [remix-run/remix#4351]
### What version of Remix are you using?

v1.7.0

### Steps to Reproduce

Create a project with express and start it. `morgan` logging is statically enabled with `tiny` config.

### Expected Behavior

Options to set own request logging options, for example to disable them at all.

### Actual Behavior

A static config of morgan is used.

**Comment by machour** [comment]
@maximilize You are free to change the `server.js` file and the logging mechanism like you want when using the express template. 
Is there anything preventing you from doing it?

**Comment by valotas** [comment]
@machour `@remix-run/serve` has a factory method that returns the remix as an express middleware. That middleware contains also a logging middleware.

I can understand the existence of a logger there since you would like to see something the first time you start your app, but there should be a way to replace it with what is being used in the rest of the app (in case you would like to do so).

For the moment, we either have to create our own `createApp` factory that looks like `@remix-run/serve` or manipulate the returned `middleware._router.stack`. Both solutions do not look that elegant.

**Comment by machour** [comment]
@valotas Feel free to post a proposal for change in the [discussions tab](https://github.com/remix-run/remix/discussions) 🙏🏼

**Comment by sergiodxa** [comment]
@valotas `@remix-run/serve` is intentionally closed so you can't customize it, the idea is that if you don't care about customizing the server you use that, if you want to customize your Express server then you can use the Express template and adapter to have full control to customize your logger.

**Comment by valotas** [comment]
@sergiodxa thanks! Now it is clear to me. Please ignore my comments :)
