### ISSUE TITLE
Document the gotcha for esbuild css plugin

### ISSUE THREAD

**Issue by machour** [remix-run/remix#4396]
An error is thrown when using either filter for onLoad (seems like esbuild is attempting to load it as js even though "main" is pointed to index.css)

We need to document a little gotcha until we find a proper solution, see discussion here: https://github.com/remix-run/remix/pull/4130#issuecomment-1279149538

**Comment by KingSora** [comment]
@machour I think it would be good if we investigate further on this, because isolated tests show that this issue might be related to other plugins / things above esbuild. Opened an issue on esbuilds side and got the confirmation there as well. https://github.com/remix-run/remix/pull/4130#issuecomment-1280845923

**Comment by machour** [comment]
Definitely, but until then, the issue should be properly documented for our users.

Thank you again for your contribution, already using it! 🙏

**Comment by machour** [comment]
Nobody complained 🤷🏼
