### ISSUE TITLE
Can't use typeorm in loaders

### ISSUE THREAD

**Issue by pascal-codetaal** [remix-run/remix#45]
I want to use typeorm as orm, the typeorm setup in done in server.ts But as soon as i import the Entities in the loaders the loaders stop rebuilding. I have created a small repo where the issue can be seen.
[https://github.com/pascal-codetaal/starter-express.git](https://github.com/pascal-codetaal/starter-express.git

[https://github.com/pascal-codetaal/starter-express/blob/7a265e8cfa601ddee900614b02935dc6d1b6acf5/loaders/routes/index.ts#L2](https://github.com/pascal-codetaal/starter-express/blob/7a265e8cfa601ddee900614b02935dc6d1b6acf5/loaders/routes/index.ts#L2)
if i uncomment this line -> the loader stops building

**Comment by sergiodxa** [comment]
If you import files from outside the `app` folder Remix compiler is not going to rebuild when they change.

If you put all the TypeORM related code inside the Express server code instead of the Remix app folder, you should pass the entities using the context objects all loaders and actions share.

See https://remix.run/docs/en/v1/other-api/adapter#createrequesthandler the `getLoadContext` method.
