### ISSUE TITLE
`handleDataRequest` function inside `entry.server.tsx` doesn't do anything

### ISSUE THREAD

**Issue by eseyfert** [remix-run/remix#4505]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

Following the Remix docs, I added this to my `entry.server.tsx`:

```tsx
// this is an optional export
export const handleDataRequest: HandleDataRequestFunction =
  (
    response: Response,
    // same args that get passed to the action or loader that was called
    { request, params, context }
  ) => {
    response.headers.set("x-custom", "yay!");
    return response;
  };
```
But the response will not get changed in any way.

### Expected Behavior

I expect the new headers I set for the data routes to actually show up in the Response.

### Actual Behavior

No matter what I change about the response inside that function, the data routes do not reflect that change.
I have used tools like `Postman` or just `curl` in the terminal to check the headers and your example in the docs does not work. None of my data routes actually have the additional `x-custom` header.
Maybe I am misunderstanding or misusing the function?

**Comment by machour** [comment]
Hey @eseyfert 👋🏼 

As stated on the documentation, `handleDataRequest` is for modifying the response of a *data* request.

> You can also export an optional handleDataRequest function that will allow you to modify the response of a data request. These are the requests that do not render HTML, but rather return the loader and action data to the browser once client side hydration has occurred.

If you want to add a header in response to all requests, then you need to set that in `handleRequest` instead, just like it's currently setting the `Content-Type` to `text/html`

**Comment by machour** [comment]
in other words, `handleDataRequest` is used when an url gets called with Remix's `_data` request parameter.
You can see it in Postman using this url for example:
    http://localhost:3000/?_data=root

**Comment by eseyfert** [comment]
First of all, thank you for the quick response. 😄 
So the way I understood it, the function is for routes that only expose a `loader` or `action` function, so I was trying to specifically target those.
When exactly is the `_data` request parameter used?

**Comment by machour** [comment]
You were almost correct, but you missed that chunk of the sentence: "... to the browser once client side hydration has occurred"

The `_data` parameter is used when Remix hydrates into a SPA. 

It's used to let Remix know that this is not a full page request (an initial load) but rather the result of a client side navigation :

I'm on page A, I click a link to page B => B gets called with the `_data` parameter and Remix knows that it only needs to send the result of the loader instead of the full page, and in this particular case, `handleDataRequest` gets called.

The nuance is that when you call the URL without the `_data` parameter (from Postman for example), you're doing a "full page request" instead of a "data request", even if you're targeting a resource route.

Hope that clears things up for you!

**Comment by eseyfert** [comment]
Aaah, that made it click.
So clearly this is not an actual issue. 😄 
Thank you again so much for the quick responses.
Hope you have a great rest of the week!

**Comment by machour** [comment]
You're very welcome!
