### ISSUE TITLE
getting Error: useRoutes() may be used only in the context of a <Router> component

### ISSUE THREAD

**Issue by thchaitra** [remix-run/remix#4654]
### What version of Remix are you using?

1.7.5

### Steps to Reproduce

We have recently moved to remix. we are getting issue like - Error: useRoutes() may be used only in the context of a <Router> component. ​when the remix version is upgraded from version 1.7.0 to 1.7.5

### Expected Behavior

Even thought the version got upgraded, the application should work as usual.

### Actual Behavior

The application was not running. As I am getting error, Error: useRoutes() may be used only in the context of a <Router> component.

**Comment by machour** [comment]
We need a reproduction in order to help

**Comment by ADCrouch** [comment]
I'm also migrating our Create React App to Remix, and I got this error.
@machour  To reproduce it, perhaps try to implement a route with a few routes from "react-router-dom"?
```
<Routes>
  <Route path="/" element={<div>home</div>} />
  <Route path="/about" element={<div>about</div>} />
</Routes>
```

**Comment by AndKiel** [comment]
I had a similar issue. My error was:

> Error: useLocation() may be used only in the context of a <Router> component.

I was importing and using

```typescript
import { useSearchParams } from "react-router-dom";
```

After importing it from `"@remix-run/react"` it started working.

Happened after upgrading remix and react-router-dom to the latest. Kinda weird.

**Comment by drewjs** [comment]
The issue first appears when bumping remix from `1.7.0` to `1.7.1`.  

repro link: https://stackblitz.com/edit/remix-issue-4654

I first encountered this while trying to migrate an old CRA project so that's why I used this specific template.  It seems to be some incompatibility with `react-router-dom`, but I haven't dug further than that.

Basically if you are still migrating `<Routes>` to Remix you may want to stick with a similar setup to make sure that Remix and React Router are working together properly:

```json
"dependencies": {
    "@remix-run/node": "1.7.1",
    "@remix-run/react": "1.7.1",
    "@remix-run/serve": "1.7.1",
    "react-router-dom": "6.3.0"
  }
```

**Comment by brophdawg11** [comment]
This happens when you have 2 different versions of `react-router-dom` in your `node_modules` - usually the Remix internal version and your own `package.json` version.  Generally, you do not want to have your own `react-router-dom` dependency and import everything from `@remix-run/react`.  

However if you need to use features outside the "normal" remix scope (like `useRoutes`), then you need to make sure they are always synced (so if you update Remix you need to update your local `react-router-dom` dependency) and also deduped in `node_modules`.
