### ISSUE TITLE
Loader not being rerun after action when PrefetchPageLinks is used

### ISSUE THREAD

**Issue by liegeandlief** [remix-run/remix#4750]
### What version of Remix are you using?

1.6.8

### Steps to Reproduce

See failing test case at https://github.com/remix-run/remix/pull/4730. I wasn't sure if I need to open this bug as well as creating the failing test case pull request.

### Expected Behavior

Prefetched data is reloaded after actions have been run

### Actual Behavior

Prefetched data is not reloaded after actions have been run and so stale prefetched data is used

**Comment by brophdawg11** [comment]
This is expected since prefetching puts your loader response into the prefetch cache for a short period of time.  Since your action is mutating the data returned by the loader you do not want to use `PrefetchPageLinks` for the action route since that will put potentially stale data into the browser prefetch cache.
