### ISSUE TITLE
[Feature]: Importing CSS in Components instead of routes

### ISSUE THREAD

**Issue by adebiyial** [remix-run/remix#493]
### What is the new or updated feature that you are suggesting?

I figured CSS imports can only be done with route components for now, it'd be cool to be able to import it in any component

### Why should this feature be included?

This is because not all components are routes and some [helper] components needs their styles to be isolated with them much more like data to UI. Ryan — styles colocation, please 😢

**Comment by chaance** [comment]
We intend on expanding the scope of our compiler to provide solutions to CSS imports at the component level. In the mean time you'll need to extract these to a stylesheet.

A pattern I've been using is running postcss in parallel with the Remix dev script, and moving the imports from my components into a singular stylesheet I import in the root.

So instead of:

```js
// button.jsx
import "~/styles/button.css";
export function Button() { /* */ }
```

Do this:

```css
/* styles/components.css */
@import "./button.css";
```

There are tradeoffs here of course, but this is our recommended approach until we decide on better integration strategies.
