### ISSUE TITLE
File route URL escape error

### ISSUE THREAD

**Issue by akun2333** [remix-run/remix#5099]
### What version of Remix are you using?

1.10.1

### Steps to Reproduce

1.Create new router file name: $code[.]code.ts, It's OK
2.Create new router file name: code[.]$code.ts, But this doesn't match

### Expected Behavior

--

### Actual Behavior

--

**Comment by machour** [comment]
What urls are you trying to match against?

**Comment by brophdawg11** [comment]
React Router does not support partial dynamic parameters, such as `path="prefix:param"`.  The parameter must be a full URL segment (between slashes).  This is why the second one doesn't match.  The first one matching is not quite valid since it generates a path of `path=":code.code"` and you can't currently use dots in param names.

For your case, you should use `routes/$code.tsx` and then you can split on the dot to get the first and second half: 

```
// $code.tsx
export function loader({ params {) {
    let parts = params.code.split('.');
    // When URL = /code.123456   
    //   parts[0] => 'code'
    //   parts[1] => '123456'
    // When URL = /123456.code
    //   parts[0] => '123456'
    //   parts[1] => 'code'
}
```
