### ISSUE TITLE
Changing fragment does not run effects

### ISSUE THREAD

**Issue by liegeandlief** [remix-run/remix#5147]
### What version of Remix are you using?

1.11.0

### Steps to Reproduce

Create a route as follows:

```JSX
import { useLocation } from '@remix-run/react'
import { useEffect, useCallback } from 'react'

const TestComponent = () => {

  const handleButtonClick = useCallback(() => {
    window.location.hash = 'updatedfragmentwithjs'
  }, [])

  const location = useLocation()

  useEffect(() => {
    console.log(`Fragment changed to: ${location.hash}`)
  }, [location.hash])

  return (
    <div>
      <button onClick={handleButtonClick}>Update fragment with JS</button>
      <a href='#updatedfragmentwithlink'>Update fragment with link</a>
    </div>
  )
}

export default TestComponent
```

### Expected Behavior

Clicking the button should log `Fragment changed to: updatedfragmentwithjs`.

Clicking the link should log `Fragment changed to: updatedfragmentwithlink`.

### Actual Behavior

The fragment is updated in the address bar but `location.hash` does not change and so nothing is logged.

In Remix version `1.9.0` and earlier the expected behaviour occurs.

**Comment by brophdawg11** [comment]
This is actually a bug fix as this isn't correct usage.  React Router can't respond to external navigation events except back/forward navigations (but only when those go back to locations previously created by RR). Because the hash is a new location, this would be like doing a  manual `history.pushState()` which also wouldn't work.

Instead, you should use `useNavigate`:

```jsx
function TestComponent() {
  let navigate = useNavigate()l 
  const handleButtonClick = useCallback(() => {
    navigate({ hash: 'updatedfragmentwithjs' });
  }, [navigate])
  ...
}
```

Or since this is a navigation, use a `<Link to="#updatedfragmentwithjs">`
