### ISSUE TITLE
🗺️ Remix Retune (HMR)

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#5240]
Clientside assets only, expect the server to do it's own reboot/reload etc. when the server assets change (since they all do anyway, and in the case of express, just do `--watch` in v19)

## PRs

- [x] #5259
- [x] https://github.com/remix-run/react-router/pull/9996

## TODO

- [ ] blog post: https://github.com/remix-run/remix-website/pull/74

**Comment by ryanflorence** [comment]
@jacob-ebey and Pedro to pair on this, especially in the beginning

**Comment by pcattori** [comment]
# How we handle different types of updates

## Prototype

Any code changes: HMR new modules only applying React Refresh after routes revalidate

## Platonic ideal

Detect addition or change of loaders so we only revalidate those.

Removal shouldn't require special handling.
Stale data can just be kept around and garbage collected.
Or we can "revalidate" it which will instantly clean it up since there's nothing to do.

### How to detect loader changes

Hash the loader function.
Ideally we could detect subtle things like an import alias changing or an import source changing even when loader source code stays the same, but that's HARD, so not gonna do that. At least not now.
