### ISSUE TITLE
Vanilla extractor styles are not being applied

### ISSUE THREAD

**Issue by Lucas-Eduardo-Goncalves** [remix-run/remix#5281]
### What version of Remix are you using?

1.11.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

// Clone the repository
`git clone git@github.com:Lucas-Eduardo-Goncalves/remix_template.git`

// Install the packages
`npm install` or `yarn`

// Run the application
`npm run dev` or `yarn dev`

### Expected Behavior

The application in the path `./app/models/notProtect/HomeModel/view` should generate the styles for the tag `<Div/>`, which is in the route `http://localhost:3000/`.

### Actual Behavior

The remix is ​​generating the class for the component but not generating the css.

![image](https://user-images.githubusercontent.com/92813658/214979940-a592bebb-5328-458b-8303-2f5fb5827bff.png)

![image](https://user-images.githubusercontent.com/92813658/214979978-c382b9a1-bb0a-45ca-94f1-b4ce92219e1b.png)

![image](https://user-images.githubusercontent.com/92813658/214980030-d0bac8b7-b791-4f6e-8de4-7470b3e3367a.png)

(ps: This also happens when trying to use a `globalStyle`, but I managed to solve this error by putting the `globalStyle` function inside a file that exports some kind of style inside a variable)

**Comment by markdalgleish** [comment]
Thanks for the bug report! This looks like the same issues as https://github.com/remix-run/remix/issues/5270. This is an issue with esbuild (https://github.com/evanw/esbuild/issues/1370) which has been triggered by your use of `export *` in `app/models/notProtect/index.ts`. As a workaround you can use named re-exports instead:

```diff
-export * from "./HomeModel";
+export { HomeModel } from "./HomeModel";
```

I'm closing this as a duplicate, but you can follow further developments in https://github.com/remix-run/remix/issues/5270.

The other issue you mentioned about tree-shaking of `globalStyle` was fixed in https://github.com/remix-run/remix/pull/5246 which will be in the next Remix release.
