### ISSUE TITLE
🗺️ "remix cli"

### ISSUE THREAD

**Issue by mjackson** [remix-run/remix#5335]
The idea here is to add CLI functionality to the `remix` package so that people can use `npx remix` directly and avoid having to add `@remix-run/dev` to their `devDependencies`.

This entails a few main pieces of work:

- add a `bin` entry to the `remix` package.json that invokes the Remix CLI. The `create-remix` package currently does this
  - `@remix-run/dev` will be in remix's `devDependencies`
- update all documentation to remove `@remix-run/dev` from `devDependencies` and use `npx remix` instead
- we will need to install `remix` as part of the Remix install process instead of installing `@remix-run/dev`
  - be sure to look at how `create-remix` currently creates new apps and installs deps

IMPORTANT: we should be sure we understand well the semantics of using `npx` to invoke Remix. Specifically, do we understand how caching works? Are we going to have to use `npx remix@latest` everywhere in our docs? or is `npx remix` sufficient?

**Comment by kiliman** [comment]
I believe `npx` maintains its own cache. It's not the same as `npm install -g` (global).

My experience is that relying on which version with `npx` is hit or miss, so I always use `@latest` 😔

**Comment by sergiodxa** [comment]
I also always add `@latest` to any `npx` line to ensure I don't use a cached version.

But for packages installed in the project `npx` is going to use the installed version by default so you could do `npx remix` and it will use the version in your `package.json`, if you're in a folder without a `package.json` it will use a global one AFAIK.

If that's the case, it should be possible to document the usage as `npx remix` for scripts you run in your own project and `npx remix@latest` for global ones as it could be an `npx remix new|create`.

Another option is to document as `npx remix@latest` and use `nom run` to tell the developers using Remix to run project specific scripts, for example `npm run routes` that runs `remix routes`.

**Comment by chaance** [comment]
Discussed this with @mjackson today, and here's where I think we're at.

1. **What is the goal?** Simplify the entrypoint into all Remix CLI tools with a single command that can be used with or without installing a dependency in your project
2. **What are the advantages?**
    - `npx remix` is short, intuitive and easy to remember
    - `npx remix` can be used from anywhere, expanding our options for tools projects that don't currently use Remix -- ex. Imagine I have a file with a React Router config and I could run `npx remix create --from./routes.tsx` and it would generate all of the files for a new Remix project
3. What are the disadvantages?
    - Users can more easily invoke a version of the CLI that doesn't work with the version of Remix in their app
    - We now rely on `npx` maintaining stable semantics and functionality
    - Cached installs will likely cause problems in some contexts

Here's where my head is on this: I like utilizing the `remix` package for to make it possible to invoke Remix commands with or without installing it as a dependency. I don't necessarily agree that we should encourage the no-dependency route for most existing use-cases when running commands for a specific app (`remix dev`, `remix start`, etc.). I want my local server to compile my app using the same version of the Remix compiler as all of my other Remix dependencies. That's much more predictable and easier to control if I have the package installed locally.

Also, `npx remix` will already work when used in the context of a Remix app because `npx` will find our local install of `@remix-run/dev` whose bin uses `remix` as its entrypoint. **So I think the only work we really need to do here is leverage the `remix` package to expose all of the commands found in `remix dev` and declare it as its own dependency.** If we're going to update any docs/templates, we could just swap out the `@remix-run/dev` package for `remix` in `devDependencies`.

**Comment by MichaelDeBoey** [comment]
Although this wouldn't be a problem in v2 anymore, we need to keep in mind that we're explicitly removing the `remix` dependency (& it's usage in `postinstall`) when running the `replace-remix-magic-imports` codemod

**Comment by mjackson** [comment]
> we could just swap out the @remix-run/dev package for remix in devDependencies.

The idea is that `remix` would be a normal dep and it would have `@remix-run/dev` in its `devDependencies`. So we wouldn't actually tell anyone to ever install `@remix-run/dev` in our install instructions.

**Comment by chaance** [comment]
> The idea is that `remix` would be a normal dep and it would have `@remix-run/dev` in its `devDependencies`. So we wouldn't actually tell anyone to ever install `@remix-run/dev` in our install instructions.

I'm not sure if I was clear here, but what I meant was that users would install `remix` in *their* `devDependencies` in place of `@remix-run/dev`. So correct, we'd never ask them to install `@remix-run/dev` after this change.

**Comment by chaance** [comment]
Hmm, ok. What is the main difference you see in going with that approach? Do you anticipate that we also end up shipping production code with the `remix` package?

**Comment by MichaelDeBoey** [comment]
> and they would get the dev tools when they are in development

@mjackson That's not how `devDependencies` work. Only the packages that are in _your own_ `package.json`'s `devDependencies` will be installed, not the packages that are mentioned in the `devDependencies` of your own packages in `node_modules`.
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#devdependencies
