### ISSUE TITLE
[BUG] Javascript projects now include Typescript dependencies

### ISSUE THREAD

**Issue by unsivilaudio** [remix-run/remix#5382]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- create new project with `npx create-remix@latest myapp`
- select 'Just the basics' and 'Javascript'

### Expected Behavior

Clean project with no mention of Typescript anywhere

### Actual Behavior

tsconfig.json persists, and package.json includes all Typescript dependencies and "typescheck" script.  I looked through the version changelogs, and [this PR](https://github.com/remix-run/remix/pull/5228) seems like the most likely culprit.

**Comment by pcattori** [comment]
Removal of all Typescript-related code and config was unreliable and buggy since Remix doesn't control stuff outside of the `app/` directory. Instead, Remix CLI now ensures that the `app/` directory is rid of TS when selecting "Javascript".

For more, see [our decision doc](https://github.com/remix-run/remix/blob/main/decisions/0008-only-support-js-conversion-for-app-code.md).

**Comment by pcattori** [comment]
As a separate issue, its probably worth updating the CLI prompt to make it clear that only the `app/` directory is targeted for JS conversion.

**Comment by unsivilaudio** [comment]
Thank you for your response. I originally thought maybe it was intentional but I couldn't find documentation to support that.  Cheers and thanks for pointing me to that information.
