### ISSUE TITLE
`submit` from `useSubmit` triggers previous request which was called from the `fetcher`

### ISSUE THREAD

**Issue by Danxil** [remix-run/remix#5557]
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

`
   const load = (model: SearchModel) => {
    let formData = new FormData();

    formData.append('some', 'value')
    
    submit(formData);
  };

    const loadMore = ({ page }: SearchModel) => {
      fetcher.load('/?index&page=1');
    };
`

Function `load` should be called, after this`loadMore` should be called

### Expected Behavior

After call of `loadMore` function, only request from this function should be triggered
After call of `load` function, only request from this function should be triggered

### Actual Behavior

After call of `loadMore` function, request from this function is triggered
After call of `load` function - request from this function Is triggered. But after this request with parameters from previous call of `loadMore` is triggered as well

**Comment by brophdawg11** [comment]
This is expected behavior currently because `fetcher.load` calls, just like loaders, automatically revalidate after you submit a mutation.  For now you can disable this with a `shouldRevalidate` on the route you are loading from.

Keep an eye on this [proposal](https://github.com/remix-run/react-router/discussions/10006) which should make this a bit easier as well.
