### ISSUE TITLE
`@remix-run/testing` `createRemixStub` `useLoaderData` returns `undefined`

### ISSUE THREAD

**Issue by nobleach** [remix-run/remix#5565]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create a `RemixStub`:
```typescript
    const mockMenuLinksResponse = {
      data: {
        links: [
          {
            id: '1e98d9e9-e51a-46ec-b8a2-2299519065e8',
            name: 'some-name',
            label: 'Some Name',
          },
        ],
      },
    };

    const RemixStub = unstable_createRemixStub([
      {
        path: '/us',
        loader: () => mockMenuLinksResponse,
        element: <MenuLink />,
      },
    ]);

        const { queryByText } = render(
      <RemixStub
        initialEntries={['/us']}
        hydrationData={{ loaderData: { '/us': mockMenuLinksResponse } }}
      />
    );
```

Try to access loader data in rendered component:
```typescript
  // inside component
  const data = useLoaderData();
  console.log('### data', data); // undefined
```

### Expected Behavior

I'd expect `useLoaderData()` to return the `mockMenuLinksResponse` data. 

The actual implementation does work... fetched data is logged when running the app.

### Actual Behavior

`undefined` is logged.

**Comment by frontendphil** [comment]
I get something similar, but only when I use the actual `loader.` 

With a loader that returns a `json` response like this:

```tsx
// route.tsx
export const loader = () => json({ some: 'data' })
```

I would expect test code that looks like this:

```tsx
import Page, { loader } from './route'
 const RemixStub = unstable_createRemixStub([
  {
    path: '/route',
    loader,
    element: <Page />,
  },
]);
```

To work. However, the response isn't unwrapped. I guess this is simply not implemented yet? It would be great though since working with actions already is pretty sweet. I can write a full integration test between user interaction and stuff ending up in my database. It would be even better if that would also work the other way round: Put something into a DB and then make sure it appears correctly in the UI. I know, I can test the loader in isolation and assert stuff on the response but if you ask me nothing beats a proper integration test.

**Comment by brophdawg11** [comment]
@nobleach Your issue is just an invalid `id` in the `hydrationData`.  Remix automatically assigns these IDs based on the filename, but in your testing setup there are no files so it inherits the default built-in ID generation from React Router which is just to use the route's position in the tree.  Since you only have one route, that ID would be `"0"`.  If it was the first child of the first route route, it would be `"0-0"`, and so on.

```js
  let RemixStub = unstable_createRemixStub([
    {
      path: "/us",
      loader: () => mockMenuLinksResponse,
      element: <MenuLink />,
    },
  ]);

  let { container } = render(
    <RemixStub
      initialEntries={["/us"]}
      hydrationData={{ loaderData: { "0": mockMenuLinksResponse } }}
    />
  );
```

Usually in testing scenarios I just add my own IDs for clarity:

```jsx
  let RemixStub = unstable_createRemixStub([
    {
      id: 'us',
      path: "/us",
      loader: () => mockMenuLinksResponse,
      element: <MenuLink />,
    },
  ]);

  let { container } = render(
    <RemixStub
      initialEntries={["/us"]}
      hydrationData={{ loaderData: { "us": mockMenuLinksResponse } }}
    />
  );
```

**Comment by brophdawg11** [comment]
@frontendphil I'm not seeing this behavior, the following test passes for me:

```jsx
test("test", async () => {
  function Comp() {
    return <pre data-testid="pre">{JSON.stringify(useLoaderData())}</pre>;
  }

  let RemixStub = unstable_createRemixStub([
    {
      path: "/",
      loader: () => json({ ok: true }),
      element: <Comp />,
    },
  ]);

  render(<RemixStub />);

  expect(await screen.findByTestId("pre")).toMatchInlineSnapshot(`
    <pre
      data-testid="pre"
    >
      {"ok":true}
    </pre>
  `);
});
```

If you are still having issues, please open a new issue with a minimal reproduction.  Thank you!
