### ISSUE TITLE
Specify `Content-Length` header when `redirect()`

### ISSUE THREAD

**Issue by nicholaschiang** [remix-run/remix#5595]
### What version of Remix are you using?

^1.11.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new Remix project;
2. Create a new resource route (e.g. `/`) that just returns a `redirect('/some-page')`;
3. Run the following (or visit the page in your browser and inspect the network request):

```
$ curl -s -I http://localhost:3000
HTTP/1.1 302 Found
location: /login
Date: Mon, 27 Feb 2023 21:11:33 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```
4. Notice that there is no `Content-Length` header in that response and thus it is invalid.

### Expected Behavior

There should be a `Content-Length` header of `0` when returning a 302 redirect.

### Actual Behavior

There is no `Content-Length` header. This is an invalid HTTP response.

### Temporary Solution

I've implemented a small wrapper around the Remix `redirect` function:

```ts
import { redirect as remixRedirect } from '@remix-run/node'

export function redirect(path: string, init?: ResponseInit) {
  // TODO remove this explicit header once the automatic content-length
  // header setting is fixed upstream (e.g. in the express app or remix).
  const headers = new Headers(init?.headers)
  headers.set('Content-Length', '0')
  return remixRedirect(path, { ...init, headers })
}
```

**Comment by nicholaschiang** [comment]
This may be an issue upstream with Express or whatever Remix is using to handle setting the `Content-Length` header for other requests. Note that I am not using a custom Express server and instead use `@remix-run/serve`.

**Comment by brophdawg11** [comment]
I dug into this a bit more and this is feeling more like an adapter-layer concern to me.  It turns out that if you remove the `compression` middleware included by default in the express template, then the `transfer-encoding: chunked` goes away and `content-length: 0` shows up correctly.  So I think this is a concern you can/should handle in your express server.  

Per https://groups.google.com/g/nodejs/c/4HyYmbBjbiE?pli=1 it sounds like setting `Content-Length` manually like you are is the correct way to tell `node` not to use chunked encoding.
