### ISSUE TITLE
HMR does't work for nested route

### ISSUE THREAD

**Issue by lili21** [remix-run/remix#5709]
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. create a nested route. such as 'routes/example/test.tsx'

```jsx
export default function () {
  return (
    <div>
      hello, remix. test test
    </div>
  );
}
```

2. run dev server with hmr
3. edit `test.tsx` 

### Expected Behavior

hmr works. 

### Actual Behavior

it doesn't work.

**Comment by lili21** [comment]
You can try to edit the `routes/game_center/test.tsx` route. and the ui didn't updated.

**Comment by dmarkow** [comment]
Looks like your default export on `routes/game_center/test.tsx` is unnamed. Add a name and it works. I imagine this has something to do with HMR needing a name to know which function to replace/update.

```typescript
export default function Test() {
```

**Comment by kiliman** [comment]
Makes sense. I typically name by default export either `Route` or `Layout` if I don't have a specific one in mind.

This should probably be called out in the Release Notes and documentation. Although there is a proposal to required a named export `Component` as your UI component instead of the default. I'm not sure I'm in favor of that though.

**Comment by lili21** [comment]
@dmarkow That's the problems. how did you find it? 😄 

@kiliman Agree. It's a great feature, but need a better documentation.

Thank you guys, I finally make it work
