### ISSUE TITLE
Unmounting a fetcher cancels the request of an adjacent form

### ISSUE THREAD

**Issue by oscarnewman** [remix-run/remix#5719]
Playwright test: https://github.com/remix-run/remix/pull/5720

### What version of Remix are you using?

1.14

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Reproduction created here with a much more detailed series of instructions: https://stackblitz.com/edit/remix-run-remix-amqk6n?file=app/routes/index.tsx

Written out:

Part 1:
- Open your network tab
- Have a `<Form method="get" id="1">` adjacent to a `<fetcher.Form id="2" method="get" action="somethingElse">` on the same route.
- Submit the fetcher form
- Now, submit the regular form again. 

Part 2:
- Add a button inside of the fetcher form that:
  -  Submit's the first form with `form="1"`
  - Waits ~100ms to unmount the entire second form
- Now, submit the fetcher form
- Then, click the second button you just added  

### Expected Behavior

- Submitting the regular form always sends one and only one XHR request to its `action` url. 
- `navigation.state` changes but the separate fetcher's `fetcher.state` does not when submitting the regular form
- Unmounting the fetcher while the first form is submitting, after having submitted the fetcher once, does not cancel the first form's XHR request

### Actual Behavior

- Once the fetcher is submitted once:
  - Submitting the regular form now sends two XHR requests -- one to its action and one to the href passed to `fetcher.load`
  - `fetcher.state` will be `loading` whenever the first form is submitted
  - Unmounting the fetcher while the first form is submitting will cancel the first forms' request and get the app stuck in `navigation.state=loading`

**Comment by brophdawg11** [comment]
Discussed in Discord but adding here for visibility.

The 2 API calls happening on submission are expected since once you perform a `fetcher.load` it will revalidate alongside route loaders.  This can be opted out of via `shouldRevalidate` on the route the fetcher it loading from.

The second issue is a bug in that revalidating fetchers share an `AbortController` with the navigation that caused them to revalidate.  This introduces a sort of 2-way binding when we only want one-way.  If the navigation is aborted we want the fetcher to abort.  However, if the fetcher is aborted (via unmounting) it should not impact the navigation.  This is fixed in https://github.com/remix-run/react-router/pull/10271.

Also worth noting that as a workaround, if you opt out of revalidation for the fetcher then the unmounting won't impact the ongoing navigation since there won't be a revalidating fetcher to abort on fetcher deletion.
