### ISSUE TITLE
Using prisma-client breaks useState()

### ISSUE THREAD

**Issue by seishunpop** [remix-run/remix#5893]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create some state like a counter button
2. Import prisma-client: `import { PrismaClient } from "@prisma/client";`
3. Instantiate prisma: `const prisma = new PrismaClient()`
![usestate](https://user-images.githubusercontent.com/94811245/227430976-873f7bb6-fe64-4dc4-8606-c0b1addd1368.jpg)

### Expected Behavior

I wrote a simple button counter that should increment on every click.

### Actual Behavior

For some reason prisma-client is preventing the increment code.
the count from useState can be referenced on the initial render, but clicking the button to call setCount doesn't work.

**Comment by sergiodxa** [comment]
Move `const prisma = new PrismaClient()` to inside the loader or to a `.server.ts` file, creating a new PrismaClient is a potential side-effect so the compiler is included Prisma in the client-side bundle and this cause an error (because it can't run on browsers) and breaks your app client-side.

You still get the initial value because your app is server rendering correctly, but it never hydrates which makes your event listeners not work.

**Comment by seishunpop** [comment]
Your solution worked! Thank you for the detailed explanation <3
