### ISSUE TITLE
Server build tree shaking not working

### ISSUE THREAD

**Issue by jasonkuhrt** [remix-run/remix#5904]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

See this repro repo https://github.com/prisma/repro-remix-tree-shaking

### Expected Behavior

The server build only bundles what is imported.

### Actual Behavior

The server build brings in everything regardless of it its imported.

----

A consequence of this issue is that it makes it AFAICT impossible to deploy something like `@opentelemetry/api` to Cloudflare. I suspect there are lots of other packages blocked by this.

**Comment by jasonkuhrt** [comment]
Discovered this https://github.com/aiji42/remix-esbuild-override, thanks @millsp.

**Comment by pcattori** [comment]
@markdalgleish this looks to be related to polyfills in 1.19.x:

```sh
✘ [ERROR] No matching export in "node-modules-polyfills:node:perf_hooks" for import "createHistogram"

    some-lib/do-not-import-me.ts:1:9:
      1 │ import { createHistogram } from "node:perf_hooks";
```

whereas replacing `node:perf_hooks` with `node:fs` works (i.e. build succeeded and server-only code is treeshaken).

**Comment by markdalgleish** [comment]
The tree shaking is working, as @pcattori pointed out when using a different Node builtin. The issue here is that the tree shaking happens later in the build process after the modules have been resolved. In this case there's a couple of issues caused by the [JSPM core polyfill for perf_hooks](https://github.com/jspm/jspm-core/blob/main/nodelibs/browser/perf_hooks.js):

- The `createHistogram ` function isn't polyfilled at all.
- The polyfill assumes `globalThis.performance` exists, but this is undefined in Cloudflare Workers, seemingly for security reasons: https://developers.cloudflare.com/workers/learning/security-model/#step-1-disallow-timers-and-multi-threading.

It's not relevant in this specific case, but I'd also add that you can exclude files from the client module graph entirely by naming them `*.server.ts/js` which is useful in a similar scenario when you have code with Node imports that aren't polyfilled on the client.
