### ISSUE TITLE
Tailwind class with image url as arbitrary value breaks the server

### ISSUE THREAD

**Issue by andrecasal** [remix-run/remix#5924]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. `npx create-remix@latest``
2. [Install tailwind](https://tailwindcss.com/docs/guides/remix)
3. Adding `// bg-[url('${icon}')]` to _index.tsx, even if inside comments, results in an error only recoverable by deleting the "build" and ".cache" folders and restarting the server.

[StackBlitz](https://stackblitz.com/edit/remix-run-remix-ktnytv?file=app/routes/_index.tsx)

### Expected Behavior

Server to continue running

### Actual Behavior

The server breaks with this error:
```log
✘ [ERROR] [plugin css-file] Build failed with 1 error:
app/tailwind.css:465:24: ERROR: Could not resolve "${icon}"

    app/root.tsx:10:23:
      10 │ import stylesheet from "~/tailwind.css";
         ╵                        ~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/plugins/cssFilePlugin.js:65:12:
      65 │       build.onLoad({
         ╵             ~~~~~~

    at setup (/Users/andrecasal/Developer/Apps/tailwind-deeply-nested-template-string-bug-reproduction/node_modules/@remix-run/dev/dist/compiler/plugins/cssFilePlugin.js:65:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handlePlugins (/Users/andrecasal/Developer/Apps/tailwind-deeply-nested-template-string-bug-reproduction/node_modules/esbuild/lib/main.js:1318:9)


Build failed with 1 error:
app/root.tsx:10:23: ERROR: [plugin: css-file] Build failed with 1 error:
app/tailwind.css:465:24: ERROR: Could not resolve "${icon}"
```

**Comment by markdalgleish** [comment]
Thanks for the bug report. I was able to reproduce this locally too.

This seems to be caused by the fact that Tailwind's JIT doesn't clean up unused classes after they've been generated. This means that if you create a class referencing an invalid URL (like your `url('${icon}')` example which is invalid CSS), the invalid URL will remain in the generated CSS until Tailwind is restarted. Unfortunately there's no way for us to work around this within Remix.

Here's a related issue on the Tailwind repo: https://github.com/tailwindlabs/tailwindcss/issues/4098. You may want to follow up with them about this particular scenario. I can imagine that Tailwind might need to use a different strategy when it comes to classes that reference URLs.

**Comment by markdalgleish** [comment]
As a side note, if you hadn't already figured this out, to get images to work with Tailwind you need to write root-relative paths like this: `bg-[url('~/images/logo.svg')]`.

**Comment by andrecasal** [comment]
Hey @markdalgleish 👋 Thanks for the feedback!

> As a side note, if you hadn't already figured this out, to get images to work with Tailwind in Remix you need to write root-relative paths like this: `bg-[url('~/images/logo.svg')]`.

I'm not a fan of hardcoding the image URLs in there, so I'm going with:
```tsx
<input style={icon ? { backgroundImage: `url(${icon})` } : undefined} />
```

I didn't quite get why `url('${icon}')` is invalid CSS 🤔

**Comment by kiliman** [comment]
Because Tailwind JIT is generating the CSS at build/save time, not at runtime. It's not evaluating the JavaScript. If you look at this example, Tailwind is simply looking for tokens in the input file. Here, it doesn't even check to see if it's inside comments. It's just looking for valid selector tokens. So the CSS is generated with invalid syntax, and the esbuild bundler is throwing an error.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/47168/228881722-928167e2-b170-4355-965e-32249b9d7fe8.png">

https://play.tailwindcss.com/rkmPIc4AVU
