### ISSUE TITLE
v1.14.3 to v1.15.0 Nested Layouts without Nested URLs issue

### ISSUE THREAD

**Issue by paul-phan** [remix-run/remix#5982]
### What version of Remix are you using?

v1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I'm using the `pathless` route feature to load different layouts for my route.
![](https://ucarecdn.com/3d1690b1-09db-4d52-878d-2140c124fae5/Screenshot20230402at111014.png)

### Expected Behavior

In `v1.14.3` and the `v2_routeConvention` flag is turned on, as you can see in the screenshot.
- The `_default/index.tsx` file contains the Tailwind CSS styling layout, and any route put in `_default` will load tailwind only.
- The `_polaris/index.tsx` file containing Polaris CSS styling layout and different loader logic, and any route putting in `_polaris` will load Polaris only.
- I put the index route in: `_polaris/_index/route.tsx`; then, by default, the index page will use Polaris style.

### Actual Behavior

It worked fine in `v1.14.3` but broke when I tried to upgrade to `v1.15.0`.

**Comment by paul-phan** [comment]
I also created a simple sample of my use case with Remix `v2_routeConvention` here: `[https://github.com/paul-phan/remix-1.15.0-test](https://github.com/paul-phan/remix-1.15.0-test)`.
It will work in `v1.14.3` but fail with `v1.15.0`

**Comment by frontendphil** [comment]
I will weigh in here because I assume the issue I'm seeing might be related. 

Here is a snapshot of how our routes are defined. We also have the `v2` convention turned on.

![CleanShot 2023-04-03 at 20 17 58](https://user-images.githubusercontent.com/187786/229593586-031f840e-2422-4e5e-8a2b-8e51efe24755.png)

In `1.14.3` this resulted in the following routes:

```tsx
<Routes>
  <Route file="root.tsx">
    <Route path=":tenantKey" file="routes/$tenantKey/index.tsx">
      <Route index file="routes/$tenantKey/_index/index.ts" />
      <Route path="matters.ics" file="routes/$tenantKey/matters[.ics]/route.ts" />
      <Route path="matters/:matterId" file="routes/$tenantKey/matters/$matterId/route.tsx" />
      <Route path="matters" index file="routes/$tenantKey/matters/_index/index.tsx" />
      <Route path="matters" file="routes/$tenantKey/matters/_overview/index.tsx">
        <Route path="all" file="routes/$tenantKey/matters/_overview/all/route.tsx" />
        <Route path="archive" file="routes/$tenantKey/matters/_overview/archive/route.tsx" />
        <Route path="by-due-date" file="routes/$tenantKey/matters/_overview/by-due-date/route.tsx" />
      </Route>
      <Route path="matters/new" file="routes/$tenantKey/matters/new/route.tsx" />
    </Route>
    <Route file="routes/_auth/index.tsx">
      <Route index file="routes/_auth/_index/index.tsx" />
      <Route path="sign-up" index file="routes/_auth/sign-up/_index/index.tsx" />
      <Route path="sign-up/verify" file="routes/_auth/sign-up/verify/route.tsx" />
      <Route path="sign-up/:registrationId/:verificationCode" file="routes/_auth/sign-up/$registrationId/$verificationCode/route.ts" />
      <Route path="sign-up/:registrationId" index file="routes/_auth/sign-up/$registrationId/_index/index.ts" />
      <Route path="sign-up/:registrationId/company-name" file="routes/_auth/sign-up/$registrationId/company-name/route.tsx" />
      <Route path="sign-up/:registrationId/your-account" file="routes/_auth/sign-up/$registrationId/your-account/route.tsx" />
      <Route path="sign-up/invitation/verify" file="routes/_auth/sign-up/invitation/verify/route.tsx" />
      <Route path="sign-up/invitation/:invitationId/:verificationCode" file="routes/_auth/sign-up/invitation/$invitationId/$verificationCode/route.ts" />
      <Route path="sign-up/invitation/:invitationId" index file="routes/_auth/sign-up/invitation/$invitationId/_index/index.ts" />
      <Route path="sign-up/invitation/:invitationId/your-account" file="routes/_auth/sign-up/invitation/$invitationId/your-account/route.tsx" />
    </Route>
    <Route path="healthcheck" file="routes/healthcheck/route.tsx" />
  </Route>
</Routes>
```

After the upgrade to `1.15.0` we only get this:

```tsx
<Routes>
  <Route file="root.tsx">
    <Route path="healthcheck" file="routes/healthcheck/route.tsx" />
    <Route path=":tenantKey" file="routes/$tenantKey/index.tsx" />
    <Route file="routes/_auth/index.tsx" />
  </Route>
</Routes>
```

I feel like I've missed a memo :) I've reread the docs, and it now seems like routes can be nested only one level deep. Is that correct?

**Comment by arielvieira** [comment]
@frontendphil I was having the same issue you are after upgrading to `v1.15.0` so I went looking it in the docs and announcements and found this. `Route nesting is now created by dots (.) in file names instead of folder nesting` 

For what I understood it seems like in `v2_routeConvention` you no longer can create nested routes by folders, the routes should be all flat and if you need a nested route you should use the `.` in the file name so for example in your `sign-up/invitation/:invitationId/your-account` ruoute, should instead of
```
routes/
|__ _auth
   |__ sign-up
       |__ invitation
          |__ $invitationId
              |__ your-account
                  |__ route.tsx
```
you would be required to do have a folder named `_auth.sign-up.invitation.$invitationId.your-account` and have a `route.tsx` inside
```
routes
|__ routes._auth.sign-up.invitation.$invitationId.$verificationCode
    |__ route.ts
|__ routes._auth.sign-up.invitation.$invitationId.your-account
    |__ route.tsx
...
```

I'm not sure if I like this change, it will make hard to have a folder for resources that can be used for [Full Stack Components](https://www.epicweb.dev/full-stack-components), fortunately I could bypass this if a custom script for [remix config routes](https://remix.run/docs/en/main/file-conventions/remix-config#routes) that would automatically generated my nested resources routes from that folder.

https://remix.run/docs/en/main/pages/v2
![image](https://user-images.githubusercontent.com/17505779/229655178-93190ff1-75ee-4555-b7a6-a850f4bb5e61.png)

**Comment by paul-phan** [comment]
Thanks, @arielvieira; it seems like I missed that.

**Comment by frontendphil** [comment]
Thanks, @arielvieira, for pointing that out. It seems like I've missed that very small but very impactful bullet point. I agree that I don't particularly like this. Would you happen to know anything about the reason for that decision? This flat style seems fine for a blog with five pages, but we're building a product, and (as business people like to say) that doesn't scale.

**Comment by jonschlinkert** [comment]
> fortunately I could bypass this if a custom script for [remix config routes](https://remix.run/docs/en/main/file-conventions/remix-config#routes) that would automatically generated my nested resources routes from that folder.

@arielvieira I know it's been a while since you posted this, but (assuming I understand correctly what you were saying) do you happen to have an example of how you were able to get nested folders working with v2, by any chance? I unfortunately won't be able to use v2 if folders can't be used for routes. Our app would have 100s of files in one folder, and the route file names would be 5 or 6 segments long and difficult to read. 

> Would you happen to know anything about the reason for that decision? This flat style seems fine for a blog with five pages, but we're building a product, and (as business people like to say) that doesn't scale.

I 100% agree. This was my first reaction: "Is Remix only targeting small blogs and apps?"

**Comment by kiliman** [comment]
I commented on another issue. `remix-flat-routes` also has a migration tool that will let you keep your existing folder structure. 

![image](https://github.com/remix-run/remix/assets/47168/9b92796f-cb8d-4712-8179-cd5b279cf38a)

**Comment by jonschlinkert** [comment]
@kiliman thanks! I'll check it out
