### ISSUE TITLE
ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by cjoecker** [remix-run/remix#5990]
### What version of Remix are you using?

1.15

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Add a file to the routes folder called `login.test.tsx`
2. Add `ignoredRouteFiles: ["**/.*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],` to the `remix.config.ts`
3. Write unit tests on that file
4. Run remix on dev mode
5. See error `ReferenceError: describe is not defined`

### Expected Behavior

Remix should ignore test files on the routes folder

### Actual Behavior

Since version 1.15, remix is not ignoring test files on routes folder.

**Comment by akamfoad** [comment]
No worries @cjoecker , but I'm afraid that wont work, remix has changed the library they use for matching the files to use minimatch, they generate a Regex from each one of the `ignoredRouteFiles` array items. See [`minimatch - Usage`](https://github.com/isaacs/minimatch#usage) to understand how this work. But the issue here is that, remix uses a function from minimatch called `makeRe` which creates JS regex and escapes all symbols, I tried it in node repl and this was the result

```js
> const mini = require("minimatch")
undefined

> mini.makeRe("**/*.test.(js,jsx,ts,tsx)")
/^(?:(?:(?!(?:\/|^)\.).)*?\/(?!\.)(?=.)[^/]*?\.test\.\(js,jsx,ts,tsx\))$/

> mini.makeRe("**/*.test.(js,jsx,ts,tsx)").test("routes/index.test.jsx")
false
```

As you can see this will never match your routes anyway. I understand this is a breaking change for a minor release, but for your case to work you can just use `*` instead of file extensions to ignore the test files

```js
ignoredRouteFiles: ["**/.*", "**/*.css", "**/*.test.*"]
```

**Comment by cjoecker** [comment]
@akamfoad that worked, thanks!
