### ISSUE TITLE
More clear documentation on the different ways of routing on routing documentation

### ISSUE THREAD

**Issue by paulieDOTjs** [remix-run/remix#6066]
On the https://remix.run/docs/en/1.15.0/file-conventions/routes-files#dynamic-route-parameters page all the documentation relates to V1 of handing routes and it does not include on this page that this documentation will not work when using the 
```js
 future: {  v2_routeConvention: true, },
```
flag in the remix.config.js which is on by default when starting a new remix project. That information is on the https://remix.run/docs/en/1.15.0/pages/v2 page but it is not immediately apparent when simply looking at the page related to routing.

**Comment by MichaelDeBoey** [comment]
Going to close this as we do have a notice at the top of the page about the v2 guide

<img width="822" src="https://user-images.githubusercontent.com/6643991/236632418-c08a85fe-72da-46c7-b958-9d84f2e6703a.png">

**Comment by nlindroos** [comment]
A related side note: Since `v2_routeConvention` is on by default, all new users doing the [short tutorial](https://remix.run/docs/en/1.15.0/tutorials/blog) will run into routing issues.

The new routing convention seems to lead to Issues with both the folder approach as well as the dot limiter approach (at least in that tutorial), I would hence reconsider enabling this by default until most issues are ironed out.
