### ISSUE TITLE
Tsconfig had .ts and .tsx instead of js/jsx on a new remix app

### ISSUE THREAD

**Issue by LupuC** [remix-run/remix#6152]
### What version of Remix are you using?

Latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I just ran `npx create-remix@latest`, selected a basic app with JavaScript.

### Expected Behavior

tsconfig.json
`"include": ["**/*.js", "**/*.jsx"],`

### Actual Behavior

tsconfig.json
`"include": ["remix.env.d.ts", "**/*.ts", "**/*.tsx"],`

**Comment by brophdawg11** [comment]
This is unfortunately the way it's expected to work today because some templates (such as the Remix Stacks) have TS code outside the `routes/` folder and we [don't touch that in the TS->JS conversion](https://github.com/remix-run/remix/blob/main/decisions/0008-only-support-js-conversion-for-app-code.md) so the `tsconfig.json` is left around so it can apply to that code _if it exists_.  

However, none of that exists for the simple remix app server template, so when choosing Javascript, `tsconfig.json` as well as the `typescript`/`@types/*` `devDependencies` are just overhead currently.  We are planning to do a pretty big update to `create-remix` in v2 and I hope we can alleviate this overhead for the simple remix app server + JS scenario.

**Comment by markdalgleish** [comment]
There's a rewrite of `create-remix` shipping soon with Remix v2 which removes the option for automatic TS to JS conversion.

You can have a look at the new templates in the `dev` branch: https://github.com/remix-run/remix/tree/dev/templates.

The JS starter template is going to be a standalone template without any of the TypeScript boilerplate: https://github.com/remix-run/remix/tree/dev/templates/remix-javascript.
