### ISSUE TITLE
CSS Side-Effect Imports not working anymore with Cloudscape

### ISSUE THREAD

**Issue by joejemmely** [remix-run/remix#6314]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [x] Yes

### Steps to Reproduce

1. Pull https://github.com/joejemmely/remix-cloudscape
2. Run `npm run dev`

### Expected Behavior

Styles should be extracted and applied

### Actual Behavior

Styles are not extracted and applied. It used to work with `unstable_cssSideEffectImports` on 1.14.0

**Comment by markdalgleish** [comment]
This looks like it's because Cloudscape contains files using the `.css.js` extension which Remix mistakenly thinks are [Vanilla Extract](https://vanilla-extract.style) files.

Similar to how Tailwind works in Remix, we might want to think about detecting the presence of the `@vanilla-extract/css` package before attempting to process these files. This still wouldn't handle the case where you want to use non-Vanilla-Extract `.css.js` files _and_ Vanilla Extract at the same time, but that's much more of an edge case.

**Comment by joejemmely** [comment]
Thanks for the prompt response.

> we might want to think about detecting the presence of the @vanilla-extract/css package before attempting to process these files

Related to this, I noticed that if `name` is missing in the package.json, the project will fail to build with `Couldn't find parent package.json with a name field from XXX`, the error is thrown in `vanilla-extract-plugin`, even though it's not installed. And even if `vanilla-extract-plugin` was installed, most remix apps won't have a name defined in the package.json. Is the `name` necessary for `vanilla-extract` to work properly?

**Comment by markdalgleish** [comment]
Thanks for raising this issue! This should be fixed in the next release.

**Comment by joejemmely** [comment]
I gave the fix a try but it didn't work as expected. `@remix-run/dev` takes a dependency on `@vanilla-extract/integration` so there currently isn't a nice way to not have any of the `vanilla-extract` dependencies.

**Comment by markdalgleish** [comment]
@joejemmely Thanks for the update. You're right, I missed that `@vanilla-extract/css` can still be requirable from your app since Remix depends on `@vanilla-extract/integration` which in turn depends on `@vanilla-extract/css`. I've just merged a PR that updates the detection logic so we now look in your app's package.json to see whether you have a direct dependency on it.

**Comment by markdalgleish** [comment]
@joejemmely Could you try again with the latest nightly?

**Comment by joejemmely** [comment]
Works like a charm 🥳 Thanks for your help
