### ISSUE TITLE
v1.16.0 can't handle custom @import with @layers in separate files in tailwind.css 

### ISSUE THREAD

**Issue by kenn** [remix-run/remix#6315]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Update tailwind setting [according to the release note](https://github.com/remix-run/remix/releases/tag/remix@1.16.0)
- Now, Remix cannot process [custom @imports as recommended by Tailwind](https://tailwindcss.com/docs/functions-and-directives#config)

All `@import` must come to first, so can't use `@tailwind` directive — break them down to `@import`s  and insert custom [`@layer`s in between](https://tailwindcss.com/docs/functions-and-directives#layer) is the only way.

```css
@import 'tailwindcss/base';
@import './styles/base';
@import 'tailwindcss/components';
@import './styles/components';
@import 'tailwindcss/utilities';
@import './styles/utilities';
```

instead of 

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

and the error says @import is not at the beginning.

```bash
[1] 💿 Building...
[1] ▲ [WARNING] All "@import" rules must come first [invalid-@import]
[1] 
[1]     app/tailwind.css:624:0:
[1]       624 │ @import './styles/base';
[1]           ╵ ~~~~~~~
[1] 
[1]   This rule cannot come before an "@import" rule
[1] 
[1]     app/tailwind.css:8:0:
[1]       8 │ *,
[1]         ╵ ^
[1] 
[1] ▲ [WARNING] All "@import" rules must come first [invalid-@import]
[1] 
[1]     app/tailwind.css:1069:0:
[1]       1069 │ @import './styles/components';
[1]            ╵ ~~~~~~~
[1] 
[1]   This rule cannot come before an "@import" rule
[1] 
[1]     app/tailwind.css:8:0:
[1]       8 │ *,
[1]         ╵ ^
[1] 
```

### Expected Behavior

Remix should embrace tailwind's suggestions for @import order.

https://tailwindcss.com/docs/functions-and-directives

### Actual Behavior

@imports in `tailwind.css` are not handled first as expected.

**Comment by corydeppen** [comment]
I noticed the same errors until I installed the `postcss-import` package and added the `'postcss-import'` plugin to the `postcss.config.js` file based on the [build-time imports guidance](https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports) in the Tailwind docs.

**Comment by markdalgleish** [comment]
The import order warning you're seeing is coming from esbuild. This is because the Tailwind PostCSS plugin is replacing the Tailwind `@import` statements with its generated CSS, just like the `@tailwind` directives, but your custom `@import` statements are still being left in the code.

This means that the generated CSS being passed to esbuild from your example looks like this:

```css
*,
:before,
:after {
  ...
}
/* etc... */

@import './styles/base';

/* Tailwind Components CSS... */

@import './styles/components';

.text-lg {
  font-size: 1.125rem;
  line-height: 1.75rem;
}
/* etc... */

@import './styles/utilities';
```

esbuild throws away any `@import` statements that aren't at the top of the file and logs a warning, so in this case all CSS in `base.css`, `components.css` and `utilities.css` is being ignored.

There are 2 different ways to fix this.

1) As @corydeppen mentioned, you can use the [postcss-import](https://www.npmjs.com/package/postcss-import) plugin (after [setting up PostCSS in Remix](https://remix.run/docs/en/1.16.0/guides/styling#postcss)) so that imports are processed alongside Tailwind before the result is passed to esbuild.

2) Alternatively — and this is probably what I'd recommend — you should avoid using Tailwind's `@import` syntax since it's ultimately just another way of writing the `@tailwind` directives. The source maps even show that the source of `tailwindcss/base` is literally just `@tailwind base;`. Instead, you should write the `@tailwind` directives yourself so you can clearly see where the import statements are.

    In your example, I'd put `@tailwind base;` at the top of `styles/base.css`, `@tailwind components;` at the top of `styles/components.css`, and `@tailwind utilities;` at the top of `styles/utilities.css`. This way you still get the ordering you expect and you're still able to split your Tailwind setup into smaller files, and you get to do it without adding more PostCSS plugins to the mix.

I'm closing this issue since this isn't something we can fix internally in Remix, but I might look at adding a warning to the documentation to cover this scenario.
