### ISSUE TITLE
An error occurred setting appDirectory as the root directory

### ISSUE THREAD

**Issue by mitamac** [remix-run/remix#6533]
### What version of Remix are you using?

latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- pnpm dlx create-remix remix
- ![image](https://github.com/remix-run/remix/assets/56892264/1487968c-de38-4d91-8be1-cb8b31b432b9)
- Change the appDirectory in remix.config.js to the root directory
- ![image](https://github.com/remix-run/remix/assets/56892264/8005f267-122e-431a-836d-7fa39656581f)
- Modifying a routing file
- ![image](https://github.com/remix-run/remix/assets/56892264/a3ceb27f-9d9e-4885-a2f0-767abb43a086)

### Expected Behavior

This feature helps flat path of Remix application.
I think we need to add an ignoredWatchPaths parameter.

### Actual Behavior

Unnecessary folders were listened for while modifying files.

**Comment by brophdawg11** [comment]
This isn't really a bug as `appDirectory` is there to choose a different name for the `app` directory, but not really to use a directory above `build` and `public/build` since that would inherently cause rebuild loops.  If you wish to see this type of `ignoreWatchPaths` feature added you can open a Proposal following our [Open Development Process](https://remix.run/blog/open-development).
