### ISSUE TITLE
1.17.0 New simplified Serialize type is excessively deep and possibly infinite when using Prisma's JSON type

### ISSUE THREAD

**Issue by piotrkulpinski** [remix-run/remix#6605]
### What version of Remix are you using?

1.17.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

When you return data containing JSON values from Prisma, its type can get messed up during the serialisation process of `useLoaderData`.

Before, it returned `any`, but now it returns recursive `[x: string]: any` definitions, which causes errors whenever I try to do anything with the returned JSON values.

Type in loader (returned directly from Prisma):
<img width="292" alt="CleanShot 2023-06-14 at 13 08 22" src="https://github.com/remix-run/remix/assets/358412/bbc89174-0743-4a38-a173-783a3c0ad106">

Type in component (after using `const { collections } = useLoaderData<typeof loader>()`):
<img width="648" alt="CleanShot 2023-06-14 at 13 09 23" src="https://github.com/remix-run/remix/assets/358412/41353358-530e-45bb-8bde-6e716115b839">

### Expected Behavior

Return `any` just like before

### Actual Behavior

Returns nested `[x: string]: any` typings

**Comment by pcattori** [comment]
Fixed by https://github.com/remix-run/remix/pull/6582

**Comment by jaminday** [comment]
I've had the same errors accessing data in `useLoaderData` when using the Supabase Json type (Remix v1.17). I assume the underlying cause is the same as the Prisma Json issue.

@pcattori v1.17.1-pre.1 (as per #6582) so far seems to help remove the Typescript errors.

I'm curious, is Remix meant to retain custom types between the server and component? For example, here my server loader function returns an object with data property that has (Supabase) `Json` type:
![Screenshot 2023-06-15 at 10 41 00 am](https://github.com/remix-run/remix/assets/1966387/60488fa0-23ef-4791-b193-93ae2db9a5c8)

In the component, the data property is serialised into basic types and I have to recast it to `Json`:
![Screenshot 2023-06-15 at 10 41 37 am](https://github.com/remix-run/remix/assets/1966387/a3faf386-6f44-4b27-8a4a-bd4431f1d061)

However, I can't remember if Remix has always done this.

**Comment by pcattori** [comment]
@jaminday the way the types are defined as of #6582 should preserve types that are JSON serializable. If that's not the case, could you make a repro in a Typescript playground so I can take a look?

**Comment by jaminday** [comment]
@pcattori Sure, here's a barebones dummy example running remix v1.17.1-pre.1 which shows the types are not being preserved:

https://codesandbox.io/p/sandbox/modest-mirzakhani-rx7jhx

**Comment by pcattori** [comment]
Fixed in https://github.com/remix-run/remix/pull/6582 (which is not part of 1.17.1, our GH bot is wrong). Available on `nightly` if you want to try it out.

**Comment by jaminday** [comment]
Thanks - this works now in my codesandbox example and on my local dev server using the current nightly build. 

fwiw things seem to blow up again if the `remix-utils` package is installed (updated codesandbox here https://codesandbox.io/p/sandbox/modest-mirzakhani-rx7jhx), but maybe it's just incompatible with the nightly build as I had to use the `--force` flag to install.
