### ISSUE TITLE
Built-in Tailwind support didn't work

### ISSUE THREAD

**Issue by kayac-chang** [remix-run/remix#6745]
### What version of Remix are you using?

v1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- using the basic remix setup `npx create-remix@latest <project-dir>`
- follow the setup on https://remix.run/docs/en/1.18.1/guides/styling#tailwind-css exactly.

### Expected Behavior

`tailwind.css` should compile correctly.

### Actual Behavior

`tailwind.css` doesn't compile.

### etc

the `tailwind-test.ts` in the remix project doesn't test the `tailwind` flag, but only the `unstable_tailwind` flag.

**Comment by alexandremottet** [comment]
I can confirm this issue.

It was also working on the `^1.17.0` versions, but seems to be broken on `^1.18.1`

**Comment by DonKoko** [comment]
I am also on 1.18.1 and I have the same issue. Will test downgrading versions and put an update here.

**Comment by brophdawg11** [comment]
Per https://github.com/remix-run/remix/issues/6745#issuecomment-1621739544, I think this is likely due to mismatched `@remix-run/*` versions.  I was unable to reproduce on a fresh `npx create-remix` and following the instructions in https://remix.run/docs/en/1.18.1/guides/styling#tailwind-css.

Please confirm all of your remix dependencies are synced up and that you don't have stale versions in `node_modules` (you can verify via `npm ls [package]`).

I'm going to close this out since I can't reproduce but if you can provide a simple reproduction, please reopen this issue.  

> the tailwind-test.ts in the remix project doesn't test the tailwind flag, but only the unstable_tailwind flag.

Both are tested:
* https://github.com/remix-run/remix/blob/main/integration/tailwind-test.ts#L47
* https://github.com/remix-run/remix/blob/main/integration/tailwind-test.ts#L340

**Comment by DonKoko** [comment]
I think you are correct. Everything works well now after a fresh install. Thanks for looking into it.

**Comment by kristjanmik** [comment]
This issue happened on my production build (CI) a couple of days ago, and I have not been able to reproduce it since. Import directives are respected and not imported from tailwind, so no styles are being compiled. I will try to hunt it down and post a way to reproduce it, but something flaky is going on with the new tailwind implementation in V2.

**Comment by kristjanmik** [comment]
The root of the issue is that installing tailwindcss as a devDependency silently breaks the built-in tailwind process when running with a production NODE_ENV flag. This does not happen locally, as most people are running with NODE_ENV=development. This must be documented well or throw a warning/error during the built-in build-time rather than swallowing it.

**Comment by kiliman** [comment]
Hmm... tailwind should be a dev dependency since it generates a static CSS file.

What is your production build process?

**Comment by brophdawg11** [comment]
> The root of the issue is that installing tailwindcss as a devDependency silently breaks the built-in tailwind process when running with a production NODE_ENV flag

If this is happening for your setup, could you provide a minimal reproduction?  Tailwind works correctly for me following these steps:

* `npx create-remix@latest`
* Follow the setup in https://remix.run/docs/en/1.18.1/guides/styling#tailwind-css, which includes installing `tailwindcss` as a `devDependency`
* `NODE_ENV=production npm run build`
*  `NODE_ENV=production npm run start`
