### ISSUE TITLE
Initial URL (undefined) does not match URL at time of hydration (/)

### ISSUE THREAD

**Issue by joshmedeski** [remix-run/remix#6763]
### What version of Remix are you using?

v0.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Note: I had a hard time recreating this issue in a simplified sample project.

My project is a pnpm monorepo running a remix app using the remix server app.

### Expected Behavior

`remix dev` to work successfully on Windows WSL environment.

### Actual Behavior

When the `remix dev` script is running I get the following error in console, and the page endlessly reloads on Windows via WSL.

```
Initial URL (undefined) does not match URL at time of hydration (/)
```

If I visit a page that isn't the homepage, it appears to be working.

What's causing this? I'm not sure why the initial URL on the homepage is coming back as undefined but it's expecting `/`.

I generated the entry.client and entry.server files from the `remix resolve` command and am using React v17 for my project.

**Comment by delexw** [comment]
Same here. I have to explicitly set `global.__remixContext.url = '/xxx'` in `entry.client.tsx` to get it passed. Not sure any better way

**Comment by brophdawg11** [comment]
This would be due to a stale `@remix-run/server-runtime` package (<= 1.18.0) and a current `@remix-run/react` package (>= 1.18.1), you need to have all of your Remix dependencies using the same version so they are synced up.

I'm pretty sure this is something going on with your `pnpm` workspace.  Please install the latest version of `remix` and all `@remix-run/*` dependencies in your `package.json` and clear any `node_modules` directories and/or `pnpm` caches and try again.

If that does not work - please reopen this issue with a simple `pnpm` reproduction repo so we can dig in further.

**Comment by joshmedeski** [comment]
Thanks, my server-runtime was out of date and the issue is resolved.

**Comment by delexw** [comment]
@brophdawg11 Dependabot doesn't pick up the minor version upgrade for `@remix-run/server-runtime`. I looked at the `package-lock.json`. The dependency version is `"@remix-run/server-runtime": "1.17.1",`. Should expect `^1.17.1`?

**Comment by brophdawg11** [comment]
It needs to be whatever the rest of your Remix deps are using.  I prefer to avoid loose versions such as `^x.y.z` since it makes it ambiguous.
