### ISSUE TITLE
`ErrorBoundary` didn't catch `TypeError` on SSR render

### ISSUE THREAD

**Issue by diajelovic** [remix-run/remix#6892]
### What version of Remix are you using?

1.19.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

in dev mode

```ts
export const loader = async ({ request }: LoaderArgs) => {
  return {}
}

export default function Page() {
  const data = useLoaderData<typeof loader>();

  return <div>{data.param.anoherParam}</div>;
}
```

### Expected Behavior

render result of `ErrorBoundary`  function in `root.tsx`

### Actual Behavior

Infinite loading

Error in server logs

```
TypeError: Cannot read properties of undefined (reading 'anoherParam')
```

**Comment by diajelovic** [comment]
Yes, i've found way to reproduce this error https://stackblitz.com/edit/remix-run-remix-lzrkak?file=app%2Fentry.server.tsx

it happen when i have `entry.server.tsx` written to use with `defer`

https://remix.run/docs/en/1.19.0/guides/streaming#enable-react-18-streaming

**Comment by brophdawg11** [comment]
Ah - that's only doing half of the work (the happy path).  The docs try to hint at this (but could probably be more explicit - PRs welcome!): 

> Here's a simple (and incomplete) version of that

If you expand the **For a more complete example, expand this** section, you'll see that you need to also include `onShellError`/`onError` callbacks to `renderToPipeableStream` that `reject` the promise - this is why you're application is hanging, since the promise never resolves or rejects.

I would recommend grabbing the approach used in `entry.server.tsx` from a brand new `npx create-remix` and using that in your app since it's a complete solution.
