### ISSUE TITLE
WebSocket connection fails repeatedly when running `npm run dev` in fresh Architect project

### ISSUE THREAD

**Issue by lpsinger** [remix-run/remix#6933]
### What version of Remix are you using?

1.19.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new basic Architect project using create-remix.
2. Launch using `npm run dev`.
3. Open a web browser and show the JavaScript console.

### Expected Behavior

No errors

### Actual Behavior

This message is repeated over and over again:

```
[Error] WebSocket connection to 'ws://localhost:8002/socket' failed: Could not connect to the server.
```

<img width="969" alt="Screenshot 2023-07-22 at 11 00 25" src="https://github.com/remix-run/remix/assets/728407/55086254-908a-4486-917e-da733034df93">

**Comment by bugamehmet** [comment]
your url localhost:3333 and  the error message you provided indicates that the WebSocket connection to 'ws://localhost:8002/socket' failed.heck WebSocket Server: Ensure that the WebSocket server is running and listening on the specified address (localhost) and port (8002). Make sure there are no issues with the server's setup or configuration.
Change your localhost address or the code you are running the server from.

**Comment by lpsinger** [comment]
This worked in remix 1.18.1, and broke in 1.19.0.

**Comment by bugamehmet** [comment]
The provided code represents a configuration object with a set property that contains an env function.

The code appears to be used for setting environment variables in the project. However, there is an important detail to note. Since there is a return statement, the second part of the function, the part after the return { testing: { NODE_ENV: "development" } }; line, will never be executed.

Therefore, the working code would be as follows:
set: {
  env() {
    // `arc sandbox` does not automatically pass `NODE_ENV` from its
    // environment to the application.
    return { testing: { NODE_ENV: "development" } };
  },
},
the second part found in this function, namely the following part:
const passthruKeys = /^NODE_ENV$|^REMIX_DEV_/;
return {
  testing: Object.fromEntries(
    Object.entries(process.env).filter(([key]) => passthruKeys.test(key))
  ),
};
If return { testing: { NODE_ENV: "development" } }; line is executed, the rest of the code will not be executed at all.

**Comment by g-curtis-edacious** [comment]
@bugamehmet 

I have a use case where I'm using Ambassador locally to map traffic on http://localhost:80 to my remix service running in a pod on port `3000` (dev server is running `3001`). The mapping is basically:

```
ws://localhost:80/socket -> service:3001/socket
```

In `remix@1.17.1`, I simply had to pass the port to the `LiveReload` component to get it to work. For example:

```
<LiveReload port={80} />
```

In `remix@1.19.1` with `v2_dev=false`, I have to set an env variable instead. For example:

```
REMIX_DEV_ORIGIN="http://localhost"
```

In `remix@1.19.1` with `v2_dev=true`, this breaks and there doesn't seem to be a way for me to configure the web socket to request a different port than the one the dev server is running on.

I want to request `ws://localhost:80/socket`, but have the dev server inside the container running on port `3001`.

Any recommendations? Let me know if I should create a different issue. Thanks!
