### ISSUE TITLE
dev server v2 tlsKey and tlsCert options don't allow `~/`

### ISSUE THREAD

**Issue by mikeybinns** [remix-run/remix#6961]
### What version of Remix are you using?

1.19.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Set up a new express project (might be in others, but this is what I've tested it in)
Follow the instructions here to add an SSL to your project:
https://remix.run/docs/en/main/other-api/dev-v2#how-to-set-up-local-https
Be sure to add your key in the user home dir

Run the following command:
`remix dev --tls-key=~/key.pem --tls-cert=~/cert.pem -c "node ./server.js"`
OR
Set the following value in remix.config.js
```js
v2_dev: {
	tlsCert: `~/cert.pem`,
	tlsKey: `~/key.pem`,
},
```

### Expected Behavior

Remix finds the file in the user home dir

### Actual Behavior

It tries to find the files in `PROJECT_CWD/~/` directory and throws this error:
```
Error: ENOENT: no such file or directory, open 'PROJECT_CWD/~/.certs/cert.pem'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at Object.serve (PROJECT_CWD/node_modules/@remix-run/dev/dist/devServer_unstable/index.js:129:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.dev (PROJECT_CWD/node_modules/@remix-run/dev/dist/cli/commands.js:236:3)
    at async Object.run (PROJECT_CWD/node_modules/@remix-run/dev/dist/cli/run.js:515:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'PROJECT_CWD/~/.certs/cert.pem'
}
```

**Comment by mikeybinns** [comment]
Note: this is important because if I make an SSL for `localhost`, it shouldn't be kept in the project as it will apply to multiple sites on localhost.

Workaround:
```js
// remix.config.js
const os = require("node:os");
const userHomeDir = os.homedir();

module.exports = {
  future: {
    v2_dev: {
      tlsCert: `${userHomeDir}/.certs/cert.pem`,
      tlsKey: `${userHomeDir}/.certs/key.pem`,
    },
  },
};

**Comment by pcattori** [comment]
Tilde expansion is a command line feature, so `remix dev --tls-key=~/key.pem --tls-cert=~/cert.pem -c "node ./server.js"` should work if you run it directly on your terminal, but not if you use it as a `package.json` script.

We don't want to change the semantics here because literal `~` is a valid filename/directory and it could also create confusion with `tsconfig` path aliases where `~` is commonly used to refer to the app root directory.

Within `remix.config.js` you can use `os.homedir()` as mentioned above or provide an absolute or relative path without relying on tilde expansion.
