### ISSUE TITLE
HeaderFunction does not affect non-SSR loaders

### ISSUE THREAD

**Issue by mihhail-lapushkin** [remix-run/remix#7017]
### What version of Remix are you using?

1.19.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Add a `headers` function to your route e.g:
```
export const headers: HeadersFunction = () => ({
  'Cache-Control': 'no-cache',
});
```

### Expected Behavior

1. Headers are present in the SSR response.
2. Headers are present in the non-SSR, JSON response.

### Actual Behavior

Headers are **not** present in the non-SSR, JSON response.

**Comment by brophdawg11** [comment]
This is expected behavior.  Since each loader returns a `Response` - data requests just use the headers on that response directly because each request only runs one loader.  

The `headers` function is only for document requests when _multiple_ loaders run and return _multiple_ responses.  Remix cannot intelligently merge the headers from those responses so we provide the `headers` function allowing you to choose how to combine all of the headers.

If you want a data response to have this header, just add it to the response directly:

```js
export function loader() {
  return json(data, { headers: { 'Cache-Control': 'no-cache' } });
}
```

**Comment by mihhail-lapushkin** [comment]
> This is expected behavior. Since each loader returns a `Response` - data requests just use the headers on that response directly because each request only runs one loader.
> 
> The `headers` function is only for document requests when _multiple_ loaders run and return _multiple_ responses. Remix cannot intelligently merge the headers from those responses so we provide the `headers` function allowing you to choose how to combine all of the headers.
> 
> If you want a data response to have this header, just add it to the response directly:
> 
> ```js
> export function loader() {
>   return json(data, { headers: { 'Cache-Control': 'no-cache' } });
> }
> ```

Ahh, right!

My confusion came from defining this function in the parent route and seeing it propagate to child routes. In my head, this immediately became a way to define default headers for a subtree of routes. And I was surprised why it worked for SSR and not for data requests.

Thanks for the clarification!
