### ISSUE TITLE
ESBuild metafiles placed in the wrong path for cloudflare pages project

### ISSUE THREAD

**Issue by pmbanugo** [remix-run/remix#7129]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

In a remix project using the cloudflare pages setup, the esbuild metafiles are placed in the *functions* directory instead of the *public/build* directory.  According to 1.19 release

```
For bundle analysis, the esbuild metafiles are now written to your server build directory (build/ by default) 
```

I guess it should follow the default because I didn't change any config and got this after upgrading.

![Screenshot 2023-08-10 at 17 26 23](https://github.com/remix-run/remix/assets/4036118/e1b9b493-7b40-4748-bb1b-e3afbb7230a7)

### Expected Behavior

Put the esbuild manifest in the `/build` folder

### Actual Behavior

Put the manifest in the `functions` directory

**Comment by pcattori** [comment]
`public/build/` is the _browser build_ directory, whereas `build/` is the default server build directory. However, the [CloudFlare Pages template configures the server build directory to be `functions/`](https://github.com/remix-run/remix/blob/main/templates/cloudflare-pages/remix.config.js#L6), so this is expected behavior.

Putting the metafiles into the browser build directory would make those files accessible via HTTP to _anyone_, which could be a security risk since you would be informing hackers of your dependencies. That's why Remix does not put the metafiles into the browser build directory.

**Comment by pmbanugo** [comment]
But those are not required to be checked in, or is it the recommendation? Perhaps adding it to the gitignore template?

**Comment by pcattori** [comment]
Correct, the templates should be updated to include them in the `.gitignore`

**Comment by MichaelDeBoey** [comment]
@pcattori #7177 will take care of that
