### ISSUE TITLE
in aws architect app, route returns loader json when accessed directly and returns HTML when navigated through a link

### ISSUE THREAD

**Issue by dagda1** [remix-run/remix#7160]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I have a remix site which uses [aws architect](https://arc.codes/docs/en/get-started/quickstart) problem that I don't understand.

This only happens when when deployed to AWS.

I have the following route `posts._index.tsx`

![route](https://github.com/remix-run/remix/assets/118328/1b751e46-b67f-426e-acc2-e627e668f876)

```ts
export const loader: LoaderFunction = async () => {
  return getPosts();
};

export default function PostsHome() {
  const posts = useLoaderData<PostData[]>();

  return <Posts posts={posts} />;
}
```

If I go directly to the [route](https://staging.frontendrescue.com/posts), it return `application/json` which is the JSON returned from the loader function.

![json](https://github.com/remix-run/remix/assets/118328/d10c48b3-6e94-4de9-84fd-589c13762514)

But If I navigate there by clicking the `blog` link on the [home page](https://staging.frontendrescue.com), it returns `text/html`.

![json](https://github.com/remix-run/remix/assets/118328/eb6ea5d9-ee8b-45e4-b41e-f1e037f9560b)

Am I doing something wrong?

### Expected Behavior

It should return `text/html` everytime

### Actual Behavior

The route returns `text/json` when accessed via the full url.

**Comment by roblox34** [comment]
Hi there,

Thanks for reaching out to me. Based on your email, it seems like you are having an issue with your Remix site when it is deployed to AWS. Regarding the problem you described, it's hard to tell what's causing the issue. However, it could be related to the routing mechanism or how the content is being served.

In order to get a better idea of what might be the issue, I would suggest checking the routing configuration, as well as the content-type headers being served. Please let me know if you find anything that could be causing the issue.

Also, to answer your question, I'm using Remix version 1.15.0, and all of my dependencies and dev-dependencies are using the same version.

Thanks, and I hope this helps!

Best regards,
mike

**Comment by brophdawg11** [comment]
This was raised in Discord the other week and was due to AWS Cloudfront's default configuration which does not forward query parameters to the origin server.  You need to configure it to send them along so Remix receives the `?_data` query string parameter.

See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html and click on `Query string forwarding and caching` (for some reason hash links don't seem to land on the right spot on that page 😕 .
