### ISSUE TITLE
prom-client not working as expected if only used in an action

### ISSUE THREAD

**Issue by tkovis** [remix-run/remix#7200]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I have a bug repro repo in:
https://github.com/tkovis/remix-bug-repro

I made it by:
1. initializing a new app based on the blues stack
2. made modules for gathering metric https://github.com/tkovis/remix-bug-repro/tree/main/app/metrics
3. used them in an action to track sign ins https://github.com/tkovis/remix-bug-repro/blob/main/app/routes/login.tsx#L57
4. imported two of them in server.ts and made a reference to one of them https://github.com/tkovis/remix-bug-repro/blob/main/server.ts#L29
5. started the server with `npm run dev`
6. went to `http://localhost:3001/metrics2` and observed that there is only metrics from 1 of the 4 counters (the one that is referenced in server.ts)
```
# HELP sign_in_3_total A test to see if counters show up in metrics
# TYPE sign_in_3_total counter
sign_in_3_total 2
... other irrelevant metrics
```

Adding references to other counters in server.ts fixes them too

### Expected Behavior

All 4 counters should work without needing to import and reference them in `server.ts`.

This might very well be related to prom-client or documented behaviour but I am unable to find any or figure out why the counters work as they do. Nevertheless this issue could be helpful to others trying to set up custom metrics using prom-client with remix

### Actual Behavior

A counter that is only used in an action won't show up in the http://localhost:3001/metrics2

**Comment by brophdawg11** [comment]
I'm not familiar with `prom-client` but my guess is that this has something to do with that since at the end of the day Remix is just an HTTP handler running on a server.  Can you try to create a smaller minimal reproduction that doesn't include the full blue stack, docker, etc?  My hope is that this will make your debugging easier and hopefully allow you to track down the issue to prom-client.

```
npx create-remix --template https://github.com/remix-run/remix/tree/main/templates/express
```

But at the least it will give us a smaller reproduction to triage with.
