### ISSUE TITLE
Creating a new Remix run project 

### ISSUE THREAD

**Issue by dantman** [remix-run/remix#7216]
### What version of Remix are you using?

latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Run `npm init remix` or `npx create-remix@latest`
2. When asked "What type of app do you want to create?" answer "Just the basics"
3. When asked "Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to 
change deployment targets." select "Vercel" in the list of "Remix App Server, Express Server, Architect, Fly.io, Netlify, Vercel, Cloudflare Pages, Cloudflare Workers, Deno" options
4. Select TypeScript
5. Answer yes to "Do you want me to run `npm install`?"
6. Look at README

### Expected Behavior

The initialized project should be whatever Remix considers best to run on Vercel.

### Actual Behavior

The README contains the following at the top:
> **Warning**  
> The `@remix-run/vercel` runtime adapter has been deprecated in favor of out of
> the box Vercel functionality and will be removed in Remix v2.  
> This means you don't have to use the Vercel template & can just use the Remix
> template instead.

However the user did not select a "Vercel template". And "Remix template" is not an option when going through `create-remix`.

Instead the user was only asked "Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to 
change deployment targets.".

But the user is sure they are deploying to Vercel and has no reason to choose anything else. It doesn't make sense to choose "Remix App Server" when there is a "Vercel" option. And "use the Remix template instead" doesn't even clearly suggest that "Remix App Server" is the correct choice to make when deploying to Vercel.

**Comment by MichaelDeBoey** [comment]
As explained in the notice, the `@remix-run/vercel` runtime adapter has been deprecated in favor of out of the box Vercel functionality and will be removed in Remix v2.

Due to the removal of this adapter, we will also be removing our [Vercel template](https://github.com/remix-run/remix/tree/main/templates/vercel) in favor of the
[official Vercel template](https://github.com/vercel/vercel/tree/main/examples/remix).

Please follow the Vercel docs for deploying Remix to their service. They've got dedicated resources and libraries to make it a great experience: https://vercel.com/docs/frameworks/remix

**Comment by dantman** [comment]
@MichaelDeBoey This is still a bug because `create-remix` still has a "Vercel" option and it's still using that Vercel template.

**Comment by MichaelDeBoey** [comment]
@dantman As said before: we're going to remove that in V2 (which is what the team is currently actively working on)

If you use `npx create-remix@next`, you won't see the Vercel choice anymore
