### ISSUE TITLE
Default error boundary loses message of exception thrown during client-side routing

### ISSUE THREAD

**Issue by ianwremmel** [remix-run/remix#7270]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a trivial page like 

```
export default function SimulatedRenderingErrorPage() {
  throw new Error('This is a simulated React error.');
}
```

2. Link to that page from another page

```
<Link to="/errors/react">Client-Rendered React Error</Link>
```

3. Run your app
4. Click the link you just created. 
5. Observe that you see "Application Error" and a stack trace, but you don't see "This is a simulated React error."
6. Reload the page
7. Observe that you see "Application Error" and a stack trace, and now "This is a simulated React error." is also present

### Expected Behavior

<img width="1419" alt="Screenshot 2023-08-27 at 4 42 38 PM" src="https://github.com/remix-run/remix/assets/1182361/53203ba3-c9e2-4476-8046-7ef107cc8cea">

### Actual Behavior

<img width="808" alt="Screenshot 2023-08-27 at 4 42 32 PM" src="https://github.com/remix-run/remix/assets/1182361/29b62f9c-2492-49f4-87c1-1b88d8f11464">

**Comment by brophdawg11** [comment]
I don't think this is a bug but just a slight difference in behavior across JS runtimes.  

Remix includes a root default error boundary that renders the [stack](https://github.com/remix-run/remix/blob/main/packages/remix-react/errorBoundaries.tsx#L99) in dev mode.  It looks like for errors in Node/Chrome/Edge, the stack includes the message by default (this is why you always get it on the hard reload, since the error comes from a render in Node, but on the client side transition it's rendering in the browser):

<img width="574" alt="Screenshot 2023-08-28 at 9 44 25 AM" src="https://github.com/remix-run/remix/assets/1609022/b90863f2-6e94-42a5-bd87-cef4608e9b82">

<img width="281" alt="Screenshot 2023-08-28 at 9 44 04 AM" src="https://github.com/remix-run/remix/assets/1609022/adf2b7e4-66a3-4fa7-a9ef-3fe515170746">

But errors in Firefox/Safari do not:

<img width="270" alt="Screenshot 2023-08-28 at 9 44 09 AM" src="https://github.com/remix-run/remix/assets/1609022/a67683ac-cf7a-470a-abc4-af7ba255d1ea">
<br/>
<img width="187" alt="Screenshot 2023-08-28 at 9 45 16 AM" src="https://github.com/remix-run/remix/assets/1609022/265f1973-516f-4491-a192-ef7e90c9459c">


We keep the default error boundary UI to a minimum by design to avoid leaking any information to the end-user (and we genericize message and strip stack traces in production).  

Apps should not be relying on the root default error boundary past any initial development and should instead be adding [Error Boundaries](https://remix.run/docs/en/1.19.3/route/error-boundary-v2) to take control over the UI.  

If you want the `error.message` to appear in all cases, you can add an `ErrorBoundary` to the root route:

```jsx
export function ErrorBoundary() {
  let error = useRouteError();
  let heading: string;
  let meta: string | undefined;

  if (isRouteErrorResponse(error)) {
    heading = error.status + " " + error.statusText;
    meta = error.data;
  } else if (error instanceof Error) {
    console.error(error);
    heading = error.message;
    meta = error.stack;
  } else {
    heading = "Unknown Error";
  }

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body>
        <h1>{heading}</h1>
        {meta ? <pre>{meta}</pre> : null}
        <Outlet />
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}
```
