### ISSUE TITLE
@remix-run/eslint-config not compatible with @typescript-eslint/parser 6.x

### ISSUE THREAD

**Issue by stevensacks** [remix-run/remix#7325]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

We use additional eslint rules on top of the ones in remix-run/eslint-config.

Currently, we cannot upgrade other eslint libraries that depend on @typescript-eslint/parser@6.x because remix-run/eslint-config is fixed to 5.62.0.

### Expected Behavior

Please add @typescript-eslint/parser 6.x support to @remix-run/eslint-config

### Actual Behavior

Error when trying to update eslint-config-airbnb-typescript from 17.0.0 to 17.1.0 (also happens with other libs):
```
npm ERR! Found: @typescript-eslint/parser@5.62.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   @typescript-eslint/parser@"^5.59.0" from @remix-run/eslint-config@1.19.3
npm ERR!   node_modules/@remix-run/eslint-config
npm ERR!     dev @remix-run/eslint-config@"1.19.3" from the root project
npm ERR!   peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.62.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     @typescript-eslint/eslint-plugin@"^5.59.0" from @remix-run/eslint-config@1.19.3
npm ERR!     node_modules/@remix-run/eslint-config
npm ERR!       dev @remix-run/eslint-config@"1.19.3" from the root project
npm ERR!     peerOptional @typescript-eslint/eslint-plugin@"^5.0.0" from eslint-plugin-jest@26.9.0
npm ERR!     node_modules/@remix-run/eslint-config/node_modules/eslint-plugin-jest
npm ERR!       eslint-plugin-jest@"^26.9.0" from @remix-run/eslint-config@1.19.3
npm ERR!       node_modules/@remix-run/eslint-config
npm ERR!         dev @remix-run/eslint-config@"1.19.3" from the root project
npm ERR!     2 more (eslint-config-airbnb-typescript, eslint-plugin-jest)
npm ERR!   1 more (eslint-config-airbnb-typescript)
```

**Comment by brophdawg11** [comment]
Just as a heads up - I think we are leaning towards [deprecating the `@remix-run/eslint`](https://github.com/remix-run/remix/issues/7056) package since the `eslint` ecosystem is quite broad and opinionated so it's a decent amount of overhead to maintain and keep up to date with issues like this one.  Keeping up with that distracts from the primary focus of Remix the framework, unfortunately.

There's details in the linked issue but the idea would be that Stacks would come with a lint setup but it would invert the control and you'd be able to make updates like this without relying on us to make these changes and push releases out for you.  And if you started from a basic template without an eslint setup, you'd be able to copy one from the stacks fairly easily.

I'll keep this open until we make an official decision on https://github.com/remix-run/remix/issues/7056.

**Comment by theocerutti** [comment]
Hello, did you make your decision ?

Because I would like to upgrade @typescript-eslint to v6 because I get false positive unused var errors using `@remix-run/eslint-config`. Also you are talking about `@remix-run/eslint` is it the same package as `@remix-run/eslint-config` ??

**Comment by brophdawg11** [comment]
> Hello, did you make your decision ?

Hi!  Yes - #7056 was closed via #7597. We haven't added official deprecation warnings yet but I expect we will soon.

> Also you are talking about @remix-run/eslint is it the same package as @remix-run/eslint-config ??

Oops - `@remix-run/eslint` was a typo of mine above, that should have been `@remix-run/eslint-config` 🤦 

I would recommend migrating to the vastly simplified [eslint config](https://github.com/remix-run/remix/blob/main/templates/remix/.eslintrc.cjs) used by the templates which will give you full control over the version of `@typescript-eslint` you are using in your project.

**Comment by brophdawg11** [comment]
I'm going to close this issue out because we are planning to deprecate `@remix-run/eslint-config` and are actively moving folks away using it via the templates/stacks.  I believe a major upgrade of the underlying `@typescript-eslint` would warrant a major Remix version upgrade which isn't in the cards at the moment.

If you need to get to the latest version of `@typescript-eslint/parser`, please begin moving off of `remix-run/eslint-config` to one the simplified configs in the current templates (which are largely what the old config was trying to get to) andf hen you have full control over the dependencies.

**Comment by vhscom** [comment]
> I would recommend migrating to the vastly simplified [eslint config](https://github.com/remix-run/remix/blob/main/templates/remix/.eslintrc.cjs) used by the templates which will give you full control over the version of `@typescript-eslint` you are using in your project.

Ideally we would not be using any CommonJS in modern apps. Flag configs make this a good time to switch. The new file name is called `eslint.config.js`. And you [can ignore files](https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files) directly from your config now, rather than via NPM scripts.
