### ISSUE TITLE
Make the Remix App Server resilient to unhandled promise rejections

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#765]
So we can handle stuff like this: https://github.com/razvan-soare/remix-test/pull/1

**Comment by judicaelandria** [comment]
Do you mean remix app server will await automatically for the response and return the value even if the dev didn't add async await?

**Comment by kentcdodds** [comment]
No, it wouldn't be able to do that. But I think if we added this we could handle the error so it doesn't just crash:

```ts
process.on('unhandledRejection', error => {
  // log the error, but don't crash
});
```

**Comment by judicaelandria** [comment]
yes! can I work on this issue?

**Comment by kentcdodds** [comment]
If you'd like to, sure! I'm afraid I don't have bandwidth right now to help get you set up though. So if you're ok working through that on your own then that works for us. Make sure you first are able to reproduce the issue before implementing any fix so you know that it actually does fix the issue. Thanks!

**Comment by judicaelandria** [comment]
Hi! okay no worries, working on it right now, having a little trouble with the Request in the test
```ReferenceError: Request is not defined```

for confirmation this is the file I should Edit remix-server-runtime and the file data.ts for the loader, the test file data-test.ts

**Comment by kentcdodds** [comment]
Sorry, I haven't worked in the codebase enough to know off the bat what the problem could be. Sorry :(

**Comment by jacob-ebey** [comment]
> Hi! okay no worries, working on it right now, having a little trouble with the Request in the test `ReferenceError: Request is not defined`
> 
> for confirmation this is the file I should Edit remix-server-runtime and the file data.ts for the loader, the test file data-test.ts

https://remix.run/docs/en/v1/other-api/node

**Comment by judicaelandria** [comment]
hey @kentcdodds I'm sorry I can't work on this for now cuz i need to rest cuz of covid, you can assign it to someone else

**Comment by kentcdodds** [comment]
Sorry to hear that @judicaelandria! Get well soon!

**Comment by jackie-greenbaum** [comment]
Saw this was marked as completed, but not seeing any other context around what the fix was.

We are seeing similar behavior that @kentcdodds described in which an error from our `deferred` loader is not being handled, which results in Remix crashing.

We have a parent route which returns a set of deferred loaders

```
const getAPIData = async () {
  // Fetch data from the API
}

export const loader() {
  return defer({
     "parentData": {"bar": "baz"}
     "childData": getAPIData()
  })
}

export default ParentRoute() {
  const loaderData = useLoaderData()
  // render ParentRoute
}
```

And a child route which gets the data and renders it using `<Suspense />`

```
export const ChildRoute() {
  const loaderData = useRouteLoaderData("/routes/parent")

  return <Suspense
      fallback={<Skeleton />}
    >
      <Await resolve={loaderData?.childData} errorElement={<p>Error!</p>}>
        {(childData) =>
          childData !== undefined ? (
            // Render Child Route
          ) : null
        }
      </Await>
    </Suspense>
}
```

We do this so that we can begin loading the child data as soon as we reach the parent route since `getAPIData()` take a long time to complete. This works fine for us, except that when `getAPIData()` encounters an error, in which case the entire application will crash.

Confusingly, if I instead move the call to `getAPIData()` out of the ParentLoader and into a loader on the actual `ChildRoute`, the error does seem to get handled (the `suspenseFallback` is shown) rather than the page crashing on an unhandled error.

Trying to see if this is something we expect Remix to handle gracefully without crashing.

(Happy to open a separate bug on this if this seems out of scope of the issue as originally described)

**Comment by abarreraaponte** [comment]
For any kind soul that comes here looking for answers, this solution worked for me:
```javascript
process.on("unhandledRejection", (reason: any, p: Promise<any>) => {
  console.error("Unhandled Rejection at:", p, "reason:", reason);

  let stack = '';
  if (reason && reason.stack) {
    stack = reason.stack;
  } else if (typeof reason === 'string') {
    stack = reason;
  } else {
    stack = JSON.stringify(reason);
  }

  logger.error("Unhandled Promise Rejection", { reason, stack, promise: p });
});
`
My logger uses AWS Cloudwatch and i was getting no stack trace but this solution keeps the node process alive, logs the error and everyone's happy.
