### ISSUE TITLE
how to prevent api fetch repeat in Remix

### ISSUE THREAD

**Issue by WreewanMorhee** [remix-run/remix#7673]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I have path: /main
in this path, I call api: /my_certain_api
and when I click button to /main?page=1
my api: /my_certain_api called again
and when I click back btn in browser from /main?page=1 to /main
my api called again 

### Expected Behavior

I think the api should just been called once.

if in SPA, I call in then store response in redux, 
then I can prevent it been called twice.

### Actual Behavior

How can I prevent this happened in Remix ?

or is there any hint/tutorial in doc has mentioned this situation ?

**Comment by akomm** [comment]
Your assumption is (in most situation) wrong. Do you want user A to open /main and user B opening /main to see data previously returned to user A?

HTTP is stateless. Each request is independent of another. 

You can use http caching utilities that make browser cache certain request. Or you need to implement a session based caching separating the cache for each user. You will have to handle yourself the invalidation logic to not show stale data, issues like memory usage by the cache and garbage collection. You need to be careful what you cache and what not too... There are a lot of pitfalls. Its not trivial.

It always easier to use the platform (HTTP) since caching this way separates it by user simply using the client browser cache.

**Comment by sergiodxa** [comment]
You can export a shouldRevalidate function from your route to tell Remix to don’t fetch the loader again when that search paran change.

**Comment by brophdawg11** [comment]
@sergiodxa is correct.  Because search params are available to all loaders, Remix cannot be sure whether any existing loaders would return different data for `?page=1`, so Remix re-calls all active loaders if a search param changes.  You can opt out of this with [shouldRevalidate](https://remix.run/docs/en/main/route/should-revalidate).  There's a [section](https://remix.run/docs/en/main/route/should-revalidate#ignoring-search-params) in there that is likely close to what you are looking for.

**Comment by WreewanMorhee** [comment]
@sergiodxa @brophdawg11 

yes, I think this is what I want !
thank u for your help
