### ISSUE TITLE
Hydration failed because the initial UI does not match what was rendered on the server

### ISSUE THREAD

**Issue by ric980** [remix-run/remix#7699]
### What version of Remix are you using?

2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Open my website.
2. The error pops in console.
3. SEO is dead.
4. Search bots see zero text content.

I understand this is not an issue with Remix, but I am using Remix and I have no clue on how to deal with this. What is not the same between server and client? How to troubleshoot it? I'm stuck.

I have no browser extensions. Removed them all for the test.
I have no locale specifics like dates or other.
The Google Tag and Meta Pixel scripts are not rendered in development environment.
The landing page of my site is completely static.

Why do I get this error?

> Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.

> Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.

> Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

### Expected Behavior

Server-side rendering to work.

### Actual Behavior

Server-side rendering is not working.

**Comment by fernandocanizo** [comment]
I came here because I have the same issue, so we can take the `bug:unverified` tag.

**Comment by sergiodxa** [comment]
> 3. SEO is dead.
> 4. Search bots see zero text content.

> Server-side rendering is not working

Those are not right, just because hydration failed doesn't mean SSR is not working and your SEO is dead and search bots will see zero text content.

You can test this by disabling JS, if you still get the UI in place with content then SSR is working and that's why search bots will see.

The hydration warning means there's some difference between your server-side rendered HTML and the DOM React expected on hydration. [This is a great article on how to solve hydration errors in Remix](https://www.jacobparis.com/content/remix-hydration-errors), there Jacob (the author) mentions how to debug hydration errors and many reasons it could be happening.

> The landing page of my site is completely static

If your landing is really completely static, consider removing the <Scripts /> component in root, you can [hydrate on-demand](https://sergiodxa.com/articles/on-demand-hydration-in-remix) your app, by only rendering the <Scripts /> component for routes that needs JS, so static routes will load faster and without hydration errors.

**Comment by ric980** [comment]
I've disabled the JavaScript and I see nothing but the header and footer. The Outlet is not rendering anything. This is my root.tsx:

```
      <body>
        <Header />
        <Outlet />
        <Footer />
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
      </body>
```

That's why I am saying that bots don't see a thing.

Thanks for the article. I'll go through it. Hope it helps 🤞 

Thank you.

**Comment by ric980** [comment]
I found my problem. I am using `useMediaQuery` which always returns `false` at the server side. Thanks for the help. Much appreciated.

**Comment by tobob** [comment]
in `links` section I've added:

```
export const links: LinksFunction = () => [
  { rel: "preconnect", href: "https://fonts.googleapis.com" },
  {
    rel: "preconnect",
    href: "https://fonts.gstatic.com",
    crossOrigin: "anonymous",
  },
  {
    rel: "stylesheet",
    href: "https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap",
  },
  { rel: "stylesheet", href: toastStyles },
  { rel: "stylesheet", href: tailwindStyles }, <---- this one 
];
```

and import:

```
import tailwindStyles from "./tailwind.css?url";
```

**Comment by matt-halliday** [comment]
> in `links` section I've added:
> 
> ```
> export const links: LinksFunction = () => [
>   { rel: "preconnect", href: "https://fonts.googleapis.com" },
>   {
>     rel: "preconnect",
>     href: "https://fonts.gstatic.com",
>     crossOrigin: "anonymous",
>   },
>   {
>     rel: "stylesheet",
>     href: "https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap",
>   },
>   { rel: "stylesheet", href: toastStyles },
>   { rel: "stylesheet", href: tailwindStyles }, <---- this one 
> ];
> ```
> 
> and import:
> 
> ```
> import tailwindStyles from "./tailwind.css?url";
> ```
> 
> and it resolved problem

Was banging my head for ages on this. Thanks
