### ISSUE TITLE
Vite: in pnpm monorepo, imports to .server.ts and .client.ts files are not excluded from the respective builds

### ISSUE THREAD

**Issue by itsMapleLeaf** [remix-run/remix#7723]
### What version of Remix are you using?

0.0.0-experimental-5603af8a3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```bash
git clone -b module-suffixes https://github.com/itsMapleLeaf/remix-vite-workspaces.git
cd remix-vite-workspaces
pnpm install
cd workspaces/web
pnpm dev
```

### Expected Behavior

The app should show "The answer is 42" and "The client answer is 42", and the counter button should work

### Actual Behavior

Only the "server answer" is shown, and client JS fails to load:
```
Uncaught SyntaxError: The requested module '/app/answer.server.ts' does not provide an export named 'theAnswer' (at _index.tsx:4:10)
```

`pnpm build` Shows a similar error:
```
"theAnswer" is not exported by "app/answer.server.ts", imported by "app/routes/_index.tsx".
file: C:/dev/demo/remix-vite-workspaces/workspaces/web/app/routes/_index.tsx:4:9
2: import { useLoaderData } from "@remix-run/react"
3: import { theClientAnswer } from "~/answer.client.ts"
4: import { theAnswer } from "~/answer.server.ts"
            ^
5: import { Counter } from "~/components/Counter.tsx"
error during build:
RollupError: "theAnswer" is not exported by "app/answer.server.ts", imported by "app/routes/_index.tsx".
```

**Comment by pcattori** [comment]
Made some fixes last week and this is no longer reproducible. Now `42` is shown for both:

<img width="278" alt="Screenshot 2023-10-27 at 2 37 03 PM" src="https://github.com/remix-run/remix/assets/1477317/2eb492ff-6c1b-4299-b6ff-d80687d617ed">

Though note that including the client answer as part of the initial render causes hydration errors, but that's to be expected since you are literally telling the client and server to render different things.
