### ISSUE TITLE
Error after each file save after Remix v2

### ISSUE THREAD

**Issue by brandonpittman** [remix-run/remix#7739]
### What version of Remix are you using?

2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Change anything in a source file

### Expected Behavior

App does hot reloading without error

### Actual Behavior

Get `net::ERR_CONNECTION_REFUSED` error in browswer.
<img width="536" alt="Screenshot 2023-10-23 at 3 59 46 PM" src="https://github.com/remix-run/remix/assets/967145/0079cc28-140a-4db3-9ceb-461e40d4d364">

**Comment by brandonpittman** [comment]
`--manual` seems to have fixed it.

**Comment by jamesgrogantech** [comment]
Just for extra clarification as I had the same issue. Adding `--manual` to `dev` within scripts in package.json.

Example: 
`"dev": "remix dev --manual -c \"npm run dev:serve\"",`

**Comment by jarimustonen** [comment]
Can someone explain why this works. I read the documentation [1] and I do not see any indication why this would fix the issue. I also worry that adding --manual will introduce other unwanted behaviour.

1. https://remix.run/docs/en/main/guides/manual-mode

**Comment by Hansenq** [comment]
Looks like Manual Mode changes how hot reloads are done. Instead of restarting the app server, manual mode keeps the app server running across hot updates. Because the app server continues running, we don't run into the bug. See https://remix.run/docs/en/main/other-api/dev#manual-mode

This does unblock me but it doesn't actually solve the issue, because the normal usage of Remix should work without erroring out. Would love for this issue to be reopened so we can move back to automatic mode, if possible!

**Comment by Hansenq** [comment]
ah looks like this is being tracked in #7621
