### ISSUE TITLE
Vite: HDR is triggered unnecessarily

### ISSUE THREAD

**Issue by OnurGvnc** [remix-run/remix#7772]
### What version of Remix are you using?

0.0.0-nightly-1f29147-20231026

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```sh
npx create-remix@nightly --template pcattori/remix-template-vite
cd ./my-remix-app
npm run dev
```

`app/routes/_index.tsx`:

```diff
-import type { MetaFunction } from "@remix-run/node";
+import { json, type MetaFunction } from "@remix-run/node";
+import { useLoaderData } from "@remix-run/react";
 
export const meta: MetaFunction = () => {
  return [
    { title: "New Remix App" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};
 
+export const loader = () => {
+  console.log("loader called! " + Math.random());
+  return json({ message: "Hello from loader!" });
+};
+
 export default function Index() {
+  const loaderData = useLoaderData<typeof loader>();
   return (
     <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
-      <h1>Welcome to Remix</h1>
+      <h1>Welcome to Remix! - {loaderData.message}</h1>
       <ul>
         <li>
```

I've observed that HDR is triggered (`console.log("loader called! " + Math.random())`) when I make minor changes to the Component code in the 'app/routes/_index.tsx' file.

### Expected Behavior

I was expecting the loader not to be triggered when I only make changes to the Component code in the 'app/routes/_index.tsx' file.

### Actual Behavior

when I make small changes to the Component code, the loader is triggered (HDR)

**Comment by pcattori** [comment]
The goal of HDR is to make sure up-to-date server data is available in the client so that HMR can be performed successfully. Reducing loader calls is nice, but not the main goal of HDR.

In the esbuild-based compiler, we performed a costly in-memory bundle of the route simply to determine if code changes affected a loader. Vite's dev server model is different; it doesn't bundle at all, but rather lazily compiles each module on-demand. This makes cross-module treeshaking untenable during development in Vite.

So instead, the Remix Vite plugin uses a simpler model: just revalidate loaders on any change. At the end of the day, HDR is there to enable HMR which is all about extending live reload to preserve browser state during code edits. Live reload would have refreshed the page and refetched data for all loaders anyway.

This approach keeps our compiler surface area small and fast. If revalidating loaders becomes a bottleneck, that problem should be solved independently. For example, you could build a MSW-based server cache in dev. Or Remix could give you devtools to turn off HDR when you are working on UI only and don't want to needlessly refetch server data.

**Comment by OnurGvnc** [comment]
hi @pcattori, first of all, thank you very much for your detailed response.
I understand your points very well. I have loaders that do a lot of work and make API calls. As you mentioned, revalidating creates bottlenecks for me.
In search of an independent solution, I've created the quirky patch below.

```patch
diff --git a/node_modules/@remix-run/dev/dist/vite/static/refresh-utils.cjs b/node_modules/@remix-run/dev/dist/vite/static/refresh-utils.cjs
index 8a1c0d4..595b6b7 100644
--- a/node_modules/@remix-run/dev/dist/vite/static/refresh-utils.cjs
+++ b/node_modules/@remix-run/dev/dist/vite/static/refresh-utils.cjs
@@ -50,12 +50,22 @@ const enqueueUpdate = debounce(async () => {
     routeUpdates.clear();
   }
 
-  await revalidate();
+  // await revalidate();
   if (manifest) {
     Object.assign(window.__remixManifest, manifest);
   }
   exports.performReactRefresh();
 }, 16);
+let shiftCount = 0, shiftTimeout;
+document.addEventListener("keydown", ({key}) => {
+  if (key !== "Shift"){ shiftCount = 0; return; }
+  clearTimeout(shiftTimeout);
+  if (++shiftCount === 2) {
+    revalidate();
+    console.log("router revalidate triggered");
+  }
+  shiftTimeout = setTimeout(() => shiftCount = 0, 300);
+});
 
 // Taken from https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/lib/runtime/RefreshUtils.js#L141
 // This allows to resister components not detected by SWC like styled component

```

HMR works just as I want it to. To manually trigger `revalidate()`, I double-press the Shift key. Yeah, it's a quirky solution, but it's the first thing that came to mind :)



HMR is very fast. Using Remix with Vite was one of the things I was most excited about. Thank you very much to both you and @markdalgleish for all your work.
