### ISSUE TITLE
Navigation does not cancel in-flight requests by useFetcher

### ISSUE THREAD

**Issue by alexbu92** [remix-run/remix#7782]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

https://codesandbox.io/p/sandbox/ecstatic-meadow-qfzw8r

Open network tab and disable cache.
Click on "Go to other route" while the fetchers are loading.

### Expected Behavior

The in-flight requests get canceled and the navigation occurs.

### Actual Behavior

The in-flight requests do not get canceled and the navigation only occurs once all in-flight requests are completed or timed out.

**Comment by brophdawg11** [comment]
Huh, interesting.  This looks like it's due to the built-in browser parallel request limit.  Chrome only allows 6 parallel requests to the same domain at a time.  So what happens is:

* The aborting of in-flight fetchers happens on unmount
* When you click a link, we can't render the new route until we load the JS chunk, so we remix makes a request for the `other-route.js` module file
* This request gets queued up behind the existing fetcher network calls since there are already 6+ requests in flight
* We can't render the new route until this JS file loads (which would unmount the current route and abort it's fetchers)
* So we end up in a bit of a deadlock where fetchers can't be aborted until the JS chunk loads, but the JS chunk can't load until the fetchers complete.

If you drop your example to 5 fetchers (`const fakeArray = [...Array(5).keys()]`) then everything works as expected since the JS chunk is now the 6th parallel request and doesn't get queued up.

We'll have to think about whether there's anything we can do here.  Once you've sent 6 fetches out - we can't load the JS chunk from the same domain until they complete.  And we can't necessarily blindly abort them since we don't know for _sure_ if they'll still be around on the next route (this is more of a problem too once we let you [specify the fetcher key](https://github.com/remix-run/remix/discussions/7698)).

One workaround would be to load your JS chunks from a separate domain (i.e., assets.mycompany.com) so they don't count in the same bucket as the 6+ fetcher calls.

**Comment by rbrcurtis** [comment]
@brophdawg11 what is the best way to load static assets from a different URL? I don't see config options for that. HTML base tag?

**Comment by brophdawg11** [comment]
Looks like we don't call this out specifically, but you can put a full domain in `remix.config.js` [`publicPath`](https://remix.run/docs/en/main/file-conventions/remix-config#publicpath)

`"publicPath": "http://example.com/assets/"`

I'll get the docs updated for that.

**Comment by brophdawg11** [comment]
I should also note in addition to the separate domain workaround, HTTP/2 should also resolve this issue since AFAIK that should remove the 6-request limit.

**Comment by alexbu92** [comment]
Thank you, serving the assets from a separate domain fixed the issue!
