### ISSUE TITLE
Vite template failing on Vercel

### ISSUE THREAD

**Issue by franklinjavier** [remix-run/remix#7852]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Clone this repo https://github.com/franklinjavier/remix-starter-template
- Create new project on Vercel and select this repo

### Expected Behavior

Show the template page

### Actual Behavior

It is displaying the source code of index.js. [remix-starter-template.vercel.app](https://remix-starter-template.vercel.app/)

I tried to change the preset from Vite to Remix, but i'm receiving this error
![image](https://github.com/remix-run/remix/assets/440220/11d4dbb4-cd1d-4cb3-b50c-b970b315ff6f)

**Comment by markdalgleish** [comment]
This is happening because Vercel is actually running the build with their own fork of Remix behind the scenes ([@vercel/remix-run-dev](https://www.npmjs.com/package/@vercel/remix-run-dev) etc.). The build output from Vite is the same shape as the existing Remix compiler, but not the Vercel fork. You'll need to raise this with them.

**Comment by franklinjavier** [comment]
Migrating to Render for now, thank you!
https://remix-starter-template.onrender.com

**Comment by princemuel** [comment]
I ran into this problem, and it took me some hours of trying to fix it until I came across this issue. This gave me the idea of the solution in the screenshot attached. I had to change the template to `Other` instead of `Remix` or `Vite`
![Screenshot 2024-02-22 at 03-45-52 Dashboard](https://github.com/remix-run/remix/assets/68931805/248ce258-cc6f-404c-8a2a-37e00809c88f)

**Comment by princemuel** [comment]
Okay. It's building but not deploying. @franklinjavier How did you setup the build settings in Render? I went with the defaults but it's running into this infinite loop when I visit the live site.

**Comment by franklinjavier** [comment]
I didn't change any build config, I left it as default. I just checked and it seems like the deployment is broken. I will evaluate and respond to you.

**Comment by franklinjavier** [comment]
> Okay. It's building but not deploying. @franklinjavier How did you setup the build settings in Render? I went with the defaults but it's running into this infinite loop when I visit the live site.

@princemuel 
![image](https://github.com/remix-run/remix/assets/440220/41861b22-18f9-4332-8d67-fdbd32422bc1)
