### ISSUE TITLE
useAsyncValue Return Type doesn't work with typeof loader

### ISSUE THREAD

**Issue by manzaloros** [remix-run/remix#7881]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
import { defer } from "@remix-run/node";
import { useAsyncValue } from "@remix-run/react";

export async function loader() {
  const foo = new Promise(() => {
    return "bar";
  });
  return defer({ foo });
}

export default function Index() {
  const { foo } = useAsyncValue() as typeof loader;
  return (
    <div>
      {foo}
    </div>
  );
}

```

### Expected Behavior

I should be able to apply a type to the return of `useAsyncValue()`.

### Actual Behavior

TypeScript error:

```
Property 'foo' does not exist on type '() => Promise<TypedDeferredData<{ foo: Promise<unknown>; }>>'.
```

**Comment by brophdawg11** [comment]
There's a few things not quite right here:

* The promise is setup incorrectly and will never resolve without calling the `resolve` function
* This isn't quite the right usage for `useAsyncValue`- that's intended to be used in a child component of `Await`
* The `foo` property on `useLoaderData()` is a `Promise<string>` and needs to be passed to `Await` to wait for it to resolve
* If you want to extract the property from `typeof loader` you need to use `SerializeFrom` (from `@remix-run/node`) which knows how to deserialize a `Response` since your loader data is sent over the network

Here's a working example:

```jsx
export async function loader() {
  const foo = new Promise<string>((resolve) => resolve("bar"));
  return defer({ foo });
}

export default function Index() {
  const { foo } = useLoaderData<typeof loader>();
       // ^? Promise<string>
  return (
    <Await resolve={foo}>
      <RenderAsyncData />
    </Await>
  );
}

function RenderAsyncData() {
  // Here, useAsyncValue gives you the resolved value from the parent `Await` component
  let foo = useAsyncValue() as Awaited<SerializeFrom<typeof loader>["foo"]>
   // ^? string
  return <p>{foo}</p>;
}
```

There is a shorthand way to do this as well if you use a render prop:

```jsx
<Await resolve={foo}>{(value) => <p>{value}</p>}</Await>
```
