### ISSUE TITLE
Exporting a loader with a name results in full document reloads on use in fetcher

### ISSUE THREAD

**Issue by ZipBrandon** [remix-run/remix#7957]
I have some loaders that I will also export a named version of them for use in other loaders.  I have noticed that I have peculiar results with a vite build as of 2.2.0. 

### What version of Remix are you using?

0.0.0-nightly-8543efe-20231108

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. clone `https://github.com/ZipBrandon/remix-export-loader-fullreload` and start repo
2. http://localhost:5173/testing
3. click `fetch from api.helloWorld` and it behaves as expected
4. click `fetch from api.helloWorldNamed` and it causes full reload

### Expected Behavior

Fetch and return data asynchronously

### Actual Behavior

Causing a full reload.
```ts
import type { LoaderFunctionArgs } from "@remix-run/node";
import { defer } from "@remix-run/node";


export const namedLoader = loader; // <-- this makes the fetcher fail
export async function loader  (args: LoaderFunctionArgs)  {
  const { request, context, params } = args;

  return defer({
    data: "hello world named",
  });
};
```

**Comment by hi-ogawa** [comment]
Thanks for the reproduction.
This is probably due to current limitation of "remove server exports" done by remix.
I didn't check this deep at that time but https://github.com/remix-run/remix/issues/7864#issuecomment-1790039032 was also having the same issue.

When I look at the network devtool, I see `useFetcher` triggers two requests:

- http://localhost:5173/api/helloWorldNamed?_data=routes%2Fapi.helloWorldNamed
- http://localhost:5173/app/routes/api.helloWorldNamed/route.ts?import

The 2nd one is to load client route module, but its content looks like below. `export const loader = ...` is eliminated but `namedLoader` was left as is, which would obviously throw:

```
$ curl 'http://localhost:5173/app/routes/api.helloWorldNamed/route.ts?import'
export const namedLoader = loader;
;
//# sourceMappingURL=...
```

I cannot think of a general solution, but at least for this specific reproduction, one workaround could be to wrap `loader` reference ike below so that it won't throw during load time:

```tsx
export const namedLoader = (args) => loader(args);
```

The full reload mechanism is coming from here:

https://github.com/remix-run/remix/blob/d437e791b817695f736fb255110be94ce270a7e4/packages/remix-react/routeModules.ts#L134-L143

Currently there's no logging and it's quite puzzling at first. So, maybe it might make sense to add `console.error` to help at least some debugging. If I patch it, the error log looks like this:

> loader is not defined
    at app/routes/api.helloWorldNamed/route.ts?import:1:28

**Comment by pcattori** [comment]
With Vite, Remix is forced to become stricter about allowed route exports. Exporting user-defined names like `namedLoader` is no longer valid.

For rationale see #8171 and https://remix.run/docs/en/dev/future/vite#strict-route-exports
