### ISSUE TITLE
Remix matches in Meta Function is missing item when access

### ISSUE THREAD

**Issue by lyquocnam** [remix-run/remix#7974]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Access to child route: ex: `/` or `/shop`
2. The `matches` object in `MetaFunction` of parent route in folder: `_home/index.tsx` have all routes, but can not access to latest item.

Demo source code: https://github.com/lyquocnam/remix-matches-missing-item/blob/main/app/routes/_home/index.tsx
```tsx
import { MetaArgs } from "@remix-run/node";
import { Outlet } from "@remix-run/react";

export const meta = ({ matches }: MetaArgs) => {
  console.log(matches);
  console.log(matches[2]); // <-- there are 3 match items but can not access the latest item
  return [];
};

export default function HomeLayout() {
  return (
    <>
      <h1>Home Layout</h1>
      <Outlet />
    </>
  );
}
```

### Expected Behavior

`console.log(matches[2]);` has latest match item.

### Actual Behavior

`console.log(matches[2]);`
=> `undefined`
<img width="454" alt="Screenshot 2023-11-11 at 10 34 58" src="https://github.com/remix-run/remix/assets/8347826/bc4e7a72-87f1-40dc-83d2-e1a08f3e5f68">

**Comment by akamfoad** [comment]
Looks like each route's meta is called in order, and only the matches up to that route is passed to the route's meta function.

You have three matches here, and Remix calls each matched route's meta function one by one sequentially, like this:

First pass:

```js
  matches = [
    {
      id: 'root',
      data: null,
      meta: [],
      params: {},
      pathname: '/',
      handle: undefined,
      error: null
    }
  ]
```

Second pass:

```js
  matches: [
    {
      id: 'root',
      data: null,
      meta: [],
      params: {},
      pathname: '/',
      handle: undefined,
      error: null
    },
    {
      id: 'routes/_home',
      data: null,
      meta: [],
      params: {},
      pathname: '/',
      handle: undefined,
      error: null
    }
  ]
```

Third pass:

```js
  matches: [
    {
      id: 'root',
      data: null,
      meta: [],
      params: {},
      pathname: '/',
      handle: undefined,
      error: null
    },
    {
      id: 'routes/_home',
      data: null,
      meta: [],
      params: {},
      pathname: '/',
      handle: undefined,
      error: null
    },
    {
      id: 'routes/_home._index',
      data: null,
      meta: [],
      params: {},
      pathname: '/',
      handle: undefined,
      error: null
    }
  ]
```

You can see this statement which is inside a loop on the matches:
https://github.com/remix-run/remix/blob/bf2feb9bdb292ac6560964d6749b0fcf9a8c784e/packages/remix-react/components.tsx#L476

So you always have access to all matching routes up to the route's meta you're accessing `matches`.

So when you're in a nested layout one step below root, you have access to `root` and that route where you access it inside meta. So up until that point, there is only 2 elements inside the `matches` array. But when you log the array, it is not a value you log, it is a reference to that array in memory, and so when you see it formatted, you can see it appears like `[{}, {}]`, because at the time of logging, that was the case, but when you expand it, DevTools will render all it's elements, and by the time you expand it, the aforementioned loop is already done and all matches has been added to the array, so upon expanding, you'll get the complete list of arrays.

This happens because Remix doesn't pass a new array to each meta function, but passes the same variable, it is just that it mutates the array each step in the loop.

**Comment by brophdawg11** [comment]
@akamfoad is correct here, `meta` receives the matches up until that route so `matches` only contains 3 entries in the index route.  The layout route `matches` only contains root and the layout route.
