### ISSUE TITLE
my.$id.new-item route matches my.$id route

### ISSUE THREAD

**Issue by mschipperheyn** [remix-run/remix#8016]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I have a route that defines a form with a list of sub items that have their own form. 
The route setup is as follows

```
settings.instructors._index.ts - list
settings.instructors.$id.tsx - edit form parent
settings.instructors.$id.new-item.tsx - create form child
settings.instructors.new.tsx - create form parent
```

When I access `/settings/instructors/1/new-item` I get the page content for `/settings/instructors/1`

When I change the route name to 

```
settings.instructors.new-item.$id.tsx - create form child
```

and access `/settings/instructors/new-item/1`

I get the correct page content

This seems weird to me. Am I wrong?

### Expected Behavior

I would expect to get the content for the correct page

### Actual Behavior

I get the content for the parent page

**Comment by kiliman** [comment]
`v2` flat convention nests routes by looking at the parent prefix.

```
settings.instructors.$id.tsx <- parent layout
settings.instructors.$id.new-item.tsx <- prefix matches parent layout
^^^^^^^^^^^^^^^^^^^^^^^^ 
```

When you have a child route, your parent layout **must** include an `<Outlet>` to render the child route.

**Comment by brophdawg11** [comment]
As @kiliman said, this is by design that child routes automatically inherit the parent layouts and parent's must include an `<Outlet />` informing Remix where to render the child content.  

It sounds like you may not want to inherit the parent layout, so you may want to [opt out of layout nesting](https://remix.run/docs/en/main/file-conventions/routes#nested-urls-without-layout-nesting).
