### ISSUE TITLE
[Bug]: Not escaping special characters if the file name start wit dot

### ISSUE THREAD

**Issue by raymclee** [remix-run/remix#819]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### Steps to Reproduce

create new project, create a route with name [.well-known].tsx or [.]well-known.tsx

### Expected Behavior

match route /.well-known

### Actual Behavior

got error message from log No routes matched location "/.well-known"

**Comment by kiliman** [comment]
This appears to be a bug in `react-router` in `compilePath()`.

It generates a regex that expects either a word character or $. Since . or @ or any other symbol is not valid, it doesn't match.

I have a patch that will fix this (although there is a comment in there as to why they chose this pattern, but I'm not really sure what they are referring to. I've tried many different paths with the patch: /home, /home/index, /home2 and they all seemed to work.

Anyway, the patch is here: https://gist.github.com/kiliman/9b85e7873ed852d5ef0ea2f5af126b4b

Install `patch-package` and copy linked file to /patches. Make sure you add "postinstall": "patch-package". And re-install `react-router` and the patch will be applied.

I'll create a PR for this in `react-router`.

**Comment by benkraus** [comment]
Thanks so much @kiliman! 🙏

**Comment by machour** [comment]
Fixed in react-router 👍🏼
