### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by mwcampbell** [remix-run/remix#82]
Since Remix encourages the use of classic HTML form posts, I wonder if it has any sort of protection against cross-site request forgery. If so, I couldn't find anything about that in the docs.

**Comment by davidbarratt-drizly** [comment]
I'm shocked that this web framework uses HTML Forms, but does not protect against CSRF attacks _by default_. To make matters worse, the [documentation](https://remix.run/docs/en/v1/guides/data-writes) does not even mention this. Where it does mention it, it is completely **wrong**
> First, the new logout route is just there to make it easy for us to logout. The reason that we're using an action (rather than a loader) is because we want to avoid CSRF problems by using a POST request rather than a GET request. This is why the logout button is a form and not a link. Additionally, Remix will only re-call our loaders when we perform an action, so if we used a loader then the cache would not get invalidated. The loader is just there in case someone somehow lands on that page, we'll just redirect them back home.

To reiterate for those in the back, using a `POST` does **not** in any way prevent a CSRF.

I'm a long time user of frameworks like Symfony who provide CSRF protection out of the box and on by default. You have to explicitly disable the protection on a per-form basis. This is similar to React's built-in XSS protection and their [extremely verbose](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) method of bypassing it.

The above comment is _also_ incorrect because it assumes that I'm running a site on the _internet_ rather than perhaps an _intranet_. 

Let's say I build a form for Example, Inc.'s internal intranet and it's hosted at `https://deleteemployee.corp.example.com`, and it's only accessible if you are on example.com's corporate VPN. Since I know that is the only way to access it, I don't bother to build a login system (why go to that effort?) and Remix is great so I use that for my framework.

Well one day I get an email to my personal email that all of our employees have been deleted from our database! How is that possible?

Well... come to find out, one of our employees went to a competitor's website to do some price comparisons, they had a little snippet on their site that looks like this:
```
fetch('https://deleteemployee.corp.example.com', {  method: 'POST', body: '...' });
```
while they weren't able to read the response with JavaScript, the browser happily executed the request since it met the qualifications for a [simple request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests).

There are really only two ways to protect against this:
1. You could have the server enforce that incoming `POST` requests do not meet the criteria for a [simple request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests). For example, by enforcing a `Content-Type: application/json` header. Of coursse this would force JavaScript to be used for form submission.
2. Setting a cookie on the HTML page that has the form, that contains a signed token (a JWT?) that is verified on the `POST` request.

I can't recommend that **anyone** use this framework until this is fixed. Yes, engineers do (on occasion) need a way to opt-out of these protections, but by default they should be there.

I'm really hoping this is resolved quickly because Remix does seem really great and I'm excited to make something with it!

**Comment by mwcampbell** [comment]
Perhaps Remix is relying on the SameSite feature of cookies, now implemented in all modern browsers, for CSRF protection. That would be in keeping with the theme of being built on modern web fundamentals.

**Comment by davidbarratt-drizly** [comment]
> Perhaps Remix is relying on the SameSite feature of cookies, now implemented in all modern browsers, for CSRF protection. That would be in keeping with the theme of being built on modern web fundamentals.

If that's the case, then it should be made explicit in the documentation, but in my example above, the `SameSite` attribute is irrelevant if it's not setting a CSRF cookie in the first place.

**Comment by rphlmr** [comment]
Maybe it could help someone :) https://sergiodxa.com/articles/adding-csrf-protection-to-remix

Package here : https://github.com/sergiodxa/remix-utils

**Comment by ngbrown** [comment]
If using OAuth to start an authenticated session, one often has to use `SameSite=none` to get everything to work because of the redirect flow. Which prevents using the same cookies for CSRF in forms...
