### ISSUE TITLE
[Bug] Path parameter inside url not working as expected

### ISSUE THREAD

**Issue by AndrewOt** [remix-run/remix#8250]
### Reproduction

See this reproduction repo: https://github.com/AndrewOt/remix-bug-repro
1. Clone, install, and start the example site with `npm run dev`
2. Navigate to `/my-page/123` (or any number or "theId")
3. Notice the form on the page. Input some text and click submit
4. Notice that the url changes to `/my-page/123/success` but the content on the page does not change.

Alternatively, you can click the "Link test" button an show that the same occurs.

If you look at the code for the route `/my-page/123`, you can see that the `action` handling the form POST request returns a `redirect` to the success url. The url in fact changes but the content of the page does not. Notice also that this is defining the route with the folder name (with the `route.tsx` in the directory); this behavior also occurs with the typescript file itself containing the route name.

Behavior is reproducible on both chromium based browsers and firefox.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 4.41 GB / 15.93 GB
  Binaries:
    Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.12 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 119.0.6045.200
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.97)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @remix-run/css-bundle: ^2.3.1 => 2.3.1
    @remix-run/dev: ^2.3.1 => 2.3.1
    @remix-run/eslint-config: ^2.3.1 => 2.3.1
    @remix-run/node: ^2.3.1 => 2.3.1
    @remix-run/react: ^2.3.1 => 2.3.1
    @remix-run/serve: ^2.3.1 => 2.3.1
```

### Used Package Manager

npm

### Expected Behavior

The `action` should properly redirect the user to the new page (i.e. the url should change and the content of the page should change).

### Actual Behavior

Only the url changes and the content remains the same.

**Comment by kevinbailey25** [comment]
This is expected behavior with your current example. I believe you want to change your `my-page.$theId` folder to be `my-page.$theId._index` and then you'll get the behavior you're expecting. 

Right now when you navigate to your `success` page, (whether via redirect in an action, link or just typing the URL. Remix thinks that your route `my-page.$theId` is a layout route and is expecting there to be an `<Outlet />` in order to render the `success` page. 

I believe you don't want the `my-page.$theId` to be a layout route, and just a normal page, so renaming the folder to `my-page.$theId._index` will fix that.

Hope this helps

**Comment by AndrewOt** [comment]
Ah ok, so I'm just a noob. I will do that! Thank you!
