### ISSUE TITLE
Possible Vite loader not triggered on Link navigation bug

### ISSUE THREAD

**Issue by sadin999** [remix-run/remix#8259]
### Reproduction

https://github.com/sadin999/stripe-demo-repro/

### System Info

```shell
Linux, node v18.19.0

Local dev env
```

### Used Package Manager

npm

### Expected Behavior

Expect the loader to trigger and for the Loader date to be populated on navigation.

## Steps to reproduce

- No need to complete a payment; just navigating to payment/success page then clicking the link to go back to index ("/") causes the issue
- Stripe keys aren't required for repro; no need to actually click "buy"

## ISSUE:

With the experimental vite plugin;

- If the index is loaded normally, the loader runs and useLoaderData works;
- but if coming back to that page from a navigation (Link to="/") - e.g. from the payment/success page - the loader isn't running; so data is not set.

### Actual Behavior

When navigating using a "Link to" (in repro: payment.success.tsx file) - the navigation results in a loader data destructuring error as loader data is undefined; since the loader never ran (network tab confirms this).

**Comment by sadin999** [comment]
Possibly somewhat related to: https://github.com/remix-run/remix/issues/7894 - but not quite exact. Does not work on vite server restart

**Comment by hi-ogawa** [comment]
I tested your repo on stackblitz and it seems I cannot reproduce the issue here:
 
https://stackblitz.com/edit/github-j7dw96?file=app%2Froutes%2F_index.tsx

I added a test link to go between `/` and `/payment/success` and the index loader looks working fine to me:

<details><summary>reveal screencast</summary>

[스크린캐스트 2023-12-11 10-23-13.webm](https://github.com/remix-run/remix/assets/4232207/aab45cd3-b918-4108-96db-7a013f742760)

</details>

Am I missing essential steps for reproduction?

Also, I noticed you use `remixDevTools` plugin. Does it behave differently if you remove the plugin? (I tested both with and without it and both cases looked fine though.)

**Comment by sadin999** [comment]
Seems to work locally for me as well now. 

I nuked the code history when making the repro; so I lost what I could have changed (although I do not remember changing anything before pushing to github). Will reopen again if I can reproduce again; but for now the issue has disappeared.
