### ISSUE TITLE
Issues with clientLoaders on Vite (v2.5.1)

### ISSUE THREAD

**Issue by AlemTuzlak** [remix-run/remix#8583]
### Reproduction

I have the following repros:
https://github.com/AlemTuzlak/client-loader-vite-repro
the above is a minimum v2.5.1 project with Vite, here is a stackblitz of identical behavior without Vite that works as expected:
https://stackblitz.com/edit/remix-run-remix-8f4bvt?file=app%2Froutes%2Fpage.tsx

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 9.07 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.9 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 120.0.6099.225
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @remix-run/dev: ^2.5.1 => 2.5.1
    @remix-run/node: ^2.5.1 => 2.5.1
    @remix-run/react: ^2.5.1 => 2.5.1
    @remix-run/serve: ^2.5.1 => 2.5.1
    vite: ^5.0.0 => 5.0.12
```

### Used Package Manager

npm

### Expected Behavior

Here is the expected behavior:
The app doesn't crash when you go to the page
The `useLoaderData` data is available inside the custom hook 

### Actual Behavior

The app dies when you navigate to the page because the `data` inside the custom hook is undefined, when moved to top level of the component it works. (the `useLoaderData` hook I mean)

**Comment by brophdawg11** [comment]
This isn't a bug in `clientLoader` but a bug in the `useCachedLoaderData` implementation - but it may have exposed a bug in the Vite stacktrace/sourcemap logic.  The reason it was working in the esbuild version is because it was SSr-ing the index route and then only on client side navigation to `/page` was the custom hook running.  In the vite version the custom hook is in the index route so it runs on initial SSR, which exposes the bug in `useCachedLoaderData`.

The underlying issue is the difference in shape between `loader`/`clientLoader` but the hook was assuming that `useLoaderData` returned the same shape ((the clientLoader shape) every time.  This is not the case on initial SSR.  You specified `clientLoader.hydrate=true`to run the client loader on hydration, but since you didn't include a `HydrateFallback`, the server will still SSR the route and hydrate with the value of the server loader - then it will run the client loader and update the SSR'd UI in place.

Here's an updated stackblitz with the hook adjusted to handle both shapes:  https://stackblitz.com/edit/remix-run-remix-exkrr5

I am going to keep this open for now and see if I can trim down the vite stack trace issue to a more minimal repro though and we can re-purpose the issue.

**Comment by brophdawg11** [comment]
oh - nevermind, the vite stacktrace thing I was seeing must have been a stackblitz issue - I originally loaded your repo through their `/github` path: https://stackblitz.com/github/AlemTuzlak/client-loader-vite-repro

But when I clone your repo and run locally I see the right error:
![Screenshot 2024-01-23 at 10 07 52 AM](https://github.com/remix-run/remix/assets/1609022/53cd2bb1-024e-4cc6-9707-739ee72eac68)

**Comment by AlemTuzlak** [comment]
@brophdawg11 ahhh I actually didn't know that bit! Thank you for the clarification, it's really appreciated, now it makes sense why it didn't work. Sorry for wasting your time though!
