### ISSUE TITLE
remix with vite, Uncaught SyntaxError: redeclaration of import RefreshRuntime and HMR don't works

### ISSUE THREAD

**Issue by yracnet** [remix-run/remix#8590]
### Reproduction

https://github.com/yracnet/vr-1

### System Info

```shell
Uncaught SyntaxError: redeclaration of import RefreshRuntimeroot.tsx:1:866note: Previously declared at line 1, column 145

HMR doesn't work

NODEJS: 20.10.0
```

### Used Package Manager

npm

### Expected Behavior

The WS to HMR will be initialize 

### Actual Behavior

The WS doesn't work

**Comment by brophdawg11** [comment]
You don't want to use both of the `react` and `remix` plugins since the remix plugin includes the react plugin - that's why you're getting 2 copies of the RefreshRuntime.  I would suggest cresting your Remix/Vire app from this template (or using it as a reference): https://github.com/remix-run/remix/tree/main/templates/unstable-vite

```
npx create-remix@latest --template remix-run/remix/templates/unstable-vite
```
