### ISSUE TITLE
Loader isn't called when dynamic segments are used with nested layouts

### ISSUE THREAD

**Issue by chrisvltn** [remix-run/remix#8634]
### Reproduction

1. Go to https://stackblitz.com/edit/remix-bug-report?file=app%2Froutes%2F_layout.tsx
2. Click the link "Failing layout 2"

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 11.47 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.14.1 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.85
    Edge: 121.0.2277.83
    Safari: 17.2.1
  npmPackages:
    @remix-run/dev: 2.5.1 => 2.5.1 
    @remix-run/react: 2.5.1 => 2.5.1 
    @remix-run/server-runtime: 2.5.1 => 2.5.1 
    @remix-run/testing: 2.5.1 => 2.5.1
```

### Used Package Manager

pnpm

### Expected Behavior

Loader to be called, and state in component to be updated

### Actual Behavior

Page URL path updates, but `loader` isn't called and component state isn't updated

**Comment by brophdawg11** [comment]
Remix does not call re-used layout route loaders on GET navigations because you already have the data for that level and because no mutations have occurred the data should not be stale.  You can control this by exporting a [`shouldRevalidate`](https://remix.run/docs/en/main/route/should-revalidate) from your `_layout` route:

```js
export function shouldRevalidate() {
  return true;
}
```
