### ISSUE TITLE
Regression in handling .server modules between Remix compiler and Vite plugin

### ISSUE THREAD

**Issue by sixers** [remix-run/remix#8640]
### Reproduction

Client only and server only code mixed outside of `routes` folder using `.server` filename syntax. It works in old Remix compiler:
- Remix Compiler example: https://stackblitz.com/edit/remix-run-remix-ah2gan?file=app%2Froutes%2F_index.tsx

It fails with Vite equivalent:
- Vite Compiler example: https://stackblitz.com/edit/remix-run-remix-kgqk9p?file=app%2Froutes%2F_index.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/css-bundle: * => 2.5.1 
    @remix-run/dev: * => 2.5.1 
    @remix-run/node: * => 2.5.1 
    @remix-run/react: * => 2.5.1 
    @remix-run/serve: * => 2.5.1 

```

### Used Package Manager

npm

### Expected Behavior

`.server` module imports are excluded from the client bundle by default from all files, regardless of the code structure and imports outside of `routes` module.

### Actual Behavior

Vite compiler error:

```
11:05:09 [vite] Internal server error: Server-only module referenced by client

    '../queries/list-posts.server' imported by 'app/features/posts/pages/PostListPage.tsx'
```

**Comment by sixers** [comment]
Known workaround:
- Remove `.server` from filename
- use `vite-env-only` plugin and wrap everything inside module with `serverOnly$`.

This works but is annoying, and I hope we can retain the old behaviour with the Vite plugin, where I can simply add `.server` to filename and be sure that it will not be included in the client bundle.

**Comment by pcattori** [comment]
@sixers this is a [limitation of Vite](https://remix.run/docs/en/main/future/vite#splitting-up-client-and-server-code)'s on-demand module-by-module compilation model in development. Note that you still get Rollup's treeshaking in production, but [relying on treeshaking for correctness is brittle](https://github.com/remix-run/remix/blob/main/decisions/0009-do-not-rely-on-treeshaking-for-correctness.md).

With Vite's dev server, there are only two options:
- Mark code as server-only at the module level (e.g. with `.server` modules)
- Mark code as server-only at the expression level (e.g. with `vite-env-only`'s `serverOnly$`)

Since this is ultimately a limitation of Vite, not Remix, if you want to pursue this you could open up a discussion on Vite's GitHub repo or the Vite discord server. Closing this as there's nothing actionable to do about it on the Remix side.

**Comment by pcattori** [comment]
@sixers Changing `.server` modules to mark all exports with `serverOnly$` would introduce compiler-time magic that would add considerable complexity and degrade performance for all users of Remix.

It definitely something that could be done in a Vite plugin, but we don't think that the trade-offs are right for everyone so not something we are looking to including within the Remix plugin itself. Definitely something you could add alongside the Remix plugin if you found or created such a plugin.

Vite is already working on a Rust port of Rollup (which they are calling "Rolldown"). That could open the door to cross-module dead-code elimination during development with Vite.

**Comment by sixers** [comment]
@pcattori, ok, thank you for the explanation!

**Comment by pcattori** [comment]
Talking to @markdalgleish , he brought up a good point that wrapping all the exports in a `.server` module with `serverOnly$` during a compile step means that the types would be inaccurate during development (i.e. in your editor). For example:

```ts
import { getUser } from "~/.server/get-user.ts"

export default function ProfilePage() {
  const user = getUser()
  return <h1>{user.name}</h1>
}
```

TypeScript would happily report that nothing is wrong here, but in fact `getUser` will be `undefined` when this module executes in the client. That'll cause this route to crash.

Also, relying on compile-time magic instead of simple logic to throw when `.server` is imported by client means that any bugs in that compile-time step would result in server code leaking to the client.

So hopefully those two additional reasons strengthen the rationale for our decision to not implement such a feature in Remix.

**Comment by pcattori** [comment]
Thanks for your great questions @sixers ! Gave me the impetus to centralize all of our decisions around this in a [new decision doc](https://github.com/remix-run/remix/blob/main/decisions/0010-splitting-up-client-and-server-code-in-vite.md)
