### ISSUE TITLE
ErrorBoundary broken after 2.4.0 upgrade

### ISSUE THREAD

**Issue by Galante97** [remix-run/remix#8764]
### Reproduction

I have a /404 route that catches any invalid routes from a user and it should trigger the `errorBoundary`. Since upgrading to remix 2.4.0 and greater, the error boundaries appear to have a hydration issue or atleast lack their styling. This happens whenever a loader is responsible for triggering a error boundary. Client side errors that trigger the error boundary do not have this problem. 

**route general setup:**
```
export const loader: LoaderFunction = ({ request }) => {
  throw new Response('Page Not Found', {
    status: 404,
    statusText: `error`,
  });
};


export const ErrorBoundary: React.FC = () => {
  return <>Error page not found</>;
};
````

A couple other notes:
* Our **root.tsx** error boundary does not have this problem even though it is set up exactly the same way as all our other ones
* Adding in - **HydrateFallback()**  fixes the problem on a per route basis, however this feels more like a bandaid rather than a real fix. 
* This happens on higher environments other than localhost
* Not useful errors appear in the console or in the local server logs
* Any remix package below 2.4.0, the ErrorBoundary's work without issues

### System Info

```shell
"react": "^18.2.0",
    "react-dom": "^18.2.0",
    "@remix-run/css-bundle": "^2.6.0",
    "@remix-run/express": "^2.6.0",
    "@remix-run/node": "^2.6.0",
    "@remix-run/react": "^2.6.0",
```

### Used Package Manager

pnpm

### Expected Behavior

I would expect the `ErrorBoundary` to load successfully from the server without any hydration issues, or missing css. 

### Actual Behavior

Error boundaries appear to have a hydration issue and/or lack their styling.

**Comment by brophdawg11** [comment]
Could you provide a minimal reproduction of the issue?

**Comment by maxwithrow** [comment]
I'm working with @Galante97 on this project, while the effects aren't repro'd here (due to some of the specifics of what we're doing in our actual Meta/Head), what we believe to be the root issue is [here]( https://stackblitz.com/edit/remix-run-remix-fqrcmr?file=app%2Froot.tsx)

What we're seeing is that even though we have no client loaders anywhere, the [RootDefaultHydrateFallback](https://github.com/remix-run/remix/commit/001d3e0e4c06b66f4828ba903e2247e676d86880#diff-08892d3b7d67473f2da23abf1348c5013da7a36d72726be04c25f2b8b890a8f1R9) is being rendered for the root _on full document requests_ hitting our splat route. Note the developer message printed to the console when hitting that sandbox's /404 route, and the document response containing 2 `<html>` and `<head>` tags (one from our entry.server.tsx and one from the default hydrate fallback). We've been able to get around this by defining a `HydrateFallback` on our root that contains the Head and Meta components, or alternatively applying a `pnpm patch` to `@remix-run/react` that sets the react-router `v7_partialHydration` future flag false. Is it expected for that default HydrateFallback to come into play for the root with **_no_** client loaders present in the app at all?

**Comment by brophdawg11** [comment]
I'm not familiar with `remix-island` but I suspect that's your culprit 😄 

You are ending up with an HTML document embedded inside another HTML document.  The outer one is fine and is properly rendering the error boundary on the server - but the embedded one from remix-island is what's giving you the warning.

![Screenshot 2024-02-16 at 5 36 49 PM](https://github.com/remix-run/remix/assets/1609022/8effefa4-3081-49f6-9ffa-2471f2af33aa)

**Comment by jrestall** [comment]
If you are using remix-island to workaround hydration issues, you might have better luck using the canary version of React instead, especially if the hydration issues are in the head element.

**Comment by brophdawg11** [comment]
> My main question is why are we seeing that RootDefaultHydrateFallback coming through at all

Probably [this line in remix-island](https://github.com/Xiphe/remix-island/blob/main/src/index.ts#L79) which is removing the SSR errors, causing React Router to detect a route with a `loader` and no hydration data from SSR, which will cause it to run the loader during hydration
