### ISSUE TITLE
SPA mode: error when eveluating SSR module 

### ISSUE THREAD

**Issue by damaon** [remix-run/remix#8840]
### Reproduction

With such config:
```
import { vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [remix({ ssr: false }), tsconfigPaths()],
});
```

Taken from https://remix.run/docs/en/main/future/spa-mode

That I tried in my existing project, I am getting SSR errors which is weird when running `remix vite:dev`

### System Info

```shell
System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
    Memory: 109.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
  Browsers:
    Chrome: 121.0.6167.184
    Edge: 121.0.2277.128
    Firefox: 122.0.1
    Safari: 16.6
  npmPackages:
    @remix-run/dev: ^2.7.1 => 2.7.1
    @remix-run/node: ^2.7.1 => 2.7.1
    @remix-run/react: ^2.7.1 => 2.7.1
    vite: ^5.1.3 => 5.1.3
```

### Used Package Manager

yarn

### Expected Behavior

It compiles

### Actual Behavior

[vite] Error when evaluating SSR module virtual:remix/server-build: failed to import "/app/routes/_index.tsx"
|- ReferenceError: localStorage is not defined

**Comment by minimuscle** [comment]
Does this error happen if you run `build` it and then run the preview? I imagine it's just in dev mode as it runs the code on the server there.

**Comment by brophdawg11** [comment]
This is noted in the [`Caveats`](https://remix.run/docs/en/main/future/spa-mode#notescaveats) section in the docs.  SPA Mode _still has a server_ so that it can pre-render your root route and save it to an `index.html` file at build time.  It also uses that server during dev so it can handle HMR/HDR etc.  

What are you doing with `localStorage` in `_index.tsx`?  There's a few ways you can get past this:

* make the access defensive via something like `if (typeof window !== undefined)`,
* put the access into an effect which will only run on the client
* moving `localStorage` access inside a .client./ts file
* or using a `ClientOnly` component from `remix-utils`

**Comment by damaon** [comment]
My application "stores" are connecting to localStorage at "bootstrap". 

Thanks for reply. I had WTF moment with why exactly this happens and missed it in docs somehow.
