### ISSUE TITLE
remix-vite with radix-ui/themes@next suffrers serving allow list problem

### ISSUE THREAD

**Issue by GOWxx** [remix-run/remix#8967]
### Reproduction

I prepared a repository for reproduction. 
repository link: https://github.com/GOWxx/solve-remix-vite-add-radix-ui-themes-allow-list-problem
The steps are simple: 
1. pull down the repository 
2. run it 
3. see the prompt in the terminal.

The following is a prompt message:
The request url "[EDITED]/node_modules/.pnpm/@radix-ui+themes@3.0.0-rc.13-patch.1_@types+react-dom@18.2.19_@types+react@18.2.61_react-dom@18.2.0_react@18.2.0/node_modules/@radix-ui/themes/styles.css" is outside of Vite serving allow list.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 47.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    bun: 1.0.14 - /opt/homebrew/bin/bun
    Watchman: 2023.11.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 122.0.6261.94
    Chrome Canary: 124.0.6336.0
    Safari: 17.2.1
```

### Used Package Manager

pnpm

### Expected Behavior

no prompt.

### Actual Behavior

When using a basic remix-vite project with themes@next added, you may encounter prompts
The request url "..." is outside of Vite serving allow list.

**Comment by GOWxx** [comment]
link https://github.com/radix-ui/themes/issues/334

**Comment by GOWxx** [comment]
After checking the recent commit, I found that it may be related to this.
link #8950

**Comment by brophdawg11** [comment]
Yeah this would be due to #8950 - and is expected behavior for the default template.  We chose to set [`server.fs.allow`](https://vitejs.dev/config/server-options#server-fs-allow) to `app` by default so that Vite's dev server wouldn't serve files in the root of your application by default - as you may have sensitive information in them (`.env`, etc.).  If you need to serve specific files outside of `app`, you can either remove this configuration if it's not a concern for your app setup/development environment, or you can add the specific files you need to allow to that vite option.
