### ISSUE TITLE
Remix removes injected html from external script

### ISSUE THREAD

**Issue by theocerutti** [remix-run/remix#9016]
### Reproduction

1/ Create a new remix repo (in my test i used remix 2.8.1): `npm create remix@latest RemixTest`
2/ add this script under `<Links/>` element in the `head`:
```
        <script>
          const newDiv = document.createElement("div"); const newContent =
          document.createTextNode("Hi there and greetings!");
          newDiv.appendChild(newContent);
          document.documentElement.append(newDiv);
        </script>
```
3/ Run server and check if the node has been created.

Note: SOMETIMES the node is created sometimes not.

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 17.28 GB / 31.03 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Watchman: 20231210.093346.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 121.0.6167.184
```

### Used Package Manager

npm

### Expected Behavior

Remix should not delete nodes injected by external scripts on load.

### Actual Behavior

Remix delete nodes injected by external scripts on load.

**Comment by brophdawg11** [comment]
This is not a Remix issue but an invalid DOM modification when using React SSR + Hydration: https://react.dev/reference/react-dom/client/hydrateRoot#caveats

> hydrateRoot() expects the rendered content to be identical with the server-rendered content. You should treat mismatches as bugs and fix them

Hydration expects the initial client side render to match the server side render exactly - and mutating the DOM like this during page load will always cause issues.  Sometimes this is unavoidable due to browser extensions and other scenarios and React [is working on fixing those scenarios](https://github.com/facebook/react/issues/24430).  But your best bet is to avoid manually mutating the DOM outside of React - and especially before hydration.

Here's a few related issues/discussions in the Remix repo which may have some useful information for handling these scenarios: https://github.com/remix-run/remix/discussions/5244, https://github.com/remix-run/remix/discussions/4902

And a blog post from one of our community members: https://www.jacobparis.com/content/remix-hydration-errors
