### ISSUE TITLE
Unhandled error from promise in loader causes Remix to crash

### ISSUE THREAD

**Issue by jackie-greenbaum** [remix-run/remix#9178]
### Reproduction

My loader is defined like so:

```
export async function loader() {
  const data = {
    "myData": someAsyncFunction() // Not awaited
  }
  // Do other stuff here
  return defer(data)
}
```

If `someAsyncFunction()` throws an error before `defer` is called, Remix will not display an error, it will simply crash

**Repro:** https://stackblitz.com/edit/remix-run-remix-vmngcr?file=app%2Froutes%2F_index.tsx

Uncomment line 16 in `app/routes/_index.tsx` to see the crash

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 55.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 17.1
  npmPackages:
    @remix-run/dev: 2.4.0 => 2.4.0
    @remix-run/node: 2.4.0 => 2.4.0
    @remix-run/react: 2.4.0 => 2.4.0
    @remix-run/serve: 2.4.0 => 2.4.0
    @remix-run/server-runtime: 2.4.0 => 2.4.0
    vite: ^5.0.9 => 5.0.9
```

### Used Package Manager

npm

### Expected Behavior

Remix handles the error without crashing the server

### Actual Behavior

Remix crashes

**Comment by jackie-greenbaum** [comment]
> Do you have an ErrorBoundary on the route?

Yes, and it is not hit in this case (I added an `ErrorBoundary` to the linked example above)

**Comment by brophdawg11** [comment]
This is standard node behavior on unhandled promise rejections.  As of Node 16 (I think) they started terminating the process if left unhandled.  `defer` will handle the rejections _if it has been wired up prior to the rejection_.  But in this case, specifically you create a promise that Remix knows nothing about, and it rejects before you hand it off to `defer`, and because it's unhandled it terminates the process.

A quick workaround is to just hand the promise to defer at creation time, but the true fix is to add a [handler for unhandled rejections](https://nodejs.org/api/process.html#event-unhandledrejection) which will prevent the server from terminating. You could add something like this in your `entry.server.tsx` or express server:

```js
process.on("unhandledRejection", (reason: string, p: Promise<any>) => {
  console.error("Unhandled Rejection at:", p, "reason:", reason);
});
```

**Comment by brettdh** [comment]
@brophdawg11 Can you see how this at least feels like a bug in Remix, or perhaps a gap in its documentation? Handing the promise to `defer` ought to handle the promise, from the app's perspective. If Remix can't do that for some reason, the docs should warn developers about it - and maybe someone (not necessarily the Remix maintainers) should create an eslint rule to avoid this footgun. On the other hand, if Remix _can_ handle it, Remix _should_ handle it.

[Here's an example without Remix](https://stackblitz.com/edit/vitejs-vite-ssyjbq?file=main.js,style.css&terminal=dev) to show what I mean. If I create multiple promises and later pass them to e.g. `Promise.allSettled`, I do not expect an unhandled rejection, regardless of whether the promise rejects before or after I've "wired it up" to `Promise.allSettled`.

**Comment by brophdawg11** [comment]
> Handing the promise to defer ought to handle the promise

The promise is never makes it to `defer` in my testing, so there's nothing Remix can do it handle it - the node process is exiting as soon as you throw and it goes uncaught.  I never see `calling defer` logged in the. below example before the server crashes.

```js
export async function fakeApiRequest() {
  console.log("throwing error");
  throw new Error();
}

export async function loader() {
  const data = {
    data: fakeApiRequest(),
  };
  await sleep(1000); // <- Uncomment this line to see the crash
  console.log("calling defer");
  return defer(data);
}
```

I'm unsure the difference between your `Promise.allSettled` example and the `defer` case but if you can figure out how to get the previously-rejected Promise into `defer` I think it should handle it ok - if not we could look at fixing that as a bug.

**Comment by brettdh** [comment]
On reflection, I think the main difference was that my previous example was client-side javascript. [This example using Remix](https://stackblitz.com/edit/remix-run-remix-artf24?file=app%2Froutes%2F_index.tsx) (mainly so that the promise stuff runs server-side) but using `Promise.allSettled` instead of `defer` crashes in the same way. So I agree it's a weird node thing where a promise rejection can be considered "unhandled" if it hasn't been passed to a handler before the event loop tick where the rejection happens.

Just to completely rule out Remix, I also made [a repro using Express](https://stackblitz.com/edit/stackblitz-starters-qw192k?description=&file=pages%2Findex.html,index.js&title=Express%20Starter), and it crashes in the same way.

Thanks for the quick responses anyway. I'll look into more general NodeJS info about this. What would you think about keeping this issue open as a doc request? It's a fairly big gotcha with `defer`, and it seems like a common enough occurrence (see also #765) that a brief mention in the `defer` docs might save folks the confusion.

**Comment by jackie-greenbaum** [comment]
Thanks @brophdawg11 @brettdh for the good discussion (and the quick replies). I agree that this is not a Remix bug, and maybe some of my confusion stemmed from the lack of clear resolution on #765 as to whether or not Remix should handle this case.

I think manually responding to unhandled promises is a fine enough workaround, (remembering to `defer` immediately, OTOH, seems not super maintainable). I agree with @brettdh that perhaps a doc request might be good for this.

**Comment by brophdawg11** [comment]
yeah we'd definitely be open to a PR to the docs with a note about this if someone wanted to open a PR!  I do think that the default node behavior (terminating the process) is the right default behavior for a simple `remix-serve` server which tries to make very few opinions on your server configuration - since you can always choose to manage your server completely.

It's a hard balance to strike on making "opinions" on stuff like this that is not so much Remix-specific but a choice of some external technology.  We've learned the hard way a few times that often when we choose todo something beyond the default provided by the external tool, it fixes the issue being reported - but then causes new issues for a bunch of other folks who were relying on (or preferred) the default behavior.  So we're leaning more and more towards inheriting whatever the chosen defaults are - in this case letting node terminate the process without a user-added `unhandledRejection` listener.

**Comment by abarreraaponte** [comment]
This worked for me. Leaving the link here in case it helps another poor soul:
https://github.com/remix-run/remix/issues/765#issuecomment-2192517799
