### ISSUE TITLE
Splat Routes that would have been prioritized can be overridden by Dynamic Segments.

### ISSUE THREAD

**Issue by uttk** [remix-run/remix#9227]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-8kwmsm?file=app%2Froutes%2Fapi.%24.ts

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.1 - /usr/local/share/nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - /usr/local/share/nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.4 - /usr/local/share/nvm/versions/node/v20.11.1/bin/pnpm
```

### Used Package Manager

pnpm

### Expected Behavior

There are two paths in routes

- `api.$.ts` → return json
- `$username.profile.tsx` → returns the HTML of `/$username/profile`

At this point, the expected behaviour when requesting `/api/profile` is as follows.

- `api.$.ts` → matches `/api/profile`, return json
- `$username.profile.tsx` → do nothing as `api.$.ts` takes precedence

### Actual Behavior

- `api.$.ts` → no matches
- `$username.profile.tsx` → matches `/api/profile`, returns HTML before `api.$.ts`.

**Comment by brophdawg11** [comment]
This is expected behavior because both of these routes _do_ match and splat routes are the lowest ranking routes because they're intended to be "catch all" routes when nothing else matches - so the username route takes precedence.  There is an inherent ambiguity in your route configuration since it prevents any user from ever existing with the username `api`.  I would recommend changing to `user.$username.profile.tsx` to disambiguate these URLs.

**Comment by uttk** [comment]
@brophdawg11 

Thanks for the reply.
While there is certainly an inherent ambiguity in my route setup, I find this behaviour counter-intuitive.
At the very least, I would like a workaround that does not involve changing the route design.

**Comment by brophdawg11** [comment]
I'm afraid the workaround _is_ to avoid ambiguous routes.  React router scores dynamic params routes higher than splat routes by design and there is no way to get around that.  If you don't want to change your URLs then I would eliminate the ambiguity via `routes/api.profile.tsx`.

**Comment by kiliman** [comment]
Hmm.. I would figure that RR would match the static `/api` part of the path before it matched the dynamic `$username` param. Since neither segment is optional, the _splat_ part should only come into play once it has matched the initial prefix.

**Comment by brophdawg11** [comment]
That's not quite how it works, what you're describing is more aligned with the idea of [tree matching](https://github.com/remix-run/remix/discussions/4786) which we'd like to do, but it's not high on the list as a major breaking change.  Especially with the new [URLPattern](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern) API any future enhancements to route matching will likely move towards using that API instead of our own custom algorithm.

Currently, each segment gets a score and they're all added up, but the _order_ of those segments isn't considered.  Since both routes have a static segment they tie there, and then dynamic params rank higher than splat params which breaks the tie and ranks the username route higher.

**Comment by uttk** [comment]
>but the order of those segments isn't considered.

Why is this so? It looks strange from the side. 
The order of the segments is very important.

**Comment by brophdawg11** [comment]
Because it wasn't written that way when v6 was released and it would be a breaking change to alter that behavior

**Comment by doowb** [comment]
I don't think this issue should be closed just because fixing the bug will be a breaking change.

I've run into this bug because I have a route with multiple static segments and a splat `api.auth.$.ts`, then a new route is introduced that contains a static segment and multiple dynamic segments: `api.$v.$resource.$id.ts`.

When I make a post request to my splat route and even though the first 2 segments match the static segments of my splat route: `/api/auth/signin/foo`, I'm getting an error that indicates the other route needs an `action` method.

I believe this to be a bug because it's more natural to match the static segments before anything else.
