### ISSUE TITLE
[Bug]: Link not behaving as expected

### ISSUE THREAD

**Issue by movingelectrons** [remix-run/remix#944]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16.13

### Steps to Reproduce

        <ul>
          {data.testCaseGroupListItems.map((t) => (
            <li key={t.id}>
              <Link to={t.id}>{t.name}</Link>
              <a href={`/testCaseGroups/${t.id}`}>asda</a>
            </li>
          ))}
        </ul>

The <Link> tag is ignoring the id, the link it produces is just to the same page its on.  I have had to use the next line (the a tag) to get the right link.  I know this proabbly isn't nearly enough information to go from, but has anyone else run into this problem?  Its doing it on another page as well

### Expected Behavior

to link to the same page as the a tag

### Actual Behavior

links to same page its on

**Comment by christophgockel** [comment]
Just out of curiosity: how come you only link to `t.id`, but the href is `/testCaseGroups/${t.id}`?
Shouldn't the link look like this?

```diff
-<Link to={t.id}>{t.name}</Link>
+<Link to={`/testCaseGroups/${t.id}`}>{t.name}</Link>
```

**Comment by chaance** [comment]
I think the issue here is that you're expecting an `<a href>` to always match the behavior as `<Link to>`. That's not the case, and it's by design.

`<Link to={t.id}>` Would only resolve to `/testCaseGroups/${t.id}` if it is rendered in a route nested under the `testCaseGroups` route. The `to` value is relative to the current route. If you want it to resolve to `/testCaseGroups/${t.id}` on any route you need to type it that way, as the `/` indicates the path is relative to the root.
