### ISSUE TITLE
Routing issue with server routes configured in defineRoutes

### ISSUE THREAD

**Issue by mahmoudmoravej** [remix-run/remix#9524]
### Reproduction

Here is the stackblitz: https://stackblitz.com/edit/remix-run-remix-ivw6gy?file=vite.config.ts
I have a server only route (`/api`). it is working with default `vite.configs`. But if I use the `routes` section to customize routing table and also use `ignoredRouteFiles:["routes/*"]` (to avoid conflicts), it raises error on `yarn build` while it is still working on production. 

To test it in stackblitz, just call `yarn build`. 

### System Info

```shell
MacOs, chrom
```

### Used Package Manager

yarn

### Expected Behavior

customized routing should work with server routes too in both dev and production environment.

### Actual Behavior

it works in dev but not production.

**Comment by brophdawg11** [comment]
Routes cannot be "server only" because the client side router needs to know about them - even resource routes - so it can match them client side with forms/fetchers and such.  So you can't register the route itself as `.server.ts`.  Instead, you can have `api.ts` as the route and then it can import from a non-route server-only file, like `api-functions.server.ts`

**Comment by mahmoudmoravej** [comment]
Well, the main issue is different behaviours for one functionality(i.e. defining routes): 
- having `api.ts` inside routes folder (✅ both development and production)
- defning it through `routes: async (defineRoutes) => {...}` in vite.config.ts file. (✅ in dev, 🚫 in production)
