### ISSUE TITLE
Relax version of Prettier in `package.json` to support Prettier 3

### ISSUE THREAD

**Issue by tschaub** [remix-run/remix#9579]
### Reproduction

- Go to https://stackblitz.com/edit/remix-run-remix-onmeek?file=README.md
- Stop the dev server (`^C` in the terminal)
- Run `npm run lint`

Here is a repository with another demonstration of the issue: https://github.com/tschaub/remix-prettier-issue

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.9.2 
    @remix-run/node: * => 2.9.2 
    @remix-run/react: * => 2.9.2 
    @remix-run/serve: * => 2.9.2 
    vite: ^5.1.0 => 5.2.12
```

### Used Package Manager

npm

### Expected Behavior

I would expect that I could use Remix and an ESLint config that makes use of Prettier 3.  I was surprised to see that Remix has a dependency on Prettier that limits the linter setups that can be used with a Remix project.

### Actual Behavior

ESLint fails to find the `eslint-plugin-prettier` package.  There are two versions of `prettier` installed (v2 and v3), and the shared ESLint config depends on v3.

If `@remix-run/dev` works with Prettier 3 (and 2), it would be nice if the version specifier in the [`remix-dev/package.json`](https://github.com/remix-run/remix/blob/6b451613630436906713af462ee9af4516a51835/packages/remix-dev/package.json#L67) could be updated to reflect that.

See also https://github.com/remix-run/remix/issues/5444.

**Comment by brophdawg11** [comment]
I have a hunch the use of prettier will go away in the next version since we're leaning into TS for our templates/defaults.  Currently, you can run `npx remix reveal --no-typescript` and remix uses `babel` to strip the types from the built in `.tsx` defaults and then uses `prettier` to format the output it writes to your `entry.*.jsx` files

That said, this feels like more of an issue with an eslint setup or something.  The nesting of `node_modules` is specifically intended to allow different dependencies to have different nested dependencies.  So I don't see why it should be an issue that `@remix-run/dev` has it's dependency on prettier 2 and you want to use prettier 2 in your eslint setup.

**Comment by tschaub** [comment]
> That said, this feels like more of an issue with an eslint setup or something.

I agree.  It may be an issue with ESLint 8 that is solved with ESLint 9 (can't upgrade because too many plugins aren't ready for v9).

Thanks for the reply.  I'll close this since it sounds unlikely to be addressed - but I'll keep an eye out for either the removal of Prettier or an update to Prettier 3.
