### ISSUE TITLE
Double clicking on <Link to={} /> makes several requests to the parent routes

### ISSUE THREAD

**Issue by devmax214** [remix-run/remix#9656]
### What version of React Router are you using?

"@remix-run/react": "^2.8.1"

### Steps to Reproduce

I created a routes in my remix app as following;
```
<Routes>
  <Route file="root.tsx">
    <Route path="/org" file="./app/OrgPage.tsx">
      <Route path="teams" file="./app/TeamsPage.tsx" />
      ...
    </Route>
    ...
  </Route>
</Routes>
```

And added a component in the nested route `TeamsPage.tsx` page.
```
<Link to='/org/teams'>Teams</Link>
```

Btw, when I double click on the link in TeamsPage, it makes two requests to `/org/teams?_data=root.tsx` and `/org/teams?_data=/org`.

### Expected Behavior

It should request to only nested route `/org/teams` or do nothing.

### Actual Behavior

It sends the unexpected requests to the parent routes `/org/teams?_data=root.tsx` and `/org/teams?_data=/org`.

**Comment by brophdawg11** [comment]
This is by design - if you are already on `/org/teams` and you click a link to `/org/teams`, Remix treats that like a click of the browser refresh button and re-runs all of the loaders to get a fresh page.  You can opt-out of the parent loaders re-running via [shouldRevalidate](https://remix.run/docs/en/main/route/should-revalidate)
