### ISSUE TITLE
SingleFetch Fetcher State Issue in Remix: Missing Loading State After Submission

### ISSUE THREAD

**Issue by axbegue** [remix-run/remix#9733]
### Reproduction

https://github.com/axbegue/remix-test-fetcher
Go to http://localhost:3000/app/contactos and check the browser log

TestData.tsx:11 fetcher.state submitting {error: {…}}
TestData.tsx:11 fetcher.state loading {error: {…}}
TestData.tsx:11 fetcher.state idle {error: {…}}
TestData.tsx:13 
TestData.tsx:11 fetcher.state submitting {error: {…}}
TestData.tsx:11 fetcher.state idle {error: {…}}
TestData.tsx:13 
TestData.tsx:11 fetcher.state submitting {error: {…}}
TestData.tsx:11 fetcher.state loading {error: {…}}
TestData.tsx:11 fetcher.state idle {error: {…}}

### System Info

```shell
Windows 11, chrome
```

### Used Package Manager

npm

### Expected Behavior

I expect the fetcher state sequence follows 'submitting' -> 'loading' -> 'idle'. every time

### Actual Behavior

Hello! I'm encountering an issue with the new SingleFetch update "2.10.0" in Remix. When I submit a fetch, the fetcher's state transitions directly from 'submitting' to 'idle' and never enters the 'loading' state, except under specific circumstances. Initially, after a browser reload, the state sequence correctly follows 'submitting' -> 'loading' -> 'idle'. However, for any subsequent submissions, it skips the 'loading' phase and jumps directly from 'submitting' to 'idle'. Previously, I relied on the loading state to handle data right after submission. Now, without a consistent loading state, I'm unsure how to manage data immediately after it's been submitted. Has anyone else faced this problem, or does anyone have a suggestion on how to handle data right after submission with the current SingleFetch behavior? Any insights or advice would be greatly appreciated!, I just realize it only happens if one of the returned properties from the loader is a promise, and if I put a little delay on the loader, the state mark  'submitting' -> 'loading' -> 'idle' as it should be

**Comment by axbegue** [comment]
The problem doesn't happens on every fetch, you need to repeat the fetch 10 - 20 times to reproduce the problem

**Comment by brophdawg11** [comment]
As fas as I can tell, this is not a Remix issue but React seemingly not running or cancelling some `useEffect` calls because a subsequent `setState` came in.  When reproducing this (it only happens when the loader completes very quickly sub ~30ms in my testing) I can see that:

* The fetcher does go into a `loading` state
* React Router's `RouterProvider` sees the `loading` state and calls `setState`
* The `TestData` component renders with the `fetcher.state` of `loading`
* But then if the `idle` state come sin quick enough the `useEffect` never runs for loading and only runs for the latest `idle` state

I used this code in `TestData`:

```js
  console.log('TestDara fetcher.state (render)', fetcher.state);
  useEffect(() => {
    console.log('TestData fetcher.state (effect)', fetcher.state);
  }, [fetcher.state]);
```

And see this in the console (along with my console logs added to the `RouterProvider` internal setState call):

![Screenshot 2024-07-10 at 10 10 09 AM](https://github.com/remix-run/remix/assets/1609022/b84c0d8d-5698-4aab-84dc-cced00ed9d3d)

Notice that you do see `TestData fetcher.state (render) loading` but you never see `TestData fetcher.state (effect) loading`.

If this is an issue for your application I would avoid using an effect on the `loading` state and instead use it based on `fetcher.data` or something else.  Another option is to use a `Promise.all()` with a small timeout value of 100ms or something to ensure the loader doesn't complete so fast causing React to skip the `useEffect`
