### ISSUE TITLE
Link tag navigating to route reloads page & no network fetch calls

### ISSUE THREAD

**Issue by neerajrathore** [remix-run/remix#9805]
### Reproduction

https://stackblitz.com/~/github.com/neerajrathore/remix-it-latest

### System Info

```shell
System:
    OS: Windows 11
  Binaries:
    Node: 18.18.0 
    Yarn: 1.22.22
```

### Used Package Manager

npm

### Expected Behavior

page should not reload while navigating, so I can see Fetch type requests for that route in network tab chrome

![image](https://github.com/user-attachments/assets/6422bafb-cfca-45bd-80ae-9f63e07a74a4)

### Actual Behavior

![image](https://github.com/user-attachments/assets/616d608c-e519-4107-9e9b-b7fa69bdfd5e)

**Comment by brophdawg11** [comment]
This is due to the error from your `main.css` file:

![Screenshot 2024-07-30 at 10 11 34 AM](https://github.com/user-attachments/assets/7fa44109-de38-4b5a-b754-68b7d8544c8d)

It looks like you are missing the `?url` parameter:

```js
// root layout will always be processed on the server side so don't import css using ?url  
import MainStyle from '~/styles/main.css'
``` 

That comment is not accurate since the root layout is also client-side rendered during hydration and on SPA navigations.
