### ISSUE TITLE
Cookie Session Storage value received from root loader sometimes stale

### ISSUE THREAD

**Issue by mattwhitson** [remix-run/remix#9845]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-ep51bx?file=README.md

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.11.1 
    @remix-run/node: * => 2.11.1 
    @remix-run/react: * => 2.11.1 
    @remix-run/serve: * => 2.11.1 
    vite: ^5.1.0 => 5.4.0 

(This is from stackblitz)
```

### Used Package Manager

npm

### Expected Behavior

I would expect the cookie value to be updated

### Actual Behavior

To reproduce this (and it doesn't always happen on stackblitz it seems, but it almost always occurs on my local machine), you need to first load the root page. Then, navigate via your search bar to any other page (in this project's case, the only other page is /random-route). This step is important, because the issue only occurs if you don't navigate via a Link from the root to another page. Now when you've reached /random-route, update the cookie by pressing the button. In the console logs on stack blitz, you'll see that the root loader is recalled and receives the new cookie value. Now, click the back button on your browser and navigate back to the root page. You should see that the loader value being logged in your browser's dev tools is the old, stale cookie value. I've attached a video below demonstrating the issue in case you are unable to reproduce it.

https://github.com/user-attachments/assets/b6c877a8-7b1a-4590-b10f-52b69ec12e43

**Comment by brophdawg11** [comment]
This is a caching issue:

* When you load the root route, it makes a document request, runs the loader, and serializes the initial loader data into the HTML document (cookie value of `1`)
* The you do a second document request to `/random-route`, click the button,  and updates the cookie to `2`
* When you click back, it's a fresh document request, not a `history.go` since you did a hard navigation to `/random-route`
* Without any explicit caching headers on the original document request, the browser may default to serving a cached HTML document - which has the stale loader data value in it (`1`).  It never re-runs your server loader and thgus never reads the updated cookie value of `2`

If you check `Disable Cache` in dev tools you will see the problem no longer exists.

You likely want to put a `cache-control` header on your document to avoid caching it, or potentially you could look into a `Vary: Cookie` header if your deployment setup supports `Vary`

**Comment by mattwhitson** [comment]
@brophdawg11 Cheers, thanks for the explanation!
