### ISSUE TITLE
[single-fetch]: Link component causes re-render when `discover` is not set to `none`

### ISSUE THREAD

**Issue by paul-vd** [remix-run/remix#9847]
### Reproduction

1. Pull the https://github.com/paul-vd/remix-reproduction repository → Install and run dev locally
3. Navigate to the `/broken` page → open browser console
4. Click the reload button → verify logs in console

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 25.18 GB / 47.01 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
    bun: 1.1.21 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.182
  npmPackages:
    @remix-run/dev: ^2.11.1 => 2.11.1 
    @remix-run/node: ^2.11.1 => 2.11.1 
    @remix-run/react: ^2.11.1 => 2.11.1 
    @remix-run/serve: ^2.11.1 => 2.11.1 
    vite: ^5.1.0 => 5.4.0
```

### Used Package Manager

pnpm

### Expected Behavior

It should log rerender 0 and 1
```
rerenders (root/routes/broken): 0
rerenders (root/routes/broken): 1
```

### Actual Behavior

It rerenders multiple times
```
rerenders (root/routes/broken): 0
rerenders (root/routes/broken): 1
rerenders (root/routes/broken): 2
rerenders (root/routes/broken): 3
```

### Proof

https://github.com/user-attachments/assets/62a810e8-319c-4975-8611-27be81c7263a

**Comment by brophdawg11** [comment]
This is expected behavior because when we discover routes, we update our route tree which causes a React Context update at the root of the Remix component tree.  You're seeing extra renders in your specific setup because you're using `useMatches` in your hook and that hook accesses the context that is updated, so it is expected to cause a re-render when the context updates.  This context update is required so that once we discover routes, we can trigger subsequent functionality related to matching to proceed, such as `<Link prefetch="render">`.

If you remove the custom hook and just `console.log('rendering')` in your component, you'll see that the `BrokenExample` component doesn't re-render when it is not accessing the context in question.
