### ISSUE TITLE
unstable_data response headers not set

### ISSUE THREAD

**Issue by ziimakc** [remix-run/remix#9849]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-stsale?file=app%2Froutes%2F_index.tsx

### System Info

```shell
-
```

### Used Package Manager

npm

### Expected Behavior

As [stated in docs](https://remix.run/docs/en/main/route/headers), if `a` route doesn't have `headers` function, then root `headers` should take over.

### Actual Behavior

If `a` route headers function is removed, headers doesn't apply.

### Side note

If this is supposed behavior, I would ask to consider some alternative, otherwise use will need to add `headers` to every route.

**Comment by brophdawg11** [comment]
The root `headers` function is taking over - the issue is that you are not actually returning any headers from it 😄 

The arguments to the root `headers` function are:
* `loaderHeaders` - the root loader headers - which does not exist, so this is empty
* `actionHeaders` - the root action header - which does not exist, so this is empty
* `errorHeaders` - any thrown error response headers - which does not exist, so this is empty
* `parentHeaders` - any parent loader headers - but root has no parent, so this is empty

So you are merging 4 empty `Headers` instances.

If you add a root loader that has headers, it works as expected: https://stackblitz.com/edit/remix-run-remix-rtbajt?file=app%2Froot.tsx

![Screenshot 2024-08-12 at 9 57 52 AM](https://github.com/user-attachments/assets/6319183d-66cb-4368-a773-91e5374b9fbd)

It seems you might be expecting the root `headers` function to have access to the `X-YQQQ` and `X-q` headers you are adding to the loader response from `routes/_index` but that is not how it works.  Parent's cannot access their children's headers.  Only children can access parents headers via `parentHeaders` for merging.

So if you want to return headers specific to `routes/_index` from it's `loader`, then you will need a `headers` function in `routes/_index` to properly merge those with any headers coming from parent `headers` functions.

**Comment by ziimakc** [comment]
@brophdawg11 that's means that I will need to use `mergeHeaders` for every route where I use action or loader which is inconvenient and not the way as it works currently.  I would ask to reconsider this and revert a removal of `ResponseStub`
```
export const headers: HeadersFunction = ({
  actionHeaders,
  errorHeaders,
  loaderHeaders,
  parentHeaders,
}) => {
  return mergeHeaders([
    parentHeaders,
    loaderHeaders,
    actionHeaders,
    errorHeaders,
  ]);
};
```

**Comment by brophdawg11** [comment]
> not the way as it works currently.

This is already how `headers` works for document requests - we're just aligning single fetch data requests with document requests since they're effectively the same idea - one request for may routes.  Then, if your loaders return headers, you need to tell Remix how to merge them.

> for every route where I use action or loader

Not quite - you only need to include a `headers` function on routes where the `action`/`loader` returns custom headers.

This requires a `headers` function:

```jsx
export function loader() {
  return unstable_data(data, { headers: { 'x-whatever' } });
}
```

This does not:

```jsx
export function loader() {
  return data;
  // or:
  return unstable_data(data);
}
```

**Comment by ziimakc** [comment]
@brophdawg11 this is not how it currently works with `json`, just tested it again.

I set headers in all the loaders because of tokens exchange and I don't have a single `headers` function export, adding it for every route is a breaking change and a bit inconvenient.

**Comment by brophdawg11** [comment]
Yes, it is for _Document_ requests as stated above - see https://stackblitz.com/edit/remix-run-remix-arw1rb?file=app%2Froutes%2Fpage.tsx for a simple example.

_Data_ requests currently don't need a `headers` function because each route is it's own HTTP request so we can return the Response from the `loader` directly.

Again, the Single Fetch feature aligns data requests with how document request already work.  Now that there is one request for _all_ loaders on data requests (just like document requests), you are required to implement a `headers` function for data requests as well to manage the merging of headers from multiple loaders.

Yes this is a breaking change and that's why it's behind a future flag :)

This might be a bit inconvenient but we believe this is a better/simpler approach as it removes the ambiguity that exists today.  Because you don't have any `headers` function, your current application is likely not returning any of your custom headers on document requests unbeknownst to you.  By aligning these two approaches we're making this behavior more consistent and explicit.

**Comment by lilouartz** [comment]
What is this `mergeHeaders` function?

I think I need it too

**Comment by lilouartz** [comment]
Is it just something like:

```ts
export const mergeHeaders = (headers: Array<Headers | undefined>) => {
  const mergedHeaders = new Headers();

  for (const header of headers) {
    if (!header) {
      continue;
    }

    for (const [key, value] of header.entries()) {
      mergedHeaders.append(key, value);
    }
  }

  return mergedHeaders;
};
```

?

Is it safe to do something like this in my routes?

```ts
({ actionHeaders, errorHeaders, loaderHeaders, parentHeaders }) => {
  return mergeHeaders([
    actionHeaders,
    errorHeaders,
    loaderHeaders,
    parentHeaders,
  ]);
}
```
